### ISSUE TITLE
App XXX is not available from this account.

### ISSUE THREAD

**Issue by Nothing4You** [SteamRE/DepotDownloader#1]
Hi,
I'm having this problem with multiple games, tried with some I own first, then with an F2P game.
Could this be SteamGuard related?
`mono DepotDownloader.exe -app 440 -user $user -pass $pass`

```
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 91
Got AppInfo for 440
App 440 (Team Fortress 2) is not available from this account.
```

**Comment by murghem200** [comment]
hi 
I'm having this problem with multiple games
Could this be SteamGuard related?
.\DepotDownloader.exe -app 2420110 -depot 2420111 -manifest 2239037909320851046 -userename $uesrname -password $password

Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 126
Got AppInfo for 2420110
App 2420110 (Horizon Forbidden West? Complete Edition) is not available from this account.
Disconnected from Steam

**Comment by JamieD91** [comment]
I'm having the same issue :( I've stared out my personal details:
C:\Windows\System32>"D:\Downloads\DepotDownloader-windows-x64_2\DepotDownloader.exe" depotdownloader -app 1449850 -depot 1449851 -manifest 8126584179407533853 -username **************
Enter account password for "***********": ****************
Connecting to Steam3... Done!
Logging '*********' into Steam3...
STEAM GUARD! Use the Steam Mobile App to confirm your sign in...
 Done!
Using Steam3 suggested CellID: 85
Got 327 licenses for account!
Got AppInfo for 1449850
Using app branch: 'public'.
Depot 1449851 is not available from this account.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Disconnected from Steam
