### ISSUE TITLE
Download suddenly stopped working?

### ISSUE THREAD

**Issue by qstlijku** [SteamRE/DepotDownloader#102]
Hi, earlier I tried to download a previous manifest for a depot, and everything seemed to be working fine. But now when I went to try to resume the download, I'm getting the error "Depot 360431 (Retail Content) is not available from this account."

I tried deleting all the downloaded depot files, and even reinstalling the depot downloader, but it's still giving the error. Any ideas on what could be causing this? It seems to be failing for all depots in only that specific app though, I tried another app and it works fine.

**Comment by qstlijku** [comment]
I should note this is not the same error as if the app isn't available. If I try the same command from the anonymous account, I get the error "App 360430 (Mafia III: Definitive Edition) is not available from this account."

**Comment by nikop** [comment]
Probably due to Valve's change to start requiring use of package tokens to get info. Depot Downloader needs to be updated to support those.

**Comment by xPaw** [comment]
Can you test #103?

**Comment by qstlijku** [comment]
Is there a release version of the latest commit? I don’t have stuff set up for me to build it myself.

**Comment by azuisleet** [comment]
This has been released as https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.6

**Comment by bugsebe** [comment]
Reopen this. it's not working again.
