### ISSUE TITLE
Redistribute DepotDownloader

### ISSUE THREAD

**Issue by Aflito** [SteamRE/DepotDownloader#105]
Hey SteamRE Team! =)

First of all, many thanks for this project as a whole, I'm creating a launcher for Dead By Daylight to download and play older versions of the game easily. Instead of directing your typical layman to download the release from Github, install .net core and run DepotDownloader, I would like to bake Depot Downloader into my app and ship a single package containing all that you need to run the game, of course, with all credit and linking to this github repo.

Is this allowed under GPL 2? do i need to ship your source code with my app aswell?

Again, thank you very much for all the effort and work into creating tools like this

**Comment by azuisleet** [comment]
GitHub provides some advice about the GPL on the license page:

https://github.com/SteamRE/DepotDownloader/blob/master/LICENSE

If you incorporate GPL code into your application, your application must be distributed under the GPL and include the source code.

**Comment by Aflito** [comment]
Thank you!
