### ISSUE TITLE
Encountered unexpected error...

### ISSUE THREAD

**Issue by paulnevada1983** [SteamRE/DepotDownloader#106]
Encountered unexpected error downloading chunk... [] A task was canceled. Why is it happening?

**Comment by azuisleet** [comment]
The error message should actually indicate that is expected. This is a common occurrence and it can be due to a variety of network conditions. As long as the program continues to execute, it will retry those chunks.

**Comment by paulnevada1983** [comment]
Well, ok. But, how can I orient this is in progress?

**Comment by azuisleet** [comment]
Unless there's something specific, I cannot diagnose slow downloads.
