### ISSUE TITLE
Questions about low speed on downloads

### ISSUE THREAD

**Issue by PaulNevada** [SteamRE/DepotDownloader#107]
1. Does it support resume downloading?
2. My speed is really slow - about 1 MB/s - is it ok?
Thanks!

**Comment by paulnevada1983** [comment]
?

**Comment by paulnevada1983** [comment]
???

**Comment by azuisleet** [comment]
This was merged into ac97c011077f8476beee540f04c8a3e220744233. A new release is pending.
