### ISSUE TITLE
Operation was canceled on downloading manifest

### ISSUE THREAD

**Issue by Kenpari** [SteamRE/DepotDownloader#108]
Attempting to download any manifest results in the following error:

Encountered error downloading manifest for depot <depotid> <manifestid>: The operation was canceled.

Tried this with 3 distinct manifests from 2 different apps. Error repeats in a loop and no content is downloaded.

**Comment by azuisleet** [comment]
If this is still an issue, please include diagnostic output by including "-debug" and open a new issue.
