### ISSUE TITLE
Can't open the .sln file

### ISSUE THREAD

**Issue by DatDraggy** [SteamRE/DepotDownloader#11]
I can't open it and only get an error. Is there a compiled version somewhere maybe?

**Comment by BenVlodgi** [comment]
Are you using Visual Studio 2010 or higher?

**Comment by psychonic** [comment]
> Is there a compiled version somewhere maybe?

Yes.
https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.2.0
