### ISSUE TITLE
Access denied. Same as issue #32

### ISSUE THREAD

**Issue by Ancientkingg** [SteamRE/DepotDownloader#111]
![image](https://user-images.githubusercontent.com/67058024/85009213-5cc9e980-b15e-11ea-8ead-9060fb172b85.png)

Access to certain depots of the app Rainbow six: Siege are denied although I have the game owned. Any fix for this or is this on Steam's part?

**Comment by azuisleet** [comment]
This appears to be related to a FreeOnDemand license. I don't know exactly what the specifics are here, but it needs to be claimed on the store. If you have more information, feel free to re-open the issue.
