### ISSUE TITLE
Depot update process does not delete files

### ISSUE THREAD

**Issue by NicknineTheEagle** [SteamRE/DepotDownloader#112]
Sometimes, files are removed in new depot versions, Steam deletes such files from storage when updating a game but DepotDownloader doesn't. Is this intentional? This can potentially create issues depending on how the game is coded.

**Comment by azuisleet** [comment]
Deleted files are indeed not implemented.

**Comment by NicknineTheEagle** [comment]
Is this on purpose? If not, I can add this real quick.

**Comment by azuisleet** [comment]
Sure. My guess is the best way to approach this is to compare the old and new manifests and look for files that no longer exist.

**Comment by xPaw** [comment]
Don't forget the files may be moved between depots.

**Comment by NicknineTheEagle** [comment]
> 
> 
> Don't forget the files may be moved between depots.

Depots are handled one by one so that shouldn't pose a problem.

**Comment by NicknineTheEagle** [comment]
> 
> 
> Don't forget the files may be moved between depots.

Oh, snap, I forgot about this. I know Doom (379720) did this. I'll have to think how to handle this.

**Comment by NicknineTheEagle** [comment]
> 
> 
> Don't forget the files may be moved between depots.

@xPaw Do you know any games that did this? I wonder if Steam actually handles this properly.

**Comment by xPaw** [comment]
I can't remember a specific example, but that does happen sometimes. And I believe Steam has no problem with that.

**Comment by azuisleet** [comment]
This is probably the same logic that needs to exist for detecting renames anyway. We could check for matches by hash in the previous manifest (eg for a rename in an update) and matches by hash in other manifests loaded (as an opportunistic lookup).

However, I don't believe we do any opportunistic loading, so I'm not certain if the second part can be implemented today.
