### ISSUE TITLE
Mono DepotDownloader failed to connect "Unable to get steam3 credentials"

### ISSUE THREAD

**Issue by Craftplorer** [SteamRE/DepotDownloader#12]
When i enter following command `mono DepotDownloader.exe -app 730` i get the message "Connecting to Steam3..." and then about 20 times "Reconnecting" after the "Reconnecting" messages i get "Timeout connecting to Steam3." "Unable to get steam3 credentials.".

I tried to monitor the connecting via wireshark. [Wireshark Dump hosted on Google Drive](https://goo.gl/BUZ5DN)
I just get a `Server Hello Done` from steam.
I tried the same thing on my windows machine there i got a `Client Key Exchange, Server Hello Done` from steam.

I added the mozilla certificate to the mono certificate pool so it should trust it. 

If you have any question or need more information please ask.
And please excuse my bad english.

**Comment by Tidro** [comment]
SOLVED:
official install guide: http://www.mono-project.com/docs/getting-started/install/linux/
The package ca-certificates-mono should be installed to get SSL certificates for HTTPS connections. Install this package if you run into trouble making HTTPS connections.
EXAMPLE:
`apt-get install ca-certificates-mono`
