### ISSUE TITLE
Is there any limit when requesting files?

### ISSUE THREAD

**Issue by z3nth10n** [SteamRE/DepotDownloader#122]
Well I would like to know if there is any rate limit when downloading files from the workshop using this tool.

For example, Steam Web API is limited to 100,000 calls per day.

Thanks!

**Comment by yaakov-h** [comment]
I'm not aware of any.

**Comment by z3nth10n** [comment]
How many files did you download at once with this tool?

**Comment by xPaw** [comment]
Create an issue when you actually run into problems when downloading files. This software works the same way Steam client itself does.

**Comment by z3nth10n** [comment]
Ok thanks, close it then, I'll re-open it if I run into problems. I need to do a crawler, and I don't know if such thing is legal (I think it's legal if I don't redistribute any file). But as you can see I need to do so many requests so I'm not sure if my IP can get banned if I do this.

Thanks anyway guys! :P
