### ISSUE TITLE
Steam install prompt

### ISSUE THREAD

**Issue by torskyy** [SteamRE/DepotDownloader#123]
Hi, i've been trying to download the oldest version of Human: Fall Flat, it downloaded, i launched the .exe but steam prompted me to install Human: Fall Flat, any fix?

**Comment by xPaw** [comment]
Yes, install Steam.

**Comment by paulnevada1983** [comment]
Here's what to do:
1. Download the regular (latest) game's version via Steam.
2. Delete all the files in the game's main folder.
3. Place all the files you got via DD to their initial place (#2).

**Comment by torskyy** [comment]
> Here's what to do:
> 
> 1. Download the regular (latest) game's version via Steam.
> 2. Delete all the files in the game's main folder.
> 3. Place all the files you got via DD to their initial place (#2).

Thank you, it helped.
