### ISSUE TITLE
Manifest ids for password protected beta branches

### ISSUE THREAD

**Issue by bgkillas** [SteamRE/DepotDownloader#124]
is there no way to find a manifest id for a password protected beta branch even if you have the password?

**Comment by paulnevada1983** [comment]
Did you get (understand) what you've just asked? :)

**Comment by bgkillas** [comment]
> Did you get (understand) what you've just asked? :)

i just think its weird that you can get only the latest manifest for a beta branch

**Comment by paulnevada1983** [comment]
> > Did you get (understand) what you've just asked? :)
> 
> i just think its weird that you can get only the latest manifest for a beta branch

Now got it...

**Comment by azuisleet** [comment]
There is no manifest history available for Steam users.
