### ISSUE TITLE
Connection timeout downloading chunk 0496f4d6addef11874bf0b7170f4fc14b8239f85

### ISSUE THREAD

**Issue by Slaint46** [SteamRE/DepotDownloader#125]
Connection timeout downloading chunk 0496f4d6addef11874bf0b7170f4fc14b8239f85

**Comment by yaakov-h** [comment]
This needs more info to be remotely actionable.

**Comment by rossengeorgiev** [comment]
Connection timeout downloading chunk 0496f4d6addef11874bf0b7170f4fc14b8239f85
