### ISSUE TITLE
Decrypt branch?

### ISSUE THREAD

**Issue by toinou181** [SteamRE/DepotDownloader#126]
I analyzed the source code of the depotdownloader and I found lines implying that we could decrypt encrypted manifests
could someone explain to me please?

**Comment by azuisleet** [comment]
Depending on the encryption method, the encryption key is either derived from the password, or Steam validates the password and supplies the encryption key. You can review the code here:

https://github.com/SteamRE/DepotDownloader/blob/master/DepotDownloader/ContentDownloader.cs#L251
