### ISSUE TITLE
Manifest ID is not a valid value for UInt64

### ISSUE THREAD

**Issue by kommersch** [SteamRE/DepotDownloader#129]

**Comment by kommersch** [comment]
Trying to fetch a depot brings up "System.ArgumentException: 422DCB519C14AFA72967026E24923D8C is not a valid value for UInt64."
Happens when trying this(login excluded): "dotnet DepotDownloader.dll -app 250820 -depot 250824 -manifest 422DCB519C14AFA72967026E24923D8C"

**Comment by azuisleet** [comment]
After some discussion, I think we agree that this is probably not worth supporting.

Decrypting a manifest ID for a branch requires the password. This is really only useful for decrypting the current manifest, as anything historical might use a different encryption key depending on the circumstances (such as the beta password changing).

You need to pass the decrypted manifest ID for this parameter.

**Comment by kommersch** [comment]
Ok, I was not aware these are encrypted. My apologies.
