### ISSUE TITLE
Mono DepotDownloader gets 401 on all apps

### ISSUE THREAD

**Issue by pjseipel** [SteamRE/DepotDownloader#13]
Running on Linux using Mono.  Regardless of what app I try to download, I get a 401 error.  Tried a number of different things but not sure what I'm doing incorrectly.  I can't even get just the depot manifest.

> mono DepotDownloader.exe -app 620 -username []l -password [] -dir ~/Downloads/Temp
> Connecting to Steam3... Done!
> Logging '[]' into Steam3...This account is protected by Steam Guard.
> Please enter your 2 factor auth code from your authenticator app: MFHGQ
> Retrying Steam3 connection... Done!
> Logging '[]' into Steam3... Done!
> Using Steam3 suggested CellID: 63
> Got 96 licenses for account!
> Licenses: 965, 700, 2206, 1178, 1238, 469, 1679, 663, 1451, 1182, 1181, 1180, 6146, 3083, 7369, 7877, 2916, 12248, 13858, 15409, 11463, 13503, 14839, 15609, 17976, 13054, 11001, 12318, 18976, 13533, 13123, 29136, 13437, 27190, 17110, 26016, 38068, 36614, 14433, 40537, 32335, 43168, 50073, 46867, 53345, 35401, 44712, 41133, 26595, 28521, 40245, 51156, 66010, 62532, 70491, 36425, 59273, 68475, 61326, 75481, 52167, 33775, 50918, 27437, 105051, 108960, 110652, 38647, 103396, 41703, 32132, 1774, 28315, 2832, 17697, 62759, 15953, 17079, 19132, 135914, 56692, 75197, 90859, 132479, 0, 90033, 39187, 50760, 57566, 50980, 15015, 29616, 88801, 50845, 67596, 1259
> Got session token!
> Got AppInfo for 620
> Depot 660 (Portal 2 - Sixense Motion) is not available from this account.
> Got appticket for 624!
> Got depot key for 624 result: OK
> Got appticket for 623!
> Got depot key for 623 result: OK
> Got appticket for 622!
> Got depot key for 622 result: OK
> Got appticket for 621!
> Got depot key for 621 result: OK
> Got appticket for 625!
> Got depot key for 625 result: OK
> Got appticket for 626!
> Got depot key for 626 result: OK
> Got appticket for 627!
> Got depot key for 627 result: OK
> Got appticket for 628!
> Got depot key for 628 result: OK
> Got appticket for 661!
> Got depot key for 661 result: OK
> Depot 323180 (Portal 2 Soundtrack (323180) Depot) is not available from this account.
> Downloading depot 624 - portal 2 client binaries
> Downloading depot manifest...Got CDN auth token for cdn.comcast.cs.steampowered.com result: OK (expires 1/19/2017 1:50:01 AM)
> Initialized connection to content server cdn.comcast.cs.steampowered.com:80 (CDN) with depot id 624
> Encountered 401 for depot manifest 624 1468736509491635097. Aborting.
> 
> Unable to download manifest 1468736509491635097 for depot 624

Any idea what I'm doing wrong?  I own a licence for the app. 401 is 'access denied' correct?

**Comment by azuisleet** [comment]
You will need to build from the latest version of SteamKit and DepotDownloader because of a recent change to CDNs. The fix is in 97b8716 but this is pending a minor release of SteamKit in order to do a DepotDownloader release.

**Comment by pjseipel** [comment]
Got it working, thanks.
