### ISSUE TITLE
Proofs for the very slow (10 Mbit/sec)  downloads with all the available parameters on...

### ISSUE THREAD

**Issue by paulnevada1983** [SteamRE/DepotDownloader#130]
What proofs do I need to provide to you and how? I'll make them. Just tell me, please. Thanks!

**Comment by VoiDeD** [comment]
@paulnevada1983 please keep the discussion to a single issue (#127).

**Comment by paulnevada1983** [comment]
They don't talk in there...

**Comment by psychonic** [comment]
That's not really relevant.

**Comment by paulnevada1983** [comment]
What do you mean by that?
