### ISSUE TITLE
How To ignore the download of specific file extensions *.wmv and *.avi

### ISSUE THREAD

**Issue by gregstein** [SteamRE/DepotDownloader#133]
Hello,

I'd like to start by saying kudos for this awesome project <3 I LOVE IT!

So I'm wondering if we can ignore downloading specific file extensions from depots such as video files *.wmv and *.avi to speed up the download because these video files take more than 1 GB of space and consume time.

Thank you,

**Comment by VoiDeD** [comment]
See the `-filelist <file.txt>` argument - with that you can use regex expressions in the file to specify what files to download.

Using a negative lookahead you can filter out files, which should work in theory. Try: `^(?!.*\.(wmv|avi)).*$`

**Comment by paulnevada1983** [comment]
> See the `-filelist <file.txt>` argument - with that you can use regex expressions in the file to specify what files to download.
> 
> Using a negative lookahead you can filter out files, which should work in theory. Try: `^(?!.*\.(wmv|avi)).*$`

Thanks - will test it soon... And I thought DD needs to be upgraded only to have -filelist in the opposite action...

**Comment by gregstein** [comment]
> See the `-filelist <file.txt>` argument - with that you can use regex expressions in the file to specify what files to download.
> 
> Using a negative lookahead you can filter out files, which should work in theory. Try: `^(?!.*\.(wmv|avi)).*$`

Thank you soo much!! I can't believe I missed that.. Impressive!!
