### ISSUE TITLE
Timeout connecting to Steam3

### ISSUE THREAD

**Issue by West0401** [SteamRE/DepotDownloader#137]
Hello everyone, i have an issue with connecting to Steam. I just don't understand what am i doing wrong. I tried many many ways to solve it, but i could not. And now i'm begging; please help me with my trouble.

Timeout connecting to Steam3.
Unable to get steam3 credentials.
Error: InitializeSteam failed

Thank you for understanding.

**Comment by azuisleet** [comment]
You could have a firewall blocking the software.

**Comment by West0401** [comment]
> 
> 
> You could have a firewall blocking the software.

I've checked it: my firewall is fully off.

**Comment by AraHaan** [comment]
I tired this too and it fails for me as well:

```
dotnet DepotDownloader.dll -app 237310 -depot 237311 -manifest 2371460163047557358 -username LabyPafait -password [redacted password] -validate
Connecting to Steam3... Done!
Logging 'LabyPafait' into Steam3...Unable to login to Steam3: InvalidPassword
Disconnected from Steam
Unable to get steam3 credentials.
Error: InitializeSteam failed
```

I have verified that the password I entered is correct on my end as I am able to successfully login in my internet browser, it just fails to go to the steam guard stuff however.

**Comment by macvaer** [comment]
Who is know how to fix it ?

**Comment by macvaer** [comment]
Fix and will working:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\KeyIso
"Start"=dword:00000003
