### ISSUE TITLE
I seem to be unable to download previous manifests of depots.

### ISSUE THREAD

**Issue by wertercatt** [SteamRE/DepotDownloader#14]
I'm using the command 
DepotDownloader -username wertercatt -password [mypasswordhere] -depot 441 -manifest 3605898397490469600 -app 440

Which should get me a previous version of the depot "TF2 Client server shared," however, it still seems to download the latest version of the depot. Is this an intentional change Valve did, or is this a bug with the program?

(Sidenote: Why was the -version parameter removed? Can you no longer get the manifest information for a specific build version from Steam?)

**Comment by azuisleet** [comment]
I tried this command line and it does download from the correct manifest, though for constructing the actual path it just grabs the current build number (1572474).

The version parameter referred to the version used for Steam2 content servers. The new SteamPipe content system only uses manifest IDs for referencing files.

I'm not aware of any way to retrieve a manifest ID except for observing the current app info.

**Comment by wertercatt** [comment]
So, is there any way for it to grab the correct build number for a manifest, so it has the right path? Or possibly let it be custom defined if the user knows it?

**Comment by psychonic** [comment]
Manifests are not necessarily tied to one specific build number. A build is a collection of manifests, one per depot in the build. Other builds can also contain some of those same manifests.

**Comment by wertercatt** [comment]
So, if I wanted to have it download a depot manifest to the correct depots/[depot#]/[buildid#], I'd need a way to define it myself, right?

**Comment by azuisleet** [comment]
As this mapping cannot be discovered, I don't believe there's anything to be done here.
