### ISSUE TITLE
Original files/folders attributes?

### ISSUE THREAD

**Issue by PaulNevada** [SteamRE/DepotDownloader#141]
Hi, Author!
Meaning date, time of the creation - is this data stored on steam servers?
Is it possible to have that info - optionally, for example? If we turn it on - the tool applies original attributes to the downloading stuff.
Thanks!

**Comment by azuisleet** [comment]
It doesn't seem likely given the data that's available in the manifest: https://github.com/SteamDatabase/Protobufs/blob/d6c75921889c65b3b885c19d94812220edfc1218/steam/content_manifest.proto

Does Steam do something in particular?

**Comment by xPaw** [comment]
> Does Steam do something in particular?

No.

**Comment by PaulNevada** [comment]
No, it doesn't. Pity a bit. Well, thanks.

**Comment by PaulNevada** [comment]
Got it - we can get that data from the manifest file's attributes - check it out, please...

**Comment by PaulNevada** [comment]
Reopen it, please...

**Comment by PaulNevada** [comment]
Can we migrate that timestamp from the manifest creation to all the files?
