### ISSUE TITLE
Project unable to compile using SteamKit nuget package

### ISSUE THREAD

**Issue by maritaria** [SteamRE/DepotDownloader#15]
SteamKit nuget package outdated, for example the method `CryptoHelper.SymmetricDecryptECB` is missing.

**Comment by psychonic** [comment]
There's not much that can be done about that until a newer SteamKit nuget package exists.

If you want a stable version, use the last tagged release. If you want the latest/greatest, you'll have to manually point it at an up-to-date clone of the SteamKit repo for now.

**Comment by maritaria** [comment]
Yea but owner of this repo also owns SteamKit... so that should be easy to settle.

**Comment by psychonic** [comment]
It's not a matter of difficulty. It's that it doesn't make sense to spin a new NuGet release for every single commit that introduces a breaking change. That defeats the purpose of having releases.

**Comment by maritaria** [comment]
Nuget supports versioning, not saying each commit needs a release but they could make a branch every time they build in features specifically for another project, and then release after pulling that branch to master when the side project is making a release as well.

**Comment by psychonic** [comment]
Closing since the SteamKit dependency was updated with this change a while ago.
