### ISSUE TITLE
It says there's a fatal error and I don't know how to fix it

### ISSUE THREAD

**Issue by PeptoPunk** [SteamRE/DepotDownloader#150]
It keeps saying "A fatal error occurred. The folder [C:\Users\Username\Desktop\depotdownloader-2.3.6\host\fxr] does not exist" Help me please

**Comment by azuisleet** [comment]
What version of the .NET Core Runtime is installed, and what OS are you using?

**Comment by azuisleet** [comment]
`dotnet --info` also provides helpful information.

**Comment by PeptoPunk** [comment]
> What version of the .NET Core Runtime is installed, and what OS are you using?
I'm using version 5.0 of dotnet and I'm on Windows 10

**Comment by azuisleet** [comment]
Does installing a .NET Core Runtime change the error message?

**Comment by PeptoPunk** [comment]
Nope

**Comment by azuisleet** [comment]
This sounds like a runtime issue that I am unable to diagnose. You could try building and running from the source code if the issue is with the packaged binaries.

If you have any more information, feel free to re-open this issue.
