### ISSUE TITLE
Multiple Depots Downloading

### ISSUE THREAD

**Issue by PaulNevada** [SteamRE/DepotDownloader#158]
Can we have some option to show the tool several depotids and manifestids to be downloaded at once?

**Comment by azuisleet** [comment]
Take a look at the 2.4.0 pre-release, as it allows you to specify a list of depot ids and a list of manifest ids:

https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.0

**Comment by PaulNevada** [comment]
Thanks a lot, Author!
