### ISSUE TITLE
2.3.6 - Connection to Steam failed...

### ISSUE THREAD

**Issue by PaulNevada** [SteamRE/DepotDownloader#159]
Any help here, please?
Worked just fine several hours ago, though...

**Comment by azuisleet** [comment]
Please try with the -debug option

**Comment by PaulNevada** [comment]
Response status code does not indicate success: 429 <too many requests> and many others, though...

**Comment by PaulNevada** [comment]
Connection cancelled before a server could be chosen...

**Comment by PaulNevada** [comment]
It's working now..
