### ISSUE TITLE
Older versions will just try to boot the latest version in the steamapps folder.

### ISSUE THREAD

**Issue by oryxcallotis** [SteamRE/DepotDownloader#160]
Not sure if this is really an issue with DepotDownloader, but I've seen a fair few with this. I have the older version of my game downloaded, everything is set up. As soon as I try to start this version, it just boots (or tries to) the up-to-date version I already have installed in my steamapps folder. To make sure this is actually the case, I can rename the game folder in my steamapps folder and try to start up the old depot version -  I get an error stating that Steam can't find the installed game (giving a link to where my up-to-date version was installed).

![asd](https://user-images.githubusercontent.com/34209909/102722803-82959e00-42fb-11eb-97e8-d95a5e771e46.jpg)

**Comment by VoiDeD** [comment]
Don't believe this is a DD issue - what you're very likely seeing here is the behavior of games with Steamworks SDK integration where they'll re-launch via Steam if they weren't originally launched by it.

You might be able to override this behavior by dropping a steam_appid.txt file with the contents of the game's appid next to the executable for the game, and then trying to launch the exe manually again.
