### ISSUE TITLE
Please log errors to stderr instead of stdout

### ISSUE THREAD

**Issue by bviktor** [SteamRE/DepotDownloader#161]
Hi,

I saw at least 3 different errors so far:

```
Encountered error downloading chunk ee624ffe0c2fe883d3bda78c525d6cf6d9b4bb0e: InternalServerError
```

```
Encountered unexpected error downloading chunk 2c4aba85374e8b34c59769b66a2312b96efde211: An error occurred while sending the request.
```

```
Connection timeout downloading chunk ee624ffe0c2fe883d3bda78c525d6cf6d9b4bb0e
```

But if I run `depotdownloader whatever > download.log`, none of these is shown, because they're all printed to stdout. It'd really help checking for any errors after a download.

---

**On a related note:** does DepotDownloader automatically retry downloading such failed parts, or do I have to repeat the download over and over until no such errors are printed in the output?

**Comment by scarrry** [comment]
> On a related note: does DepotDownloader automatically retry downloading such failed parts, or do I have to repeat the download over and over until no such errors are printed in the output?

I wonder this as well, I've attempted to install an older version of Moonlighter across it's 5 oldest versions and through close analysis, the batch file does say "100% Moonlighter, etc", upon loading the exe, it automatically closes after 4 seconds of a black screen. 

I have tried separating the files from steamdepot, re-entering file codes (steamappid, etc), and replacing the steam files and nothing seems to work across all 5 versions.

I suspect a valve update has changed the way the program is meant to grab manifestations and actively tries to block it...? Anyways, I would hope another way comes to fix this/downpatch

**Comment by scarrry** [comment]
> 
> 
> > On a related note: does DepotDownloader automatically retry downloading such failed parts, or do I have to repeat the download over and over until no such errors are printed in the output?
> 
> I wonder this as well, I've attempted to install an older version of Moonlighter across it's 5 oldest versions and through close analysis, the batch file does say "100% Moonlighter, etc", upon loading the exe, it automatically closes after 4 seconds of a black screen.
> 
> I have tried separating the files from steamdepot, re-entering file codes (steamappid, etc), and replacing the steam files and nothing seems to work across all 5 versions.
> 
> I suspect a valve update has changed the way the program is meant to grab manifestations and actively tries to block it...? Anyways, I would hope another way comes to fix this/downpatch

Much of this stems from the downloader saying "0.01% - 10% Downloaded" and after that comes up with errors and continuity errors;
"30% downloaded
Failed to download chunk: x
86% downloaded"

**Comment by azuisleet** [comment]
Transient errors like timeouts or server errors are always retried. Only once all chunks are downloaded will the program report 100% downloaded.

It does not log to stderr, but if a fatal error occurs a non-zero exit code is used.

**Comment by bviktor** [comment]
Alright, I'll rely on the exit code then, thanks!
