### ISSUE TITLE
When i try to downgrade gmod this comes up when i opend

### ISSUE THREAD

**Issue by FortcraftAdmin** [SteamRE/DepotDownloader#162]
![image](https://user-images.githubusercontent.com/77021365/103686195-bb39a680-4f8e-11eb-81a2-71303dc781be.png)

**Comment by VoiDeD** [comment]
This likely isn't a depotdownloader specific issue, but more with the operation of source engine games. You may wish to search around for how to launch source games outside of Steam (ex: https://developer.valvesoftware.com/wiki/Missing_GameInfo.txt).
