### ISSUE TITLE
I have steam authenticator enabled

### ISSUE THREAD

**Issue by BiOSF2** [SteamRE/DepotDownloader#163]
I have the steam auth enabled and whenever I try to do the login it comes back with password invalid. Is there any way I can input my authenticator's code?

**Comment by mcdalcin** [comment]
It handles authentication already. I would double-check that the username and password are correct. It will ask for the authenticator code afterward.

**Comment by BiOSF2** [comment]
> It handles authentication already. I would double-check that the username and password are correct. It will ask for the authenticator code afterward.

Thanks, I forgot I used an older username when I made my account and my password changed a while ago. It worked fine now! Thank you for your help.
