### ISSUE TITLE
[FR] Consider packaging compiled public release with standlone executable

### ISSUE THREAD

**Issue by Kein** [SteamRE/DepotDownloader#164]
There is no reason to feed M$ that sweet-sweet private user data they call """""""telemetry""""""" every time an uneducated user uses DD for his needs:

https://github.com/dotnet/sdk/issues/6145
https://dgl.cx/2020/08/ms-report.txt
https://dgl.cx/2020/08/dotnet-sdk-gdpr

It is not particularly hard to implement and it wont undermine DD as a library in any way as well.

**Comment by VoiDeD** [comment]
We're already packaging up compiled binaries - is there something more you're looking for here?

**Comment by Kein** [comment]
Your *public* release is a library class binary that you suggest (via documentation) to run via default `dotnet` processor. This triggers the collection an upload of user data on every call. Packaging the release with its own executable cli binary can partially mitigate that (since it cannot be fully disabled by M$ design).
99% of the users will be getting the release binaries from Releases and running these as prescribed in readme, without 2nd thought. A simple repackage can mitigate the problem and do not empower MS any more with the personal data of every living soul.

**Comment by VoiDeD** [comment]
Per the docs, it doesn't appear that telemetry is enabled for the "run" flow:

https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry#scope

> Telemetry isn't collected when using dotnet to start an application in the following format:
>
>    dotnet [path-to-app].dll

**Comment by Kein** [comment]
MS docs mean jack shit, just check the issues, across few years people report the connections to telelemetry servers despite having all possible opt-outs enabled.  
You don't just naively think MS will tell you in the official documentation how to disable their bread and butter? This wouldnt be an issue to being with.

**Comment by VoiDeD** [comment]
While I value your concern about our users, if you have reason to believe the .NET tooling isn't following the documentation or the documentation isn't accurate, you should open an issue upstream in their repos.

**Comment by Kein** [comment]
Microsoft is not gonna address that and we both know it. Nobody is gonna care about the private user data but the community itself.  
If you are too disinterested to address that (which is less than 5 minutes of work) I can PR the project structure under which it compiles CLI executable wrapper for the release instead of relying on `dotnet` default processor.
