### ISSUE TITLE
Timeout connecting to Steam3.

### ISSUE THREAD

**Issue by HarryWang828** [SteamRE/DepotDownloader#166]
my username and password are 100% right.
and i have turned off my firewall
here is the screenshot with debug
![批注 2021-01-13 131130](https://user-images.githubusercontent.com/53087311/104409280-e0d33b00-55a0-11eb-82b2-2ceb8e472aaa.jpg)

**Comment by azuisleet** [comment]
Are you running any firewall software?

**Comment by HarryWang828** [comment]
> Are you running any firewall software?

just Windows defener，and i have turned it off

**Comment by HarryWang828** [comment]
run cmd, netsh winsock reset, restart
