### ISSUE TITLE
Invalidpassword keeps showing up

### ISSUE THREAD

**Issue by Creeperspielt** [SteamRE/DepotDownloader#171]
gday yall, im trying to download something but the same error keeps showing up: Unable to login to Steam3: InvalidPassword
I even resetted my steam password, but still: InvalidPassword.

**Comment by azuisleet** [comment]
Most likely you have entered a wrong username or password. You should confirm your username and password through the Steam application first.

If your password contains special characters and you're passing them on the command line, they may need to be escaped.

**Comment by azuisleet** [comment]
If you still have issues with entering your password feel free to re-open the issue. Otherwise the suggestion is to not provide it on the command line and instead wait for the interactive prompt.

**Comment by PhantomSlash64** [comment]
> Most likely you have entered a wrong username or password. You should confirm your username and password through the Steam application first.
> 
> If your password contains special characters and you're passing them on the command line, they may need to be escaped.

How do I do that? I am having the same issue as him and I know for the fact that it's correct
