### ISSUE TITLE
Encountered error downloading manifest for depot (depot number) (manifest number) : Task cancelled

### ISSUE THREAD

**Issue by dianobanano** [SteamRE/DepotDownloader#172]
it all goes well until this happens :
Encountered error downloading manifest for depot (depot number) (manifest number) : Task cancelled
![image](https://user-images.githubusercontent.com/78323576/106398837-67976d00-6415-11eb-8c33-37045c1e8af2.png)
any help please??

**Comment by azuisleet** [comment]
Can you confirm if this is happening on the 2.4.0 pre-release? 
https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.0
