### ISSUE TITLE
batch not working

### ISSUE THREAD

**Issue by timon4ik142** [SteamRE/DepotDownloader#173]
when i double click or press open. just... nothing happens... the depot download doesn't open bat file even tho i did everything right ;-;
i see the bats' window boarders for a split millie second. and then they just disappear :(

**Comment by DoctorMcKay** [comment]
Do you have dotnet installed?

Also, you can't just double-click the batch file and expect anything to happen; you have to invoke it from the command line with arguments specifying what you want it to do.

**Comment by timon4ik142** [comment]
> Do you have dotnet installed?
> 
> Also, you can't just double-click the batch file and expect anything to happen; you have to invoke it from the command line with arguments specifying what you want it to do.

where do i download dotnet??

**Comment by timon4ik142** [comment]
> Do you have dotnet installed?
> 
> Also, you can't just double-click the batch file and expect anything to happen; you have to invoke it from the command line with arguments specifying what you want it to do.

ok i downloaded it but it does nothing again. it open but then i saw some red text for a brief moment and i closed again
then it started closing again like last time. but i see it open but i just closes anyway :|

**Comment by SlejmUr** [comment]
You need to write a batch yourself.
Create a txt, edit with any text editor, then save it to .bat. Then paste `dotnet DepotDownloader.dll -app <your app> -depot <your depot> -manifest <your manifest> -username <your username> -remember-password -dir "<yourpath/something>" -validate -max-servers 15 -max-downloads 10`
Then write your things into this batch, like your app is siege or gtaV, etc, every information you get it from https://steamdb.info/ 
For example i use this to download R6S First Steam released version:
`dotnet DepotDownloader.dll -app 359550 -depot 377237 -manifest 8358812283631269928 -username %username% -remember-password -dir "Downloads\Y1S0_Vanilla" -validate -max-servers 15 -max-downloads 10
`
If you add into a batch some other line , like `@echo off` in the start and `pause` in the end, plus if you want to other user can use your batch you need to `set /p username:"Type your steam login name here: "` just don't forget to edit to your username to %username%.

**Comment by timon4ik142** [comment]
> You need to write a batch yourself.
> Create a txt, edit with any text editor, then save it to .bat. Then paste `dotnet DepotDownloader.dll -app <your app> -depot <your depot> -manifest <your manifest> -username <your username> -remember-password -dir "<yourpath/something>" -validate -max-servers 15 -max-downloads 10`
> Then write your things into this batch, like your app is siege or gtaV, etc, every information you get it from https://steamdb.info/
> For example i use this to download R6S First Steam released version:
> `dotnet DepotDownloader.dll -app 359550 -depot 377237 -manifest 8358812283631269928 -username %username% -remember-password -dir "Downloads\Y1S0_Vanilla" -validate -max-servers 15 -max-downloads 10 `
> If you add into a batch some other line , like `@echo off` in the start and `pause` in the end, plus if you want to other user can use your batch you need to `set /p username:"Type your steam login name here: "` just don't forget to edit to your username to %username%.

OMG THX SO MUCH! YOU'RE A LIFE SAVER 😃
now i can play terraria 1.0.0 :D
