### ISSUE TITLE
Getting "Unable to login to steam3: invalidpassword" Despite having entered in the correct credentials

### ISSUE THREAD

**Issue by Spaa641** [SteamRE/DepotDownloader#177]
I get this error Logging 'MyUsername' into Steam3...Unable to login to Steam3: InvalidPassword
Disconnected from Steam
Unable to get steam3 credentials.
Error: InitializeSteam failed"
No matter what I do so what exactly am I supposed do to fix this

**Comment by azuisleet** [comment]
Most likely you have entered a wrong username or password. You should confirm your username and password through the Steam application first.

If your password contains special characters and you're passing them on the command line, they may need to be escaped.

**Comment by Spaa641** [comment]
> Most likely you have entered a wrong username or password. You should confirm your username and password through the Steam application first.
> 
> If your password contains special characters and you're passing them on the command line, they may need to be escaped.

Well I've validated my credentials multiple time doing what you just said. and I'm not sure what you mean by special characters but all the characters in my password are typeable on a standard US keyboard like % & $ @ ! * for example

**Comment by antel** [comment]
> Well I've validated my credentials multiple time doing what you just said. and I'm not sure what you mean by special characters but all the characters in my password are typeable on a standard US keyboard like % & $ @ ! * for example

Check this link [escaping-special-characters-in-cmd](https://stackoverflow.com/questions/10296162/escaping-special-characters-in-cmd)
You need to escape special characters with ^ and double % for '%', also enclose pass inside ""

**Comment by Spaa641** [comment]
> > Well I've validated my credentials multiple time doing what you just said. and I'm not sure what you mean by special characters but all the characters in my password are typeable on a standard US keyboard like % & $ @ ! * for example
> 
> Check this link [escaping-special-characters-in-cmd](https://stackoverflow.com/questions/10296162/escaping-special-characters-in-cmd)
> You need to escape special characters with ^ and double % for '%', also enclose pass inside ""

Thanks for this it's working now
