### ISSUE TITLE
Trying to get Terraria 1.3 results in this

### ISSUE THREAD

**Issue by biomseed** [SteamRE/DepotDownloader#178]
Unable to download manifest 8115792227484220109 for depot 105601
App 105600 was not completely downloaded.
The operation was canceled.
it worked before, but failed to download some chunks whatever that means but now it just completely stops
(yes, i wasnt able to get it working the first time)

**Comment by biomseed** [comment]
2.4.0 prerelease

**Comment by biomseed** [comment]
this also doesnt work with old versions of the haha funny imposter sus amogus game

**Comment by azuisleet** [comment]
You may have a firewall enabled that is preventing the program from working correctly. Try running with -debug to get the exact error messages.

**Comment by biomseed** [comment]
Okay now its the same thing from before that problem happened but uhh i dont know if thi is new for the debug thing but here you go
[CDNClient] Failed to complete web request to http://cache4-atl1.steamcontent.com/depot/105601/chunk/fd02e4673e892ccc48b1b7d4a7612ebf908b22cf: The operation was canceled

Failed to find any server with chunk fd02e4673e892ccc48b1b7d4a7612ebf908b22cf for depot 105601. Aborting.
App 105600 was not completely downloaded.
The operation was canceled.

**Comment by azuisleet** [comment]
The chunk at that URL appears to be available, so it seems more likely that another program is interfering with DepotDownloader.

**Comment by azuisleet** [comment]
2.4.1 contains a revised timeout mechanism for downloads. Take a look and let me know if you still have download issues. https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.1
