### ISSUE TITLE
How to integrate to a visual studio project?

### ISSUE THREAD

**Issue by JaySlex** [SteamRE/DepotDownloader#182]
I have my console app with steamkit2, but i cant integrate it without having errors?
How did you guys import it?

**Comment by yaakov-h** [comment]
This is a tool, not a library. What are you trying to do?

**Comment by JaySlex** [comment]
i have an application console with steamkit2 and i want to use depotdownloader (steam3session)

**Comment by JaySlex** [comment]
and i dont know how to integreate it, or use the api

**Comment by JaySlex** [comment]
I got it you can close now
