### ISSUE TITLE
DepotDownloader Doesn't create a depot folder

### ISSUE THREAD

**Issue by UIElliott** [SteamRE/DepotDownloader#187]
I want to rollback to an earlier version of Among Us, and everything seems to go well, the CMD opens fine with no issue and runs correctly, It asked for my steam code and I gave it and it looked like it was downloading properly. However after the CMD closed a Depots folder was not created like it was for my friends

**Comment by azuisleet** [comment]
Depending on how you ran the program, the files would be downloaded to the folder specified by "-dir" or the current working directory.
