### ISSUE TITLE
Connection timeout downloading chunk

### ISSUE THREAD

**Issue by qrosalt** [SteamRE/DepotDownloader#189]
trying to download an older verson of The Isle. it goes to 1.48% downloaded then just spits a bunch of Connection timeout downloading chunk errors forever... ):

command: dotnet DepotDownloader.dll -app 376210 -depot 376212 -manifest 1042447795905728485 -username user -password pass

**Comment by malxsant** [comment]
I encounter the same issue, trying to downpatch a RDR2 version

**Comment by ian1308** [comment]
yea im trying to do it for the isle too and the same thing happens.

**Comment by azuisleet** [comment]
2.4.1 contains a revised timeout mechanism for downloads. Take a look and let me know if you still have download issues. https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.1
