### ISSUE TITLE
can't download anything as depotdownloader won't connect to steam

### ISSUE THREAD

**Issue by jizsockery** [SteamRE/DepotDownloader#193]
used it a few months back and it worked fine but when i tried to download something today it didn't work.
all i get is the following, after i put in my password;

connecting to steam3....connecting to steam failed. trying again
timeout connecting to steam3.
unable to get steam3 credentials.
error: initalizesteam failed
enter account password for "myusername"

try again and it just same the same thing, again and again.

are the servers acting up atm? steam client working fine.

**Comment by azuisleet** [comment]
You may have a firewall preventing the program from connecting. If you have any more information, feel free to re-open the issue.
