### ISSUE TITLE
"Connection timeout downloading depot manifest"

### ISSUE THREAD

**Issue by krajpaj** [SteamRE/DepotDownloader#198]
I've been trying to downpatch Hollow Knight and am completely new to downpatching. I tried looking around, but seems no one else had this issue. I am using the newest version of depot downloader (2.4.0), I also tried using 2.3.6, but I have gotten a completely different issue which I believe is due to the version being outdated.
![Depot](https://user-images.githubusercontent.com/83126035/115962587-74ab9000-a51c-11eb-8ffd-0886824276dd.png)

**Comment by azuisleet** [comment]
2.4.1 contains a revised timeout mechanism for downloads. Take a look and let me know if you still have download issues. https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.1
