### ISSUE TITLE
Problem of privilege

### ISSUE THREAD

**Issue by RagaSonic** [SteamRE/DepotDownloader#20]
DepotDownloader -app 584400 -depot 584401
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 14
Insufficient privileges to get access token for app 584400
Got AppInfo for 584400
App 584400 (Sonic Mania) is not available from this account.

I tried my account too but not work.

**Comment by psychonic** [comment]
The game is not in the anonymous sub. You need to own it (from a release override package, since it's not released), and then use the -username parameter to specify your Steam account name.

**Comment by RagaSonic** [comment]
Oki.

**Comment by RagaSonic** [comment]
I buy the game but always not work.

**Comment by psychonic** [comment]
The store package is not a release override package, and the game is still not released yet.
