### ISSUE TITLE
Please HELP

### ISSUE THREAD

**Issue by RevoNation** [SteamRE/DepotDownloader#203]
After starting Batch-File with Commands Steam wants that i'm say that E-mail Adress i have to send the Double Verifikation.. Ok i give it but than goes the Batch Off and nothing will Download.. What i make wrong?

**Comment by azuisleet** [comment]
You should probably run the tool from the command line so you can review any error messages that may be appearing. If you completed the two-factor challenge, there may be an error such as the app not being available.
