### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by KevinRommens** [SteamRE/DepotDownloader#204]
There is no explanation of what to do to use this. I don't know whether or not to use this in console, chrome, or steam console.

Any help would be appreciated.

**Comment by SlejmUr** [comment]
create batch file (.bat) (rename or save as a txt to bat)
Type it to `dotnet DepotDowloader.dll` + prefixes (or open it the .bat with notepad)
Save and run (as admin)

My .bat looks like this:
`dotnet DepotDownloader.dll -app 359550 -depot 377237 -manifest 6708129824495912434 -username %username% -remember-password -dir "G:\Downloads\Y2S3_BloodOrchid" -validate -max-servers 15 -max-downloads 10`
Put %username% to your steam username (not nickname)

**Comment by yaakov-h** [comment]
I don’t know what gave you the idea that you could perhaps run a dll in Chrome (??) but this is a command-line application. Parameters and examples are provided in the readme.
