### ISSUE TITLE
Is there a way to download all manifests from a depot?

### ISSUE THREAD

**Issue by m1s3ry** [SteamRE/DepotDownloader#205]
What the title says. I need to download all manifests from a depot and I can't find info on wether it's possible or not to download all manifests with one command.

**Comment by SlejmUr** [comment]
If you mean manifest data (files) not the txt one for file , hash, etc
Yes you can, use `dotnet DepotDownloader.dll -app <APPID> -username <UserName> -remember-password`
It will ask your password , type it. It invisible for privacy reason. And if you want to download for specific path use `-dir "D:\Path\Example\DD\Downloaded App"`
Dont forget to use UserName with Log-in not the Displayed one
(The red one NOT the green)
![image](https://user-images.githubusercontent.com/52343819/118093080-3859aa00-b3cd-11eb-906c-d40173fafd93.png)

**Comment by azuisleet** [comment]
You can only download one manifest per depot when running the program. This is to support downloading an app and its depots to a single target directory.
