### ISSUE TITLE
Cannot download preload of Mass Effect Legendary

### ISSUE THREAD

**Issue by ckorn** [SteamRE/DepotDownloader#206]
Hello,

the preload of Mass Effect Legendary has just started.
On my PC Steam offers me the option to preload the game.

Since I have a slow connection and do not want to keep my PC running all the time, I wanted to use
DepotDownloader on my Raspberry Pi.

I successfully downloaded other games before (but never tried with preloads).

I start DepotDownloader with params `-os windows -osarch 64 -language german -app 1328670`

The output is:

```
Got 231 licenses for account!
Got session token!
Got AppInfo for 1328670
Using app branch: 'Public'.
Got AppInfo for 228980
Got depot key for 228988 result: Blocked
Disconnected from Steam
No valid depot key for 228988, unable to download.
Depot 228990 (DirectX Jun 2010 Redist) is not available from this account.
Depot 1328671 (Mass Effect Legendary Edition - Content) is not available from this account.
Depot 1328673 (Mass Effect Legendary Edition - de_DE) is not available from this account.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Failed to retrieve content server list: The operation was canceled.

```

**Comment by ckorn** [comment]
On Steam I can preload the game:
![image](https://user-images.githubusercontent.com/1178591/118012972-eb84bd80-b351-11eb-8c30-118e0a8c60ae.png)

**Comment by psychonic** [comment]
DepotDownloader does not support downloading without decryption, and you don't have access to the depot keys for decryption until the app is fully released.
