### ISSUE TITLE
I can't type my password

### ISSUE THREAD

**Issue by MagicJungle7054** [SteamRE/DepotDownloader#207]
I'm unable to type my password I also had to make the bat again :(

**Comment by yaakov-h** [comment]
Can you provide any actionable details whatsoever?

**Comment by FatalBulletHit** [comment]
I assume this is about having no feedback when typing in the password prompt.

Got confused by it at first, too, as you type and nothing visually happens.
I suggest showing asterisks (`*`) while typing.
