### ISSUE TITLE
-remember-password switch required for subsequent calls

### ISSUE THREAD

**Issue by FatalBulletHit** [SteamRE/DepotDownloader#209]
The `-remember-password` switch is required for subsequent calls, as omitting it prompts for a password even if a valid login key exists.

Shouldn't DepotDownloader first check for a valid login key before prompting for a password?

**Comment by azuisleet** [comment]
If the switch wasn't enabled, and we tried to resume an existing session, it wouldn't work in subsequent runs.

**Comment by FatalBulletHit** [comment]
Ah, ok, I thought of it as a "log me in and remember me" switch, but that'd probably make account switching more complicated when using the UI rather than startup parameters. 🤔
