### ISSUE TITLE
HTTP Status Code 404 for existing Manifest IDs

### ISSUE THREAD

**Issue by RyanTT** [SteamRE/DepotDownloader#21]
I'm currently using this tool for a personal project of mine where I index all mods of a games workshop and allow people to scan for reuploads by hashes.

My worker fetches an up-to-date list of all workshop objects, then attempts to download the manifest data and save that information to a database.

However I've recently stumbled upon an error message that I can't really follow: When attempting to download some manifests via appid, depotid and manifestid (in which case appid == depotid), it fails to retrieve the information correctly (or, at all) often printing out "Internal server error" and mostly followed up by "NotFound". However all objects I've checked so far do exist and their manifestid is correct when attempting to download through depotdownloader.

Might it be that some workshop objects aren't accessible via the depot where the depotid is equal to the appid?

**Comment by azuisleet** [comment]
If this can be reproduced in 2.3.0, please re-open this.
