### ISSUE TITLE
Unable to get steam3 credentials. 

### ISSUE THREAD

**Issue by Avoney** [SteamRE/DepotDownloader#211]
![Screenshot 2021-06-02 021542](https://user-images.githubusercontent.com/55459047/120409244-7270f880-c348-11eb-8fb3-4ef2af66bc38.png)
I can't seem to get the program working, I tried following this issue page here: https://github.com/SteamRE/DepotDownloader/issues/137 but the fix didn't seem clear, could someone please explain how to fix this since I really want to try an older version of Rocket League.

Thank you

**Comment by yaakov-h** [comment]
The response from the server was that your credentials (username/password) are invalid. If they contain special characters you may need to escape them as per whatever shell you are using (in this case, CMD).

**Comment by FatalBulletHit** [comment]
If you are using CMD, you can use this tool to escape your password: http://output.jsbin.com/anitaz/11

Some more information can be found here: https://ss64.com/nt/syntax-esc.html#escape

**Comment by FatalBulletHit** [comment]
see #186
