### ISSUE TITLE
An error occurred while updating [game] (downloads disabled)

### ISSUE THREAD

**Issue by Avoney** [SteamRE/DepotDownloader#212]
![Screenshot 2021-06-02 040321](https://user-images.githubusercontent.com/55459047/120417882-7a846480-c357-11eb-9e4d-d8fdcfc96eca.png)

I successfully got the program working, but when I try to load up the older version of the game via Steam Offline mode, it doesn't seem to work.

Any ideas on how to fix this?

**Comment by VoiDeD** [comment]
Getting older versions of games to work is outside of the scope of DepotDownloader.
