### ISSUE TITLE
the .bat file wont show up

### ISSUE THREAD

**Issue by bentmailbox** [SteamRE/DepotDownloader#213]
i keep downloading and extracting this but the .bat file is never there, i also have .net installed so i dont know whats wrong

**Comment by yaakov-h** [comment]
It looks like the latest release doesn't include a .bat. However, since the instructions in the readme don't mention a .bat, why are you looking for one?

**Comment by bentmailbox** [comment]
> It looks like the latest release doesn't include a .bat. However, since the instructions in the readme don't mention a .bat, why are you looking for one?

im trying to downgrade terraria, and all the guides i find mention a .bat file

**Comment by FatalBulletHit** [comment]
See #215
