### ISSUE TITLE
Downloading doesn't work with the “filelist” argument specified in the 2.4.1 version

### ISSUE THREAD

**Issue by przemo20** [SteamRE/DepotDownloader#220]
As the title says.

The command I use here (dotnet DepotDownloader.dll -app 729040 -depot 729041 -manifest 8904156715871996648 -filelist filelist.txt -username USERNAME -password PASSWORD) works fine in the 2.3.6 version.

Screenshot of cmd window:
![DepotDownloader](https://user-images.githubusercontent.com/22180480/120939776-f09f1780-c719-11eb-8879-8cc701edd6ae.png)

--
Also, the newest version crashes (throws out an unhandled exception) on pre-allocating files, when there is not enough disk space.
![DepotDownloader2](https://user-images.githubusercontent.com/22180480/120940166-38bf3980-c71c-11eb-8afa-7950c543148e.png)
![DepotDownloader3](https://user-images.githubusercontent.com/22180480/120940171-3fe64780-c71c-11eb-8c4f-695c742df935.png)

**Comment by azuisleet** [comment]
2.4.1 changed the syntax for the filelist. You now have to prefix any regex paths with `regex:` #175. 

I have updated the release notes at https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.1
