### ISSUE TITLE
"Connection Timeout Downloading Depot Manifest" 2.4.1

### ISSUE THREAD

**Issue by AubbyLobby** [SteamRE/DepotDownloader#223]
Latest version of Depot Downloader has an error when trying to redownload depots and manifests.
Tried to delete and reinstall, but nothing worked. Even tried to change the manifest, but it still didn't work. Kept on getting connection timeout. Help would be appreciated, thank you.
![Screenshot 2021-06-09 183336](https://user-images.githubusercontent.com/85417781/121438169-8c669880-c951-11eb-8b5f-13cbc5842899.png)

**Comment by azuisleet** [comment]
How is your network setup? Do you have any VPN, proxy, firewalls, etc configured?

The cell is 84 and it doesn't look like there's anything unusual there.

Are there any entries related to your ISP at https://api.steampowered.com/IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=84 when you visit it from your network?

**Comment by AubbyLobby** [comment]
> How is your network setup? Do you have any VPN, proxy, firewalls, etc configured?
> 
> The cell is 84 and it doesn't look like there's anything unusual there.
> 
> Are there any entries related to your ISP at https://api.steampowered.com/IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=84 when you visit it from your network?

I do not have a VPN, proxy, firewalls. However I do have a Malewarebytes premium trial still going on, and that usually blocks some websites. I don't know how to turn that off however, it might have a firewall built in.

When going to that website, it gives me this kind of information.
![Screenshot 2021-06-09 185158](https://user-images.githubusercontent.com/85417781/121439349-c6d13500-c953-11eb-8c2a-cb5955ad8598.png)

**Comment by AubbyLobby** [comment]
I found out how to turn it off the web protection for Malewarebytes, but it is still giving me the same error when retrying.

**Comment by azuisleet** [comment]
You could try running with -debug, but most likely this is something where additional diagnostics are needed, such as watching the connections in Wireshark, or adding hooks in the app itself.

**Comment by AubbyLobby** [comment]
> You could try running with -debug, but most likely this is something where additional diagnostics are needed, such as watching the connections in Wireshark, or adding hooks in the app itself.

I'm updating my steam game back to the latest version before I do -debug. I'll tell you the results afterwards.

**Comment by azuisleet** [comment]
2.4.2 enables additional diagnostics for HTTP when -debug is specified. Give it a shot and provide a log.

https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.2

**Comment by AubbyLobby** [comment]
> 2.4.2 enables additional diagnostics for HTTP when -debug is specified. Give it a shot and provide a log.
> 
> https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.2

I've downloaded 2.4.2, however it still states connection timeout.

I've put in -debug in the bat file. Where is the Depot Downloader log located?

**Comment by azuisleet** [comment]
The log is written to the console.

**Comment by AubbyLobby** [comment]
I think this is it then, if not then let me know.
![Screenshot 2021-06-09 202046](https://user-images.githubusercontent.com/85417781/121445819-39481200-c960-11eb-9f99-6de2b8e2764f.png)

**Comment by azuisleet** [comment]
Every connection attempt fails this same way?

**Comment by azuisleet** [comment]
Do you have a functional IPv6 stack? https://test-ipv6.com/

**Comment by AubbyLobby** [comment]
> Every connection attempt fails this same way?

It seems like it. I waited a bit and let to do it's thing about 4 or 5 times
![Screenshot 2021-06-09 203129](https://user-images.githubusercontent.com/85417781/121446513-ac05bd00-c961-11eb-9c86-7f079ebe804b.png)

**Comment by AubbyLobby** [comment]
> Do you have a functional IPv6 stack? https://test-ipv6.com/

Maybe? I don't know what that is to be perfectly honest with you.
![Screenshot 2021-06-09 203252](https://user-images.githubusercontent.com/85417781/121446605-e0797900-c961-11eb-82d2-3f367c64d63a.png)

**Comment by AubbyLobby** [comment]
Alright funny story.

I reset my computer and now everything is working again.
I don't know if I should close this or you will eventually, else you want to help me in case a situation like that were to reoccur again. I do appreciate your help though.
![Screenshot 2021-06-09 205110](https://user-images.githubusercontent.com/85417781/121447799-6e566380-c964-11eb-9322-2ad0e06f3e0e.png)

**Comment by azuisleet** [comment]
I have released 2.4.3 disabling IPv6 for HTTP sockets. We have no way of knowing if the IPv6 stack is functional.

https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.3
