### ISSUE TITLE
Validation resets modify date on app files

### ISSUE THREAD

**Issue by NicknineTheEagle** [SteamRE/DepotDownloader#224]
Running DepotDownloader with -validate resets modify date on all app files, even the ones that weren't actually modified. This does not match Steam behavior and can cause organizational issues.
I've looked at the code and I'm not sure how to fix this with the current setup.

**Comment by azuisleet** [comment]
When Steam does fix a file, does the modified date change to the current date?

**Comment by NicknineTheEagle** [comment]
> 
> 
> When Steam does fix a file, does the modified date change to the current date?

Yes,

**Comment by azuisleet** [comment]
This should be addressed by #225. Pending a numbered release.
