### ISSUE TITLE
Stuck on "Accepted new login key for account (username)"

### ISSUE THREAD

**Issue by Coolperson2323** [SteamRE/DepotDownloader#226]
When trying to download manifest, i get "Accepted new login key for account (username)" and its just stuck. I remember it working fine a couple days ago, and now its just not working all of the sudden. please help

**Comment by azuisleet** [comment]
Please run with -debug and provide the log output.

**Comment by Coolperson2323** [comment]
> Please run with -debug and provide the log output.

theres alot of stuff, but ill show everythimg after accepted new login key

03:43:17.9696174  System.Net.Http.ResponseHeadersStart()
03:43:17.9697330  System.Net.Http.ResponseHeadersStop()
03:43:17.9705198  System.Net.Http.ResponseContentStart()
03:43:17.9707867  System.Net.Http.ResponseContentStop()
03:43:17.9709957  System.Net.Http.RequestStop()
03:43:18.9807832  System.Net.Http.RequestStart(scheme: https, host: api.steampowered.com, port: 443, pathAndQuery: /IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=12&format=vdf, versionMajor: 1, versionMinor: 1, versionPolicy: 0)
03:43:18.9810259  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: api.steampowered.com)
03:43:18.9818251  System.Net.NameResolution.ResolutionStop()
03:43:18.9822342  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{1,187,23,37,70,128,0,0,0,0,0,0,0,0})
03:43:18.9957008  System.Net.Sockets.ConnectStop()
03:43:18.9958287  System.Net.Security.HandshakeStart(isServer: False, targetHost: api.steampowered.com)
03:43:19.0275727  System.Net.Security.HandshakeStop(protocol: 3072)
03:43:19.0276829  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1)
03:43:19.0283688  System.Net.Http.RequestHeadersStart()
03:43:19.0286971  System.Net.Http.RequestHeadersStop()
03:43:19.1473032  System.Net.Http.ResponseHeadersStart()
03:43:19.1474402  System.Net.Http.ResponseHeadersStop()
03:43:19.1484457  System.Net.Http.ResponseContentStart()
03:43:19.1489884  System.Net.Http.ResponseContentStop()
03:43:19.1493215  System.Net.Http.RequestStop()
03:43:20.1498191  System.Net.Http.RequestStart(scheme: https, host: api.steampowered.com, port: 443, pathAndQuery: /IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=12&format=vdf, versionMajor: 1, versionMinor: 1, versionPolicy: 0)
03:43:20.1500774  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: api.steampowered.com)
03:43:20.1507803  System.Net.NameResolution.ResolutionStop()
03:43:20.1511718  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{1,187,23,37,70,128,0,0,0,0,0,0,0,0})
03:43:20.1664815  System.Net.Sockets.ConnectStop()
03:43:20.1665492  System.Net.Security.HandshakeStart(isServer: False, targetHost: api.steampowered.com)
03:43:20.2033484  System.Net.Security.HandshakeStop(protocol: 3072)
03:43:20.2034594  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1)
03:43:20.2041641  System.Net.Http.RequestHeadersStart()
03:43:20.2044661  System.Net.Http.RequestHeadersStop()
03:43:20.3072582  System.Net.Http.ResponseHeadersStart()
03:43:20.3073556  System.Net.Http.ResponseHeadersStop()
03:43:20.3080913  System.Net.Http.ResponseContentStart()
03:43:20.3083758  System.Net.Http.ResponseContentStop()
03:43:20.3086162  System.Net.Http.RequestStop()

**Comment by Coolperson2323** [comment]
sorry forgot this, this is everything after all that stuff and it says it 4 times

System.Net.Http.ConnectionClosed(versionMajor: 1, versionMinor: 1)

**Comment by azuisleet** [comment]
It appears that there's a Steam issue that we aren't handling correctly. I don't have a fix currently, so it's currently "wait and see". More information is available at https://github.com/SteamRE/SteamKit/issues/1001

**Comment by azuisleet** [comment]
A new hotfix release is available for 2.4.3. It contains pending changes to the SteamKit2 library to handle PICS being unavailable and shuffles the CM list so we don't keep connecting to the same CM.

https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.3

**Comment by Coolperson2323** [comment]
> A new hotfix release is available for 2.4.3. It contains pending changes to the SteamKit2 library to handle PICS being unavailable and shuffles the CM list so we don't keep connecting to the same CM.
> 
> https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.3

Thank you so much! Can confirm this works now, thanks!
