### ISSUE TITLE
Depot is not available from this account

### ISSUE THREAD

**Issue by ImSammy6** [SteamRE/DepotDownloader#235]
When I try to download a game, it'll say the depot is not available on my account, despite me owning the game.
EDIT: It seems to be only one game, Bob's game. Perhaps because it was removed from the store?

**Comment by azuisleet** [comment]
It may be that you don't own a specific depot in the app.

**Comment by NicknineTheEagle** [comment]
Can happen with DLCs and foreign languages.

**Comment by azuisleet** [comment]
If you have any more information, feel free to re-open this issue.
