### ISSUE TITLE
Bug: Timeout fetching depot key for arma 3 mod

### ISSUE THREAD

**Issue by WolfSkin0** [SteamRE/DepotDownloader#239]
I've been wanting to try out DeportDownloader as a way of managing my arma dedicated server installs on linux.

Arma's server (appid 233780) itself downloads fine with it, though it does it weirdly, by splitting its core executables and its addons across appids 233781 and 233783 respectively (likely for interusability with the standard client). Both of those use 6830389 as the depot key as far as I can understand.

![image](https://user-images.githubusercontent.com/27926588/127496377-968c77a8-8b72-4927-816f-ee56e170ddb5.png)

However, when I try to download a workshop mod, I run into the following issue, where a depot key, and therefore a manifest, cannot be found, meaning that the install attempt just times out and errors:

![image](https://user-images.githubusercontent.com/27926588/127496774-44317c8b-7846-4909-acba-d6999bba0f9f.png)

I have tried the other two appids, as well as the depot key they use in conjunction with the main appid, but to no avail.
Unfortunately, that now leaves me a bit stumped, since I wouldn't know where to start debugging this locally

**Comment by xPaw** [comment]
Whatever number you are passing into -ugc, it is not correct. For workshop ids, you use -pubfile.

**Comment by WolfSkin0** [comment]
Ah ok, that works to fix that error :sweat_smile:. Thanks! Now it's complaining about not being able to find a manifest file, but that's a different problem I guess
