### ISSUE TITLE
not a valid value for UInt32

### ISSUE THREAD

**Issue by Kainkun** [SteamRE/DepotDownloader#241]
Prey 2017 has a manifest id 7011320259885328682 whic UInt32 cant handle. Is there still a way to get this depot?

**Comment by Kainkun** [comment]
actually, the examples have manifest ids that are bigger than this so I'm not sure whats going on

**Comment by Kainkun** [comment]
this is what im trying in the cmd prompt `dotnet DepotDownloader.dll -app 480490 -depot 480491 7011320259885328682`

**Comment by azuisleet** [comment]
You are specifying multiple depot ids. You need to specify the manifest
`dotnet DepotDownloader.dll -app 480490 -depot 480491 -manifest 7011320259885328682`

**Comment by Kainkun** [comment]
yeah i just realized. thanks!
