### ISSUE TITLE
Latest Release - No .bat File Included

### ISSUE THREAD

**Issue by Kirbyarm** [SteamRE/DepotDownloader#242]
Trying to follow tutorials on how to use this but they're all indicating the use of a .bat file or shortcut to a depotdownloader.bat file, but when I download the latest release ZIP the file isn't present.

Would it be too much trouble to ask someone to paste the contents of the .bat here so I can create it myself?

**Comment by NicknineTheEagle** [comment]
BAT file is not needed anymore since the project was migrated to .NET 5.0, just run DepotDownloader.exe.

**Comment by Kirbyarm** [comment]
I did try that, both as and as not Administrator and the a command prompt looking window opens and immediately closes with no trace of error. This is what led me to research how to properly use it, which led me to the .bat tutorial, which led me here.

Any idea why the exe doesn't open a window that stays open?

-Windows 10 Professional OS

**Comment by NicknineTheEagle** [comment]
You need to pass arguments to the program from command line to use it, read README.

**Comment by Kirbyarm** [comment]
Aha, that explains. I understand now. Not experienced with these command prompt shenanigans. Thank you for clearing it up.
