### ISSUE TITLE
Repository size is inflated by tags

### ISSUE THREAD

**Issue by Kodiologist** [SteamRE/DepotDownloader#249]
There are binary files at e.g. `Resources/NetHook2/NetHook2/libprotobuf.lib` that don't appear in the history of `master` but are dragged in by `git clone` because they exist in tagged commits. Of this repository's 41 tags, it looks like several are actually for different projects, and are presumably in this repository by mistake.

**Comment by yaakov-h** [comment]
Good spotting there.

I've deleted the old tags from before this repo was split out of SteamKit2, and the clone size seems to have dropped from 52MB to just 1.5MB.

**Comment by Kodiologist** [comment]
Nice.
