### ISSUE TITLE
"dotnet is not a recognized command" after installing .net 2.09

### ISSUE THREAD

**Issue by Carnaxus** [SteamRE/DepotDownloader#250]
Do I specifically need 2.0 or am I doing something else wrong?  Here's my batch file:

@echo off
dotnet %~dp0DepotDownloader.dll %* -app 361420 -depot 361422 -manifest 4718209134484916344 -dir Downloaded\6995932
pause

I tried both with and without the %~ etc. stuff.

**Comment by SlejmUr** [comment]
If you use after the 2.4.1 , you need to install Dotnet 5.0
Also try this:
`dotnet DepotDownloader.dll -app 361420 -depot 361422 -manifest 4718209134484916344 -dir "Downloaded\6995932"`

**Comment by Carnaxus** [comment]
Er.  I downloaded from a link on a Youtube video that led straight to 2.3.6.  Whoops.  Thanks!

**Comment by Carnaxus** [comment]
![image](https://user-images.githubusercontent.com/2092336/132452118-e172da54-e139-494d-b4bc-c098796985fa.png)

This is after downloading 2.4.4 and .net 5.0...

**Comment by SlejmUr** [comment]
Enter dotnet --version on normal cmd
Send screenshot.
Also you installed .NET 5.0 SDKs?
[Dotnet 5.0.400 x64 installer (win)](https://download.visualstudio.microsoft.com/download/pr/c1bfbb13-ad09-459c-99aa-8971582af86e/61553270dd9348d7ba29bacfbb4da7bd/dotnet-sdk-5.0.400-win-x64.exe) 
Then restart your pc and try again the first (dotnet --version) and then send a screenshot

**Comment by philou-felin** [comment]
> 
> 
> Enter dotnet --version on normal cmd
> Send screenshot.
> Also you installed .NET 5.0 SDKs?
> [Dotnet 5.0.400 x64 installer (win)](https://download.visualstudio.microsoft.com/download/pr/c1bfbb13-ad09-459c-99aa-8971582af86e/61553270dd9348d7ba29bacfbb4da7bd/dotnet-sdk-5.0.400-win-x64.exe)
> Then restart your pc and try again the first (dotnet --version) and then send a screenshot

Are you implying that we need to download and install the link you added?

**Comment by Carnaxus** [comment]
Actually I did not install the SDK, just the runtime.  Maybe that's my problem.  Will update.

**Comment by SlejmUr** [comment]
> 
> Hello! Are you implying that we need to download and install the link you added?

Yep , its safe, its from the official Microsoft site. And it actually said in the 2.4.1 update to now it is using dotnet 5.0

**Comment by philou-felin** [comment]
> > Hello! Are you implying that we need to download and install the link you added?
> 
> Yep , its safe, its from the official Microsoft site. And it actually said in the 2.4.1 update to now it is using dotnet 5.0

I'm sure it's safe. :) I'm planning to do a How-To guide for "No Man's Sky" player, so I wanted to make sure since DepotDownloader already works fine on my computer. 🙂

Do we indeed need the SDK?

**Comment by SlejmUr** [comment]
> I'm sure it's safe. :) I'm planning to do a How-To guide for "No Man's Sky" player, so I wanted to make sure since DepotDownloader already works fine on my computer. 🙂
> 
> Do we indeed need the SDK?
> 
> Also... I just realized I did not use "dotnet DepotDownloader.dll" today. I used the ".exe", unless I'm mistaken... 🤔

Probably it better if you install sdk instead of just the .net framework.

Btw some games don't work when you just download and play, (probably needed some other things).
But if you write to copy paste everything to they game files (or make a backup copy for a currently build and the old build then copy paste files).

**Comment by philou-felin** [comment]
No Man's Sky uses Steam DRM.

**Comment by SlejmUr** [comment]
> No Man's Sky uses Steam DRM.

Then probably not :D If you use games like siege or that has other drm , you need to do dirty stuff :(
