### ISSUE TITLE
For some reason I cant connect to steam anymore

### ISSUE THREAD

**Issue by Richcarlos** [SteamRE/DepotDownloader#251]
After installing the downpatcher i stopped being able to even launch steam i tried restarting my computer reinstalling steam everything even checked my firewall nothing fixxes it idk what this did to my steam but it destroyed my steam assist please

**Comment by azuisleet** [comment]
If you launched this tool without specifying a `-loginid`, your existing connection to Steam may have been interrupted. It should just be a matter of closing and opening the Steam Client again to resolve it.

This tool does not change any of your Steam Client settings.

**Comment by azuisleet** [comment]
If you have any more information, feel free to re-open this issue.
