### ISSUE TITLE
Add an FAQ to the Readme

### ISSUE THREAD

**Issue by azuisleet** [SteamRE/DepotDownloader#259]
Some common questions that come up:

- Why am I prompted to enter a 2fa code every time I run this tool? (-remember-password)
- Why does the Steam Client log out when I run this tool? (-loginid)
- Do I have to provide my password on the command line? (No, you can specify -username and you will be prompted for your password)
- Why doesn't my password work when I provide it on the command line? (Special characters must be escaped)
- When downloading an old manifest, I get an error like "Failed to find any server with chunk" (These files are no longer available)

**Comment by xPaw** [comment]
Does it still kick Steam client logins since it has a default LoginID now?

**Comment by azuisleet** [comment]
I don't think there is a default LoginID set in DepotDownloader or SteamKit, I believe they collide with Steam Client by default

**Comment by azuisleet** [comment]
I have added some entries in 703929dad06595f50550b88915fcf2b86fd88ced
