### ISSUE TITLE
Failed retrieving CDN auth token

### ISSUE THREAD

**Issue by sgkoishi** [SteamRE/DepotDownloader#263]
```
> DepotDownloader.exe -app 381210 -depot 381211 -username ***** -password *****
Connecting to Steam3... Done!
Logging '*****' into Steam3...Disconnected from Steam
This account is protected by Steam Guard.
Please enter your 2 factor auth code from your authenticator app: *****
Retrying Steam3 connection... Done!
Logging '*****' into Steam3... Done!
Using Steam3 suggested CellID: 94
Got 410 licenses for account!
Got session token!
Got AppInfo for 381210
Using app branch: 'Public'.
Got depot key for 381211 result: OK
Processing depot 381211 - Dead by Daylight Content
Downloading depot manifest...Got CDN auth token for steamcontent.com result: Fail (expires 1970-01-01 12:00:00 AM)
Disconnected from Steam
```
No other steam client running, tried with different `-cellid` but no difference.
The same result happens in Linux (the only difference is time format - becomes `Fail (expires 1/1/1970 12:00:00 AM)`).
Local system time for both Windows and Linux is correct.

Not sure if the account or the network is related; everything works correctly one week ago in Sept (before I got two RateLimitReached).

**Comment by azuisleet** [comment]
2.4.5 is now available. Please give it a try https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.5
