### ISSUE TITLE
Disconnected from steam 

### ISSUE THREAD

**Issue by AizerMortenort** [SteamRE/DepotDownloader#265]
![image](https://user-images.githubusercontent.com/10715203/136376496-17a9f28a-20a2-4d57-9b4b-b60fc85a1748.png)
Disconnected from steam. Keeps failing download

**Comment by azuisleet** [comment]
I'm not certain what you're expecting. If you've downloaded all the files, then there is no data left to retrieve from Steam.

**Comment by azuisleet** [comment]
If it says it is 100% complete, then all the files have been downloaded.
