### ISSUE TITLE
Multiple manifest issue.

### ISSUE THREAD

**Issue by legomeaker101** [SteamRE/DepotDownloader#271]
Hello, I have been trying to download multiple copies of a game (nuclear throne) but all the manifests go into the same folder. is it possible to make each go into a different directory without having to do a -dir for each individual manifest? or am I doing something wrong?

**Comment by azuisleet** [comment]
DepotDownloader can only track one installation at a time for a given app. If you want to download multiple manifests, you will have to download into different directories, using the -dir option.
