### ISSUE TITLE
1557210 (Prague (1557210) Depot) is not available from this account.

### ISSUE THREAD

**Issue by gregstein** [SteamRE/DepotDownloader#279]
Hello,

Three depots from here https://steamdb.info/patchnotes/7463742/ (Palermo & Prague) are failing to download and return:

```
Depot 1022220 (Phoenix (1022220 ) Depot) is not available from this account.
Depot 1389240 (Palermo(1389240) Depot) is not available from this account.
Depot 1557210 (Prague (1557210) Depot) is not available from this account.
```
The rest of the depots download flawlessly though.

**What are your thoughts about this?** Are Palermo & Prague private depots to the devs?

Thank you,

**Comment by azuisleet** [comment]
You need an account with an appropriate license to download specific depots.

**Comment by gregstein** [comment]
Ohhh that makes sense! Since I do not own one dlc. Thanks a lot that clears it up <3
