### ISSUE TITLE
Failed to retrieve content server list

### ISSUE THREAD

**Issue by DragonT4** [SteamRE/DepotDownloader#28]
well here it is. 

this is my txt setup and bat setup
remastered.txt
HomeworldRM\\Data\\Homeworld2.big
HomeworldRM\\Data\\HW2Ships.big
HomeworldRM\\Data\\HW1Ships.big
HomeworldRM\\Data\\HW2Campaign.big

and my oldHW.bat
@echo off
cls
set /p user="Steam username: "
set /p pass="Steam password: "
cls
DepotDownloader.exe -app 244160 -all-platforms -depot 244161 -manifest 2705039423460849921 -filelist "remastered.txt" -username "%user%" -password "%pass%" -dir remastered
pause

and the result...

Got session token!
Accepted new login key for account [MY STEAM ACCOUNT NAME]
Got AppInfo for 244160
Using app branch: 'Public'.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Got appticket for 244161!
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Got depot key for 244161 result: OK
Downloading depot 244161 - Hickory HD
Downloading depot manifest...Failed to retrieve content server list: An internal
 error occurred while attempting to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.
Failed to retrieve content server list: An internal error occurred while attempt
ing to parse the response from the CS server.

**Comment by azuisleet** [comment]
If this can be reproduced in 2.3.0, please re-open this.
