### ISSUE TITLE
Subnautica Depot Download Issue

### ISSUE THREAD

**Issue by nonelikegrant** [SteamRE/DepotDownloader#280]
So I’ve been using depot downloader and it’s been working really well helping me play the old versions of Subnautica. But I’ve tried to download the PRAWN update and The Dangerous Creatures update and they haven’t worked due to an error that states “error loading chunk- (and then a bunch of random letters and numbers)” I’m wondering if this is a me issue or a depotdownloader issue

**Comment by azuisleet** [comment]
Please include the error message. It may be that the manifest you are trying to download no longer exists.

**Comment by nonelikegrant** [comment]
Here it is



Failed to find any server with chunk 73ab0070c34dbcc974ce5c3e45b5aa216c6c25e6 for depot 264712. Aborting.
Failed to find any server with chunk 7a1d1449706e0ee980daf6c868b015fc9bdd64d7 for depot 264712. Aborting.
Failed to find any server with chunk 79e29bfcd15bfee3b324f8f556eff11badce6245 for depot 264712. Aborting.
Failed to find any server with chunk 7a854d683f97f825ffa2ab4659bb9eda92e12884 for depot 264712. Aborting.
Failed to find any server with chunk 7a973808c427f275e0402271783e833dfebbfaed for depot 264712. Aborting.
Failed to find any server with chunk 7aa9db23f5b6c5cac3eba7bb3f3d5a62a34e5a7a for depot 264712. Aborting.
Failed to find any server with chunk 7abbb2099c30a808989552567813736105af045f for depot 264712. Aborting.
Failed to find any server with chunk 7ad2abafdfadcd980b471d59b620c71d812052b5 for depot 264712. Aborting.
Failed to find any server with chunk 7a7bdc1391f680a23cb72158365f7ed8710b5d09 for depot 264712. Aborting.
Failed to find any server with chunk 79bf91154cfbf3c0a85eada84d81896e2942d39a for depot 264712. Aborting.
App 264710 was not completely downloaded.
Failed to find any server with chunk 7b61b6bc86f5f51e803afef109f69f2dde9e7a48 for depot 264712. Aborting.
Failed to find any server with chunk 7bc14f10657b3629f49f5a967c04b8af3c15bfab for depot 264712. Aborting.
Failed to find any server with chunk 7aea3564e7bb58c51957eb78261d35ec3d58cafb for depot 264712. Aborting.
Failed to find any server with chunk 7bdf625786a953a382b36255c01afe17c2653d09 for depot 264712. Aborting.
Failed to find any server with chunk 7be549260a9e642df886a972291950f31ed88ce2 for depot 264712. Aborting.
Failed to find any server with chunk 7c3e9f89a0c5118ee1627106a654a15fe004c75b for depot 264712. Aborting.
The operation was canceled.
Failed to find any server with chunk 7c8a1acfe238c99b85999ee18db9b616327a355b for depot 264712. Aborting.
Failed to find any server with chunk 7c992f1034d981cbea65b39868b7fbeba2dca6e3 for depot 264712. Aborting.
Failed to find any server with chunk 7ca75c5e3de387b9d49066f2b76f8eb59d6620da for depot 264712. Aborting.
Failed to find any server with chunk 861c386a17ed8338cb9fda56a16bd5cb59f62eb5 for depot 264712. Aborting.
Failed to find any server with chunk 86230ed66068f177cf10678121477ef14e0bb85b for depot 264712. Aborting.
Failed to find any server with chunk 865722c7f3692cc5989a52707f8ba57538656633 for depot 264712. Aborting.
Failed to find any server with chunk 863ebd3a6f9f8c10b7dea5686e26be5cde4aa567 for depot 264712. Aborting.
Failed to find any server with chunk 866b94f6c0e09ca2ec36b56c7c97e537a20c3f16 for depot 264712. Aborting.
Failed to find any server with chunk 868605cec533d20183ad991f6b9eb10eca95bbf6 for depot 264712. Aborting.
Failed to find any server with chunk 86d69c904e3031ca86e6765544f98b71178a5414 for depot 264712. Aborting.
Failed to find any server with chunk 86a78d7e6f31f26e610e614f09b9c92f1cabe123 for depot 264712. Aborting.
Failed to find any server with chunk 86a85dec839a63c78f72a35672b324d18099f013 for depot 264712. Aborting.
Failed to find any server with chunk 8718fc25c2c1bd6b60176babac3ce7f2226eaa13 for depot 264712. Aborting.
Failed to find any server with chunk 872cc935fc676458465bef7023d0c72642ff477b for depot 264712. Aborting.
Failed to find any server with chunk 6aee36814ebae907f00205164b0eca599002778d for depot 264712. Aborting.
Failed to find any server with chunk 8a6513dfcf02683880eb8b9d795362b3b59ae4b8 for depot 264712. Aborting.
Failed to find any server with chunk 6dcb968d67bad2a2dfdfc8bfc6c5cf4d00d43b3c for depot 264712. Aborting.
Failed to find any server with chunk 7a1c8885c147b5cb67459512b603f181254b8c77 for depot 264712. Aborting.
Failed to find any server with chunk 702e8ac2b0af089f893294f03fcf803aa657ebcf for depot 264712. Aborting.
Failed to find any server with chunk 7a034a8afdd612f23d80aed66434b39739a6b648 for depot 264712. Aborting.
Failed to find any server with chunk 7a79498f0114c91918e77ac7cc32a6c2485dabe6 for depot 264712. Aborting.
Failed to find any server with chunk 7baeaa468ff937b16a5c15af3998a2d9905c923b for depot 264712. Aborting.
Failed to find any server with chunk 7bc87dfead59bf417d6466bb51527bd5b04fbaad for depot 264712. Aborting.
Failed to find any server with chunk 7c3ee5a03ff2d8c9be12fbcb27dca70c71c00e98 for depot 264712. Aborting.
Failed to find any server with chunk 7ca8c1ea1288ceb25eea5b8154872a97e2cf9288 for depot 264712. Aborting.
Failed to find any server with chunk 867b468a564f26ab6dfd663c711b8337ca0d995b for depot 264712. Aborting.
Failed to find any server with chunk 8665585161d2ad1045e97a54a7eee8e59a43650f for depot 264712. Aborting.
Failed to find any server with chunk 86a5bf16f7b65b2745d9de528fdd1e44eac5cbb0 for depot 264712. Aborting.
Failed to find any server with chunk 8734cf246ff0184bf018b57c81d6c2ff39e1d008 for depot 264712. Aborting.
Failed to find any server with chunk 656e81ac3f71e52f4bdb2458450e1946338947a0 for depot 264712. Aborting.
Failed to find any server with chunk 8652ea74784bc8a3da9f77b60869cadbb27d91ce for depot 264712. Aborting.
Failed to find any server with chunk 7ae6d47ee8bedee8064a73256c06dc4ad57763c1 for depot 264712. Aborting.
Failed to find any server with chunk 7b532760dd2990232c278bae932df8a7ed2cac7c for depot 264712. Aborting.
Failed to find any server with chunk 7ba17d777b36a36c5a559b395b986ed7a9a67327 for depot 264712. Aborting.
Failed to find any server with chunk 7cac3520b388facc66bd066846a6e19bb66cbd4d for depot 264712. Aborting.
Failed to find any server with chunk 719a005551c5fa8635fa0a410daa18e3d1ba6fc7 for depot 264712. Aborting.
Failed to find any server with chunk 7a65f14d218dd586e088e1ca32ec7f120621095a for depot 264712. Aborting.
Failed to find any server with chunk 7aa4b7773a23adfb139915495e5e89fe99879680 for depot 264712. Aborting.
Failed to find any server with chunk 7ba932f9d4b88fcb412b5f6da17ea5ba069fc8e2 for depot 264712. Aborting.
Failed to find any server with chunk 7bc79e94b90834d4f3af85e3d096d3ddeced4faf for depot 264712. Aborting.
Failed to find any server with chunk 7c14151c12798112f7cc14ea201b66d9de0b0597 for depot 264712. Aborting.
Failed to find any server with chunk 86a6996332aef54469880732ca3e212e33b5e02b for depot 264712. Aborting.
Failed to find any server with chunk 8658fca78c31859231ec9064e5b4a72d86deabc0 for depot 264712. Aborting.
Failed to find any server with chunk 79b162f57e456b31cbdc0f170a9b0aa59e6bff8d for depot 264712. Aborting.
Failed to find any server with chunk 7c8c4de3394e51b74dad5aaef01c407d465ce4c4 for depot 264712. Aborting.
Failed to find any server with chunk 7c569c855bd9eab030eabdc4034bb73e8a31d32e for depot 264712. Aborting.
Failed to find any server with chunk 8605bf4b94dee0747825498493c30d97041879ea for depot 264712. Aborting.
Failed to find any server with chunk 7981948752e76cb5ccbcb0e3dbd70686e3b09995 for depot 264712. Aborting.
Failed to find any server with chunk 7a7d134f0f1e346963f9ff79fb0543bb6f5d3589 for depot 264712. Aborting.
Failed to find any server with chunk 865aed75d375db620b73220b820cb64808c036e4 for depot 264712. Aborting.
Failed to find any server with chunk 7a25cda99c1bdc05fcce8f355ed5b88a408f75ed for depot 264712. Aborting.
Failed to find any server with chunk 7bf3dd95db330ad2145915350cd3cbdfed7b1dac for depot 264712. Aborting.
Failed to find any server with chunk 7cb4442464244a93970ca6c75b48becde4a19a95 for depot 264712. Aborting.
Failed to find any server with chunk 79ecc1094293e7d0b8829493efea752d13c6819a for depot 264712. Aborting.
Failed to find any server with chunk 7a3a3986e5008118b3e384071a5b3a36fedea27e for depot 264712. Aborting.
Failed to find any server with chunk 7c2e8a36c61a4b1c6353e93b50ecf18593770a49 for depot 264712. Aborting.
Failed to find any server with chunk 833eb61981e234ad61de579886d8dc89d3270008 for depot 264712. Aborting.
Failed to find any server with chunk 86d76603e388b0cf135579c25255c58cf71f5a84 for depot 264712. Aborting.
Failed to find any server with chunk 7c10357a1c8f0f50aed3f3bc58f4044e4caf8abd for depot 264712. Aborting.
Failed to find any server with chunk 807e0149e0c2fcfa449c23f3634cbf7b961bdcf8 for depot 264712. Aborting.
Failed to find any server with chunk 873c9564ad4a1e798e5688218b43ef2bde34ddeb for depot 264712. Aborting.
Failed to find any server with chunk 7b66c9127272711103a1e296e4d4a28007099f71 for depot 264712. Aborting.
Failed to find any server with chunk 6d318d462ff6b1cd29ef821cc20a915c48c2dd2a

**Comment by azuisleet** [comment]
This depot is likely not available for download.
