### ISSUE TITLE
Depotdownloader can't login to steam

### ISSUE THREAD

**Issue by MichaeLfrh** [SteamRE/DepotDownloader#284]
Hey so I keep getting this message. This thing is. I did gave my username and password. It was all in between quotation marks. 
I'm running the latest version of depotdownloader. 4.2.5 I believe. 
 ```
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 15
Got AppInfo for 962730
App 962730 (Skater XL) is not available from this account.
Disconnected from Steam
```

**Comment by azuisleet** [comment]
You must specify a username as one of the parameters on the command line.

**Comment by MichaeLfrh** [comment]
This is what I put in. Is there something wrong int this line?```
 Dotnet DepotDownloader.dll -app 962730 -depot 962731 -manifest 
8856969232953247160 -username "Blank_blank_" -password "somethingwith!"
```

**Comment by azuisleet** [comment]
It's difficult to say. If it's formatted exactly like you've posted, those arguments may be a new line instead.

**Comment by MichaeLfrh** [comment]
I insert it exactly like I typed here above. I just get this everytime..


 No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 15
Got AppInfo for 962730
App 962730 (Skater XL) is not available from this account.

Can it be that one drive or something is disrupting it? or something else?

**Comment by MichaeLfrh** [comment]
or maybe reinstall steam??
