### ISSUE TITLE
Downloading game for wrong OS

### ISSUE THREAD

**Issue by skylerspaeth** [SteamRE/DepotDownloader#285]
Hi, not sure if this is an issue with this project or something on Valve's side of things, but I can't seem to get the Linux version of CSGO downloaded. I originally wasn't specifying the architecture since the docs say it should download the app for the OS you ran the program from. FWIW I am on Debian 10. Next I tried using the -os linux and -osarch 64 options which seemed to continue doing the same, downloading the Windows version of CSGO with a .exe and no csgo_linux64 binary or the shell script that is present on a typical Linux version of CSGO. I should mention I was worried this could be because CSGO didn't support Linux during the manifest release date that I specified, but read that native Linux support was introduced in 2014 and I'm downloading a 2017 build. Any assistance would be appreciated!

**Comment by azuisleet** [comment]
The OS architecture is only used when evaluating which depots to download. If you specify your own list of depots, those are the depots that will be downloaded.

**Comment by skylerspaeth** [comment]
Ohhh I see. After looking further in to the depot ID on SteamDB I found that it was indeed for a Windows version. I'm new to what depots/manifests/packages/apps mean in the Valve world exactly.

Sorry about raising an issue for this and I appreciate the swift response!
