### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by LvsrsRedDragon** [SteamRE/DepotDownloader#292]
![image](https://user-images.githubusercontent.com/47902811/145089477-33c4b4c3-fa92-43f6-a978-8e4deb0f7e0f.png)

Trying to use the app with no success. Keeps getting the same error, tried disabling read-only, did not work.

**Comment by azuisleet** [comment]
Typically you aren't allowed to access the Program Files folder without an elevated prompt. You should use pretty much any other path.
