### ISSUE TITLE
connection timeout downloading chunk

### ISSUE THREAD

**Issue by Kolotilo12** [SteamRE/DepotDownloader#293]
Hello, I want to install an old version of rust, but when 2% passes in the download, I get a "connection timeout downloading chunk". What to do about it?

**Comment by azuisleet** [comment]
Typically these are transient issues and the chunk will be downloaded from a different server when this occurs.

**Comment by Kolotilo12** [comment]
I waited like this for 10 minutes, and connection timeout downloading chunk constantly appeared. Should I wait even longer?

**Comment by azuisleet** [comment]
No. It's more likely you have a firewall preventing the application from connecting to Steam.

**Comment by Kolotilo12** [comment]
Th
