### ISSUE TITLE
32bit 

### ISSUE THREAD

**Issue by WasherJ** [SteamRE/DepotDownloader#294]
will there be a 32bit version in the future?

**Comment by dxgldotorg** [comment]
Is this compiled as x64 or as Any CPU?  If any native DLLs are used then the app has to match their platform, but if all DLLs are .NET then if all are compiled Any CPU it should work on x86.

**Comment by Lanzador** [comment]
I'm using a 32-bit OS and DD works fine. Don't use DepotDownloader.exe, instead just open cmd and run it from there with the dotnet command.
