### ISSUE TITLE
Linux downloader?

### ISSUE THREAD

**Issue by danger89** [SteamRE/DepotDownloader#295]
Where is the Linux binary?

**Comment by yaakov-h** [comment]
The DepotDownloader binaries themselves are cross-platform. For the runtime, see:

https://docs.microsoft.com/en-au/dotnet/core/install/linux

**Comment by danger89** [comment]
Uh, but it's an exe file? It's not a native binary at all. Meaning I still need WINE to execute the DepotDownloader binaries 😢 .

**Comment by yaakov-h** [comment]
The .exe is a convenience .NET runtime loader for Windows. The actual application code is in the DLL. The readme shows you how to launch it on any platform, the instructions are the same (`dotnet DepotDownloader.dll`)
