### ISSUE TITLE
Pre-allocating...

### ISSUE THREAD

**Issue by PaulNevada** [SteamRE/DepotDownloader#297]
Hi!
v2.4.5 - how does pre-allocation work here? Does it pre-allocate file by file and not several files at the same moment? I'd love to have it 1 by 1 to not to stuck the receiving disk - a flash drive at the moment, actually...

**Comment by azuisleet** [comment]
The application has always pre-allocated new files. We now report when this is happening, as the program would previously be working on this process but not report any progress.

The first stage involving pre-allocation and validation runs at -max-downloads parallelism. 

The second stage of downloading the chunks and writing them to disk also runs at -max-downloads parallelism.

**Comment by PaulNevada** [comment]
So that's why my Samsung flash drive gets stuck that much? And am I able to force this process to work in a sequential character/mode?

**Comment by xPaw** [comment]
`-max-downloads 1` should do  that.
