### ISSUE TITLE
BuildID incorrect (stays most recent) for Skyrim Special Edition for all manifests

### ISSUE THREAD

**Issue by lab-data** [SteamRE/DepotDownloader#298]
I don't believe this is a bug in DepotDownloader, but wanted to share what I've found.

In attempting to download previous versions of Skyrim Special Edition tonight, I've noticed that the Build ID's are staying set at the most recent during download (7891225), regardless of manifest given.  If you attempt to download 2 different builds under the same depot in the same base folder, it will blend/overwrite previous downloads.

Maybe change the downloader to use the manifestID as well in the output folder naming until this is fixed/worked around?  I didn't see an option switch to include that in the output folder naming.

SteamDB is also reflecting the same BuildID for all previous manifests of SkyrimSE when I look them up, so the BuildID change appears to have happened within the Steam catalog data.  The files in a given manifest associations appear to still be correct, but we're left with guessing build dates for obtaining the correct version, at least without another reference.

Not sure if this is a bug/temporary issue, if this is a new normal for Steam games, or just Skyrim SE to discourage downgrading.

**Comment by xPaw** [comment]
Build(ids) specify the manifests used, not the other way around (its actually a bit more complicated than that, due to shared depots and branches). So when you pass in manifestids to download, there's nowhere to get the buildid from (and appinfo will only have the current one).

**Comment by lab-data** [comment]
I'm referring to the directory structure created in the depots folder the downloader creates.  I've been using this for quite some time now and, up until the 1.6.353 release of Skyrim SE, the BuildID folder number always reflected something different related to the manifest numbers I could find in the SteamDB site.  I'm not arguing the relationship you reference, I'm specifically talking about the folders that DD creates when downloading an app manifest.  I was previously able to keep using the same base depot folders to download new versions because the BuildID folder that was created was accurately related to the manifest.  Now, at least for SkyrimSE, no matter the manifest used, the BuildID folder number is ALWAYS the same now.  I ended up blending a 1.5.97 install within the same folder as 1.6.353 because of this.  That is a deviation from the last several times I've used this utility.

**Comment by xPaw** [comment]
It doesn't matter what manifest you use, it will always pull the buildid from the appinfo (which is latest).
What it sounds like is you used DD between Skyrim updates on Steam, so it created different build folders for you.

You should be able to use `-dir` option to download into a dir you specify.

**Comment by lab-data** [comment]
So I was just luckily timing my downloads at the right moment to prevent overlap?  I'd swear I downloaded both the most recent version of SSE (at that time) and the previous version's manifests, without buildID overlap, but you'd know better being the dev of all of this.  Thought for sure I'd uncovered a Bethesda conspiracy to undermine downgrades ;)  Thanks for the -dir tip.  I'll use that from here on.

**Comment by xPaw** [comment]
The folder creation code is here: https://github.com/SteamRE/DepotDownloader/blob/389e7eb788107c7e070dba35ce46c4ebc25bffa1/DepotDownloader/ContentDownloader.cs#L54
