### ISSUE TITLE
BUG: Argument -manifest <id> should be a string instead of integer

### ISSUE THREAD

**Issue by Thundercraft** [SteamRE/DepotDownloader#303]
### Discussed in https://github.com/SteamRE/DepotDownloader/discussions/302

<div type='discussions-op-text'>

<sup>Originally posted by **Thundercraft** January 15, 2022</sup>
I'm pretty sure that the variable for the "-manifest <id>" argument should be a <b>string</b> instead of being limited to an <b>integer.</b> At least, that seems to be the case as of January 2022.

I say this because I know for a fact that the following Steam Console command works without error:
`download_depot 361420 361422 B987A6E73A661CFBC85BA6E3C76C10E8`
(This is with the download_depot Console command being in this form: `download_depot <appid> <depotid> <manifestid>` )

When I use this command, the B987A6E73A661CFBC85BA6E3C76C10E8 manifest id resolves itself to 3262335649682350467 and the depot is downloaded successfully. To prove that this is a legitimate manifest id, check out this listing on SteamDB (might only be visible if you have Astroneer):

[https://steamdb.info/app/361420/depots/?branch=qa_sandbox](https://steamdb.info/app/361420/depots/?branch=qa_sandbox)

My issue with using Steam Console to download this manifest is that it only seems to download the latest version and not the older "qa_sandbox" branch I was looking for. So I thought I would try using DepotDownloader to see if it would do this. But when I tried the following command (my username and password being omitted for obvious reasons), it popped up with an error message and the dotNET SDK halted.

```Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>dotnet --version
5.0.404

C:\Windows\system32>E:

E:\>cd E:\GAME (Steam)\depotdownloader

E:\GAME (Steam)\depotdownloader>dotnet DepotDownloader.dll -app 361420 -depot 361422 -manifest B987A6E73A661CFBC85BA6E3C76C10E8 -username <username> -password <password>
Unhandled exception. System.ArgumentException: B987A6E73A661CFBC85BA6E3C76C10E8
is not a valid value for UInt64. (Parameter 'value')
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCod
e type)
   at System.Number.ParseUInt64(ReadOnlySpan`1 value, NumberStyles styles, Numbe
rFormatInfo info)
   at System.UInt64.Parse(String s, NumberStyles style, IFormatProvider provider
)
   at System.ComponentModel.UInt64Converter.FromString(String value, NumberForma
tInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorConte
xt context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorConte
xt context, CultureInfo culture, Object value)
   at DepotDownloader.Program.GetParameterList[T](String[] args, String param) i
n C:\Projects\DepotDownloader\DepotDownloader\Program.cs:line 346
   at DepotDownloader.Program.MainAsync(String[] args) in C:\Projects\DepotDownl
oader\DepotDownloader\Program.cs:line 209
   at DepotDownloader.Program.Main(String[] args) in C:\Projects\DepotDownloader
\DepotDownloader\Program.cs:line 15
```</div>

**Comment by azuisleet** [comment]
B987A6E73A661CFBC85BA6E3C76C10E8 is an encrypted manifest ID and has to be decrypted instead.

**Comment by NicknineTheEagle** [comment]
@azuisleet There's a bit of an issue with that where, because manifest argument is strictly integer, you cannot download older manifests from encrypted branches.

**Comment by azuisleet** [comment]
The decryption of an manifest key is only possible in the branch lookup path currently.

**Comment by bc15bekl** [comment]
> B987A6E73A661CFBC85BA6E3C76C10E8 is an encrypted manifest ID and has to be decrypted instead.
> 
> The manifest id 3262335649682350467 that was resolved by the Steam Client is actually just the manifest id of the public branch.
> 
> The implementation of this can be seen here https://github.com/SteamRE/DepotDownloader/blob/master/DepotDownloader/ContentDownloader.cs#L272 and the branch password must be supplied to Steam to retrieve the decryption key.

which only works for the current manifest and doesn't let you download specific encrypted manifests if you do have them & have the password as well
