### ISSUE TITLE
should i disable my firewall just for the game to downgrade?

### ISSUE THREAD

**Issue by fineiguessyouaremylittlepogchamp** [SteamRE/DepotDownloader#306]
ive been trying to downgrade payday 2 to the release version of it, but i always keep getting the same message "Connection timeout downloading chunk" should i just ignore the message or just disable my firewall

EDIT: also i just encountered these very peculiar errors... 
Encountered error downloading chunk 2beabdd04ca27df238da29fc54dfe87fbe22e0e7: ServiceUnavailable
Failed to retrieve content server list: The SSL connection could not be established, see inner exception. (even though my connection is just fine, it still says this...)

**Comment by NicknineTheEagle** [comment]
> Connection timeout downloading chunk

These errors are normal, just ignore them as DepotDownloader automatically retries chunk downloads. You do not need to adjust firewall settings for DD to work as it doesn't need to accept any incoming connections.

**Comment by NicknineTheEagle** [comment]
@azuisleet May I suggest changing the text for these error messages to be more indicative of the meaning? I'm seeing people confused by them way too often. Append "Retrying..." to the end, for example, would help a lot.
