### ISSUE TITLE
Stops checking depots for branch at first failure to find match

### ISSUE THREAD

**Issue by lukespragg** [SteamRE/DepotDownloader#31]
When you try to use a specific branch (ie. itemv2 for Hurtworld) and do not specify a depot, it will fail at the first depot and default to the public branch instead of check the other 4+ depots.

This can be resolved by specifying the depot ID, but ideally that shouldn't be required.

**Comment by xPaw** [comment]
```
➜ .\depotdownloader.bat -app 393420 -branch oldversion -osarch 32
Warning: Depot 393424 does not have branch named "oldversion". Trying public branch.
Warning: Depot 393425 does not have branch named "oldversion". Trying public branch.
```

I think this works correctly? Looking at the code and git blaming it I'm not sure when this was even a problem.

**Comment by lukespragg** [comment]
At the time, I had to specify a depot for it to actually get the files as using without one wasn’t working. I don’t know that it is an issue anymore, as I don’t think we specify a depot anymore.

**Comment by xPaw** [comment]
I am looking at git blame, and that code was the same when you created this issue. Can you confirm that it works now, and if so, close this issue?

**Comment by lukespragg** [comment]
We don’t specify a depot anymore than I can tell, so I would assume it is working, so I guess close. ;)
