### ISSUE TITLE
Rate Limit Hit when downloading multiple manifests

### ISSUE THREAD

**Issue by ryantheleach** [SteamRE/DepotDownloader#312]
I have a script that can pull specific files across all manifest versions providing you have them from SteamDB etc.

However, due to the nature of how DepotDownloader works, you can run into rate limiting with authentication.

With remember-password, is it potentially possible to remember the 'session' across subsequent runs of DepotDownloader, instead of re-authenticating?

**Comment by azuisleet** [comment]
`-remember-password` is the only supported way to handle this.

DepotDownloader is not build to download the same app multiple times, so this simply isn't something I can support.

**Comment by ryantheleach** [comment]
Whilst it's probably not a near-term goal, wouldn't it be as straight forward as storing session information somewhere globally? I believe you would run into the same issues if you were checking if an entire steam library were up to date, one application at a time. (since you would need to specify a different directory, for each application anyway)

**Comment by azuisleet** [comment]
`-remember-password` is the session information you are talking about. The session identifier is persisted and resumed upon connection where possible.

If you are running into rate limits, it is somewhere else in the system, such as a logon rate limit.

**Comment by azuisleet** [comment]
To clarify, the login keys are persisted "globally" to isolated storage and not to the current working directory configuration.

https://github.com/SteamRE/DepotDownloader/blob/master/DepotDownloader/AccountSettingsStore.cs

**Comment by ryantheleach** [comment]
Ok, and logging in (which I suspect is what is rate limited) is 100% required on each run, if I had a valid session moments ago? surely there's something that could be cached with the tokens etc, unless it happens upon connection and there's a constant connection kept open?
