### ISSUE TITLE
AccessDenied when attempting to download

### ISSUE THREAD

**Issue by lukespragg** [SteamRE/DepotDownloader#32]
No sure why this is suddenly an issue, but I can download the same appid using SteamCMD without any issues. This used to work just fine with DepotDownloader, so I'm not sure why it started showing AccessDenied.

```
Accepted new login key for account USERNAME
Got AppInfo for 304930
Using app branch: 'public'.
Unable to get appticket for 228986: AccessDenied
Disconnected from Steam
No valid depot key for 228986, unable to download.
Depot 304931 (Unturned Windows 32) is not available from this account.
Depot 304935 (Unturned Windows 64) is not available from this account.
Depot 304933 (Unturned Shared) is not available from this account.
Depot 304938 (Unturned Shared_Release) is not available from this account.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
```

**Comment by azuisleet** [comment]
I can only seem to fetch the app ticket for 228986 from an anonymous account. I'm going to take a look at see what SteamCMD is doing.

**Comment by azuisleet** [comment]
See #33. There are some protocol changes.

**Comment by lavolp3** [comment]
Sorry @azuisleet I can't seem to follow you. 
What do I need to do inside DepotDownloader to resolve the issue?

**Comment by azuisleet** [comment]
The fix for this has been pushed into master, This depends on the new release of SteamKit 2.0.0, which switches to .NET Core 2.0. I'm currently deciding on how to release this is a friendly manner.

**Comment by solomax2014** [comment]
@azuisleet, I tried to build DepotDownloader, but it builds as a .dll...

**Comment by psychonic** [comment]
That's what he was referring to regarding releasing in a friendly manner.

With .NET Core, either a platform-agnostic dll is created, which you execute with the dotnet command, `dotnet DepotDownloader.dll`, like you're seeing - or you generate a platform-specific executable with all dependencies from the runtime (tens of megabytes of dlls).

**Comment by solomax2014** [comment]
@psychonic, ok, thanks!

**Comment by yaakov-h** [comment]
I wonder how much work it would be to create a stub exe for the FDD deployment...

**Comment by lukespragg** [comment]
This has been fixed, so closing the issue. Only thing left is however they setup to release it. For me, I just updated my scripts to use a self-compiled .dll.
