### ISSUE TITLE
cdn out of date

### ISSUE THREAD

**Issue by GordonFreakman** [SteamRE/DepotDownloader#331]
`Connecting to Steam3... Done!
Logging 'XXXXXXXX' into Steam3... Done!
Using Steam3 suggested CellID: 31
Got 210 licenses for account!
Got session token!
Got AppInfo for 4000
Using app branch: 'Public'.
Got depot key for 4001 result: OK
Downloading depot 4001 - GMOD Content
Downloading depot manifest...Got CDN auth token for steamcontent.com result: Fail (expires 1/1/1970 12:00:00 AM)
Disconnected from Steam`

**Comment by xPaw** [comment]
Update.

**Comment by GordonFreakman** [comment]
im on the latest version

**Comment by GordonFreakman** [comment]
worked
