### ISSUE TITLE
Older .NET Runtime Request

### ISSUE THREAD

**Issue by Gwindalmir** [SteamRE/DepotDownloader#332]
Any chance we can get a release that isn't on .NET 6?

I use this in GitHub actions, and that doesn't seem to support .NET 6 yet, so the program can't execute.

**Comment by Gwindalmir** [comment]
Well, I was able to get .NET 6 installed in the Github runner, so I guess not a huge deal now

**Comment by yaakov-h** [comment]
We use GitHub Actions to build our code, so whatever we target is naturally available on GitHub Actions.

**Comment by Gwindalmir** [comment]
> 

It wasn't by default, which was the issue. The windows-latest runner doesn't have .NET 6.0 runtime installed by default.
Either way, appreciate the reply.

**Comment by yaakov-h** [comment]
.NET 6 is supposed to be available on the latest Windows runner. If it's not, I suggest opening an issue with GitHub.

https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#net-core-sdk
