### ISSUE TITLE
"Got CDN auth token for steamcontent.com result: Fail"

### ISSUE THREAD

**Issue by iDavi** [SteamRE/DepotDownloader#333]
I saw that there are other closed issues for this error, but none of the solutions worked

I'm trying to download this depot: https://steamdb.info/depot/105601/history/?changeid=M:7573196773923640738
It's an old version of Terraria

I'm on Windows 11 lastest update

Tried DepotDownloader 2.3.5 and 2.3.6 

I also tried installing .NET SDK 5

`dotnet DepotDownloader.dll -app 105600 -depot 105601 -manifest 7573196773923640738 -username ***** -password ****
Connecting to Steam3... Done!
Logging '******' into Steam3... Done!
Using Steam3 suggested CellID: 25
Got 9 licenses for account!
Got session token!
Accepted new login key for account *******
Got AppInfo for 105600
Using app branch: 'Public'.
Got depot key for 105601 result: OK
Downloading depot 105601 - TerrariaRelease
Downloading depot manifest...Got CDN auth token for steamcontent.com result: Fail (expires 01/01/1970 00:00:00)
Disconnected from Steam`

**Comment by Juesto** [comment]
please update your copy of depotdownloader

**Comment by azuisleet** [comment]
You must use DepotDownloader 2.4.6 as the CDN code used in 2.3.6 is no longer supported. https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.6
