### ISSUE TITLE
Question: How to decrypt encrypted manifest ID?

### ISSUE THREAD

**Issue by tmob03** [SteamRE/DepotDownloader#334]
I have the branch password. When searching through this repository, @azuisleet reponds to questions like this saying you can decrypt them if you have the password, and it's even in depot downloader. @azuisleet how do I decrypt a manifest ID? DepotDownloader readme has no parameter to do this.

**Comment by yaakov-h** [comment]
I believe that is the `-betapassword <pass>` command-line argument which is mentioned in the readme.

It gets used here:

https://github.com/SteamRE/DepotDownloader/blob/72683ef35cc60d6f55f6e79d2902ac564b0c2b7d/DepotDownloader/ContentDownloader.cs#L265-L290

Which calls this function:

https://github.com/SteamRE/SteamKit/blob/abddc535b96ae7219ef9a1aaef6c291366d29934/SteamKit2/SteamKit2/Util/CryptoHelper.cs#L422-L453

**Comment by tmob03** [comment]
I've tried that arguement and I get an error of the manifest being a string since it's still encrypted. Maybe i'm doing it wrong? this is what i'm inputing (with the values removed) `dotnet DepotDownloader.dll -beta -betapassword  -app  -depot  -manifest  -username -password`

**Comment by yaakov-h** [comment]
I suspect that if the manifest ID you have is a hexadecimal string, then you'll need to manually follow along with the code snippet above to convert it into bytes, decrypt the bytes, then convert it back into a number. Only then can you use that number with `-manifest` on the command line.

**Comment by tmob03** [comment]
Nevermind, I got steamctl to decrypt it.
