### ISSUE TITLE
Unable to download manifest 9114506817795670562 for depot 337321 [PAINT THE TOWN RED]

### ISSUE THREAD

**Issue by EthanJamesBarron** [SteamRE/DepotDownloader#337]
I'm trying to download an older version of Paint The Town Red. Here's the command I used

dotnet depotdownloader.dll -app 337320 -depot 337321 -manifest 9114506817795670562 -username myuser -password mypassword

Downloading depot manifest...Encountered 401 for depot manifest 337321 9114506817795670562. Aborting.

**Comment by azuisleet** [comment]
You must use DepotDownloader 2.4.6 as manifest request codes are now required when downloading from Steam. https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.6
