### ISSUE TITLE
access denied to the folder issue!!!!

### ISSUE THREAD

**Issue by lilpotatochip** [SteamRE/DepotDownloader#338]
when i try it says this: 

Download failed to due to an unhandled exception: Access to the path 'C:\Users\noneofyourbuisnessyoungBUCK\Downloads\depotdownloader-2.4.6\depots\454651\8934572\bin\DBXV2.exe' is denied.

**Comment by azuisleet** [comment]
It's possible that you have anti-virus software or something similar trying to lock these files. If you have any more information, feel free to open a new issue.
