### ISSUE TITLE
401 Unauthorized for titles that worked previously

### ISSUE THREAD

**Issue by doctashay** [SteamRE/DepotDownloader#340]
Hello! 

I use Depot Downloader pretty frequently for preservation purposes. Just a week ago or so, I downloaded 20+ manifests of various games and they all worked fine - downloaded completely.

Today, I was attempting to archive some different builds, and ran into a new issue I haven't seen before. I get a 401 Unauthorized error whenever I attempt to download a manifest. It doesn't seem to matter what game or what manifest I select, the issue is the same each time. 

I've tried 5 different manifests on two different games, DayZ and Arma 3, both worked fine a week ago. I have full ownership of both games on Steam and am logging in as that user when attempting to download. Is it possible there was a change to Valve's API for content delivery?

**Comment by Juesto** [comment]
Valve has enforced manifest request codes for good this time. they had some issues and had to revert it a bit ago.

**Comment by doctashay** [comment]
> Please update your copy of depotdownloader

I'm using the latest master branch from this repository, is there another one I should be using?

**Comment by Juesto** [comment]
> > Please update your copy of depotdownloader
> 
> I'm using the latest master branch from this repository, is there another one I should be using?

Sorry, maybe you're trying to access a manifest that is actually unavailable, not much you can do about game/developer choices.

**Comment by doctashay** [comment]
> > > Please update your copy of depotdownloader
> > 
> > 
> > I'm using the latest master branch from this repository, is there another one I should be using?
> 
> Sorry, maybe you're trying to access a manifest that is actually unavailable, not much you can do about game/developer choices.

Can developers see what users are requesting what manifests and how many downloads they've received recently? I stumbled upon some internal branches for DayZ (64bittest, survivor gamez depot) which *should have* been inaccessible, but allowed me to download anyway, so I'm wondering if grabbing these unreleased versions prompted them to lock down their manifests? It's like this with all Bohemia games now.

**Comment by Juesto** [comment]
Sounds out of scope here.

**Comment by Juesto** [comment]
> > > > Please update your copy of depotdownloader
> > > 
> > > 
> > > I'm using the latest master branch from this repository, is there another one I should be using?
> > 
> > 
> > Sorry, maybe you're trying to access a manifest that is actually unavailable, not much you can do about game/developer choices.
> 
> Can developers see what users are requesting what manifests and how many downloads they've received recently? I stumbled upon some internal branches for DayZ (64bittest, survivor gamez depot) which _should have_ been inaccessible, but allowed me to download anyway, so I'm wondering if grabbing these unreleased versions prompted them to lock down their manifests? It's like this with all Bohemia games now.

Sounds out of scope here.

**Comment by Headline** [comment]
I believe I'm hitting something similar, but I'm not intentionally fishing for anything other than public release builds

```
bots@gabriel:~/steamdepotdownloader$ dotnet DepotDownloader.dll -all-platforms -app 740 -filelist files.txt -dir downloads -validate
Using filelist: 'files.txt'.
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 81
Got AppInfo for 740
Using app branch: 'Public'.
Got depot key for 731 result: OK
Got depot key for 740 result: OK
Processing depot 731 - Counter-Strike Global Offensive Beta Common
Downloading depot manifest...Encountered 401 for depot manifest 731 8470578532521242053. Aborting.

Unable to download manifest 8470578532521242053 for depot 731
App 740 was not completely downloaded.
The operation was canceled.
Disconnected from Steam
```

**Comment by azuisleet** [comment]
You must use DepotDownloader 2.4.6 as manifest request codes are now required when downloading from Steam. https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.6

```
C:\Users\Azu\Downloads\depotdownloader-2.4.6>dotnet DepotDownloader.dll --all-platforms -app 740
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 49
Got AppInfo for 740
Using app branch: 'Public'.
Got depot key for 731 result: OK
Got depot key for 740 result: OK
Processing depot 731 - Counter-Strike Global Offensive Beta Common
Downloading depot manifest...Got manifest request code for 731 8470578532521242053 result: 3805952584754230213
 Done!
Manifest 8470578532521242053 (7/27/2022 11:24:19 PM)
Processing depot 740 - Counter-Strike Global Offensive Beta - Dedicated Server
Downloading depot manifest...Got manifest request code for 740 1587973518387901018 result: 16938311942661812929
 Done!
Manifest 1587973518387901018 (7/27/2022 11:24:38 PM)
Downloading depot 731 - Counter-Strike Global Offensive Beta Common
```
