### ISSUE TITLE
App is not available from account (Even though i own it)

### ISSUE THREAD

**Issue by ExtractBlade** [SteamRE/DepotDownloader#341]
So i recently bought a game and apparently when i tried to downgrade the game is says "App () is not available from this account", even though it is in my library and i own it.

**Comment by PoIakis** [comment]
I am getting this error as well, the app it says for me is Resume Makerr for Mac

**Comment by PoIakis** [comment]
Well I just figure it out for me, I was typing the appID wrong lmaoo make sure you aren't typing anything in wrong.

**Comment by ExtractBlade** [comment]
i retyped it 4 times and still didnt work.
