### ISSUE TITLE
Potential security issue with -password

### ISSUE THREAD

**Issue by stopmotio** [SteamRE/DepotDownloader#343]
`-password` is insecure in public settings but also may not be treated fully securely by the OS. I don't know how Windows specifically handles passwords but I do know Linux has them entered after the main command and completely hidden while typing. Not sure if Windows does this but it would be nice if it did.

I apologize if this is clutter.

**Comment by azuisleet** [comment]
The password can be entered interactively, and is masked.

https://github.com/SteamRE/DepotDownloader#why-doesnt-my-password-containing-special-characters-work-do-i-have-to-specify-the-password-on-the-command-line

**Comment by stopmotio** [comment]
Very good! But we should probably make this known in the readme or show a message that `-password` isn't necessary.

**Comment by yaakov-h** [comment]
The square brackets in the readme for `[-password <password>]` are a standard notation which indicate that the argument is optional.

**Comment by stopmotio** [comment]
My bad. But I think it's still a bit cryptic.
