### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by solomax2014** [SteamRE/DepotDownloader#35]
Can you make a new release? Just the old one don't have some new fixes like "Access Denied" fix.

**Comment by MJBrune** [comment]
Was about to download the latest release and saw it was over a year old... Wow good thing I checked. Can we get a release pushed?

**Comment by MJBrune** [comment]
Got sick of waiting https://github.com/MJBrune/DepotDownloader/releases/tag/DepotDownloader_2.2.3 enjoy.

**Comment by psychonic** [comment]
Nice try, but that doesn't appear to work on my Linux box that does have the .NET Core runtime installed.

Welcome to the fun of packaging for .NET Core, where you effectively created a 20mb executable package that only runs on a single OS.

**Comment by MJBrune** [comment]
I'm fine with not supporting linux for that builds purpose.

**Comment by azuisleet** [comment]
It doesn't look like there's going to be a .NET Framework experience that supports .NET Standard 2.0. It requires installing the .NET Core SDK, so there doesn't appear to be any reason to target .NET Framework. I've published a 2.3.0 FDD release.

**Comment by MJBrune** [comment]
ah awesome. Thank you very much. Turns out the best way to get a new release is to do it in a way someone doesn't like. :P In all seriousness this application is fairly awesome. Thank you for continued support.

**Comment by azuisleet** [comment]
The delay was mostly to wait and see if the .NET Framework situation was going to change. I suppose I'll just have to accept the state of FDD, but I'm sad to see the executable launcher go. I'm closing this issue as I believe this release is sufficient.
