### ISSUE TITLE
"It was not possible to find any compatible framework version"

### ISSUE THREAD

**Issue by Trupphol** [SteamRE/DepotDownloader#351]
_"It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - The following frameworks were found:
      5.0.17 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

![Screenshot 2022-08-22 013848](https://user-images.githubusercontent.com/111733031/185866180-9e1d84c5-3388-4279-9ed6-a9c777cbe76f.png)

I have installed the NET core from that link but the same message is still given to me

**Comment by yaakov-h** [comment]
You need .NET 6, but you’ve only installed .NET 5.

**Comment by Trupphol** [comment]
> 

Ive installed .NET 6 but I still get the same message every time, I found the folder for 5.0 and if I delete it it only says I have no SDK but the only files I can find for 6.0 are in my temp files

**Comment by Trupphol** [comment]
figured it out I just needed the x64 version
