### ISSUE TITLE
Unable to get steam3 credentials.

### ISSUE THREAD

**Issue by cry122** [SteamRE/DepotDownloader#356]
![ffCapture](https://user-images.githubusercontent.com/113646347/190524367-8999a468-d608-456b-9bef-e02234769eb0.JPG)
![Capture](https://user-images.githubusercontent.com/113646347/190524368-893f10c4-fe91-4694-b7a6-19501823bb62.JPG)
I have tried to escape/alter my password as well. Any help greatly appreciated!

**Comment by yaakov-h** [comment]
Try running with `-debug`, that should give us more useful information.

Please post logs as text rather than images.
