### ISSUE TITLE
App halts after Disconnected from Steam (Sometimes)

### ISSUE THREAD

**Issue by austinv900** [SteamRE/DepotDownloader#36]
Some reason. The app halts once files are downloaded and stays on Disconnected from Steam and doesn't accept any more input. Can only force close the console.

https://imgur.com/a/wAugIu1

**Comment by azuisleet** [comment]
What command line do you use? For example, are you using -remember-password?

**Comment by austinv900** [comment]
Powershell. And no not using remember password. Logging in anonymous

**Comment by austinv900** [comment]
Tested it on a CI build server and locally. CI fails each time. Local I've only been able to do it the very fist time

**Comment by azuisleet** [comment]
I'm able to reproduce this. I'll let you know shortly.

**Comment by azuisleet** [comment]
I've released 2.3.0 hotfix 1. It looks like the connection monitor task was never actually shutting down.

https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.3.0/depotdownloader-2.3.0-hotfix1.zip

**Comment by austinv900** [comment]
Thanks for the fast fix
