### ISSUE TITLE
nie moge zalogować się do depotdownloader bo wyskakuje to 

### ISSUE THREAD

**Issue by niepodamnikomu** [SteamRE/DepotDownloader#371]
Enter account password for "amogus": **********
Connecting to Steam3...Connection to Steam failed. Trying again
 Done!
Logging 'amogus' into Steam3...Unable to login to Steam3: InvalidPassword
Unable to get steam3 credentials.
Error: InitializeSteam failed

**Comment by SlejmUr** [comment]
Steam login name

**Comment by niepodamnikomu** [comment]
jest dobra hasło tak samo
![Screenshot_1](https://user-images.githubusercontent.com/106471471/202909768-294083ff-9370-4da9-993d-06dbc91523b3.png)

**Comment by SlejmUr** [comment]
You sure you give the login name and the login password.
Not the nickname?

**Comment by niepodamnikomu** [comment]
naprawione wystarczyło zmienić email w steam NA TEN SAM

**Comment by niepodamnikomu** [comment]
jak zamknąć problem
