### ISSUE TITLE
No depots folder in the zip file

### ISSUE THREAD

**Issue by GrenHubber** [SteamRE/DepotDownloader#374]
there is no depots folder in the zip file

**Comment by psychonic** [comment]
Why would there be?

**Comment by GrenHubber** [comment]
I have seen videos where it gets created upon downloading a depot but for some reason mine didn't appear. Is it possibly because it failed to get a chunk?

**Comment by GrenHubber** [comment]
I have found the depots folder. It has been placed weirdly in my opinion but I found it.
