### ISSUE TITLE
probably a stupid question - no .exe

### ISSUE THREAD

**Issue by AlbinoPolarbear** [SteamRE/DepotDownloader#38]
Hi - I downloaded the files to a folder and tried to use it, but there is no .exe file. I guess I probably just need to do some kind of installation process, but I don't know what I'm doing. Can someone please help? Thanks!

**Comment by psychonic** [comment]
It requires .NET Core to be installed.

Then you can launch it as `dotnet DepotDownloader.dll <args>`

**Comment by AlbinoPolarbear** [comment]
Thanks! I wish you good karma!

**Comment by coldman4** [comment]
Hi, I'm really new to this sort of thing. when I try to run dotnet DepotDownloader.dll <arguments>", I get the error: "could not execute because the specified command or file could not be found." Does this mean it's looking for depotdownloader and can't find it? How do I fix that?

**Comment by psychonic** [comment]
You need to have the .NET Core runtime installed.

**Comment by coldman4** [comment]
I actually had it installed already, but i think it was the wrong version (3.1 instead of 2.0). Now I get this error instead: No executable found matching command "dotnet-DepotDownloader.dll"
