### ISSUE TITLE
Support .NET SDK 7

### ISSUE THREAD

**Issue by C0rn3j** [SteamRE/DepotDownloader#389]
.NET 7 came out a few months ago, though the global.json still relies on 6.x for now.

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by yaakov-h** [comment]
Producing net7.0 assemblies would probably be a waste of times but using the .NET 7 SDK to produce a net6.0 application would be fine IMO.

**Comment by xPaw** [comment]
It targets net8.0 now.
