### ISSUE TITLE
Some app IDs not available for the anonymous account

### ISSUE THREAD

**Issue by RogueLizard** [SteamRE/DepotDownloader#39]
Trying to download The Divinity Engine 2 (664400). Returns "app is not available for this account."

Downloads Divinity Original Sin 2 just fine. Won't download 664400 afterwards either.

**Comment by xPaw** [comment]
Well, 664400 is not available for anonymous users. What did you expect?

https://steamdb.info/app/664400/subs/

**Comment by RogueLizard** [comment]
I also tried logging in with my personal steam account, did the thing with
Steam Guard, and it still didn't work.

**Comment by xPaw** [comment]
Well, does your account own it?

**Comment by RogueLizard** [comment]
I own Divinity Original Sin 2. The editor counts as DLC but it's free.
Steam won't open the purchase page so I tried this. And it doesn't work.

**Comment by xPaw** [comment]
It's not a DLC of the base game. Your account most likely just doesn't own it and you're looking at the wrong thing. This isn't an issue with depot downloader.

You can do `licenses_for_app 664400` in Steam console or steamcmd.

**Comment by RogueLizard** [comment]
"no active license found".

**Comment by xPaw** [comment]
As I said, your account doesn't own it.

**Comment by RogueLizard** [comment]
The editor? Well, obviously, but I paid for the game, and the paid game is
the only prerequisite for the editor, according to SteamDB.

So I don't know what the problem is.

Do those old hacked steam clients still work?

**Comment by xPaw** [comment]
You don't own the app == you can't download it.

Simple as that.

**Comment by RogueLizard** [comment]
Okay. So my question is then, why isn't steam taking me to the download
page when I request it, even directly via URL? A bug, or what?
