### ISSUE TITLE
Official docker image?

### ISSUE THREAD

**Issue by dumbasPL** [SteamRE/DepotDownloader#404]
Would be nice to have an official docker image that is automatically built in CI/CD.

LMK if you need any help setting it up or want me to make a PR

**Comment by psychonic** [comment]
I don't see any reason that we shouldn't have one. Feel free to submit a PR.

**Comment by xPaw** [comment]
I have a different question, what do you need a docker image for?

If you don't want to install .NET, providing standalone builds would be a better idea imo.

**Comment by xPaw** [comment]
You can give a self contained build from here a try: https://github.com/SteamRE/DepotDownloader/actions/runs/4594451840

**Comment by dumbasPL** [comment]
All the Linux builds (and probably the rest as well) are arm64 because when you run 3 builds in a row they overwrite each other.  
Tip: throw the arch into the matrix (windows also has arm now `;)`) and use the matrix variables in the build/upload stages instead of if statements

**Comment by xPaw** [comment]
Oh yeah oops, they just have to be built into separate folders.

**Comment by dumbasPL** [comment]
nice, will they be available somewhere outside of gh actions though? Maybe gh (pre)releases? Downloading artifacts outside of a browser is a pain.

**Comment by yaakov-h** [comment]
IIRC @azuisleet wasn't happy with releasing self-contained builds, but I don't remember why.

From a security perspective it's a pain - instead of the user installing a patch, we have to rebuild and rerelease the whole application - but I suspect most users won't actually care about that, it's more of an enterprise-y thing.

(The same applies to container images anyway, though.)

**Comment by xPaw** [comment]
Size of the binary is one concern, especially because we can't trim them easily.

**Comment by yaakov-h** [comment]
I was working on trimming a while ago but protobuf-net just isn't there yet. We would need to switch to the Google library or something else more trim-friendly in order to get that working, and potentially then an AOT-compiled build could also be on the cards 🥺

**Comment by Troughy** [comment]
Any news regarding this issue? What's the current best way of running DepotDownloader in a Docker container?

**Comment by xPaw** [comment]
RE: self contained binaries

Releases do have stand alone binaries you can use now.
