### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by emorrp1** [SteamRE/DepotDownloader#42]
Is this code intended to be open source by all 9 contributors? Without a license file or any reference to copyrights, the default in most copyright jurisdictions would be "All rights reserved.".

The SteamKit2 library is LGPL2 or later, would you consider re-licensing DepotDownloader under GPL3 or later? You would need an explicit acknowledgement from all contributors.

Finally, thanks for providing a non-Steam way of downloading the games :)

**Comment by TBK** [comment]
I would also like to get this clarified. Currently it is impossible for me to package DepotDownloader for various Linux distros.

**Comment by azuisleet** [comment]
We discussed this, and we agreed that GPLv2 was the most appropriate license.

**Comment by emorrp1** [comment]
Awesome, thanks for sorting it!
