### ISSUE TITLE
Chinese CDNs require authentication (Encountered 403 for depot manifest)

### ISSUE THREAD

**Issue by huddhudd** [SteamRE/DepotDownloader#424]
### What did you expect to happen?

 dotnet DepotDownloader.dll -app 578080 -depot 578081 -username huddcc2 -password [REDACTED]
Connecting to Steam3... Done!
Logging 'huddcc2' into Steam3...Lost connection to Steam. Reconnecting
 Done!
Logging 'huddcc2' into Steam3... Done!
Using Steam3 suggested CellID: 204
Got 102 licenses for account!
Got AppInfo for 578080
Using app branch: 'Public'.
Got depot key for 578081 result: OK
Processing depot 578081 -
Downloading depot manifest...Got manifest request code for 578081 1224926623952854117 result: 16311532807010240413
Encountered 401 for depot manifest 578081 1224926623952854117. Aborting.

Unable to download manifest 1224926623952854117 for depot 578081
App 578080 was not completely downloaded.
The operation was canceled.
Disconnected from Steam

### Instead of that, what actually happened?

Encountered 401 for depot manifest 578081 1224926623952854117. Aborting.

Unable to download manifest 1224926623952854117 for depot 578081

### Which operating system are you running on?

Windows

### Version

6

**Comment by yaakov-h** [comment]
What version of DepotDownloader are you using?

**Comment by shaoyy** [comment]
I have the same issue both in 2.4.5 and 2.4.7

**Comment by oureveryday** [comment]
It seems Chinese cdn verify problem for 
`dl.steam.clngaa.com
st.dl.bscstorage.net
trts.baishancdnx.cn
xz.pphimalayanrt.com
`

**Comment by shaoyy** [comment]
> Are you in China?

Yes.

**Comment by huddhudd** [comment]
Is it so difficult that only China has this problem? I am also in China

**Comment by oureveryday** [comment]
> Is it so difficult that only China has this problem? I am also in China

Specify the cdn with this tool works https://www.dogfight360.com/blog/1531/

**Comment by SlyCooperReloadCoded** [comment]
I'm located in the USA and I'm also having this issue.

**Comment by oureveryday** [comment]
`Unable to download manifest 8731387993101941680 for depot 225543`
Nope it's manifest download problem, not depot download problem.

**Comment by oureveryday** [comment]
getCDNAuthToken(appID, depotID, hostname, callback)
appID - The ID of the app for which you want an auth token
depotID - The ID of the depot for which you want an auth token
hostname - The hostname of the content server for which you want an auth token
callback - Called when the requested data is available
err - An Error object on failure, or null on success
token - The requested auth token on success, as a string
expires - On success, this is the time when this token will expire, as a Date object
Requests an auth token for a particular DepotID to be downloaded from a given content server. One token is required per depot and per content server. On success, the token will be cached in memory until it expires or the SteamUser disconnects.

This token will usually be an empty string, but not always.

We should use this to get a CDN Auth Token for download in these Chinese CDNs.

**Comment by huddhudd** [comment]
I'll try it tomorrow. Has anyone tried it

**Comment by oureveryday** [comment]
> I'll try it tomorrow. Has anyone tried it

https://github.com/oureveryday/DepotDownloaderMod/releases/tag/DepotDownloaderMod_2.4.5.6

Release executable

**Comment by Funny-ppt** [comment]
> > I'll try it tomorrow. Has anyone tried it
> 
> https://github.com/oureveryday/DepotDownloaderMod/releases/tag/DepotDownloaderMod_2.4.5.6
> 
> Release executable

i tried to compile a linux_x64 version myself and it doesn't work now (using cdn: dl.steam.clngaa.com)

**Comment by JL-victor** [comment]
> > 我明天试试。有人试过吗
> 
> https://github.com/oureveryday/DepotDownloaderMod/releases/tag/DepotDownloaderMod_2.4.5.6
> 
> 发布可执行文件

 文件安装在哪才能配对啊

**Comment by xPaw** [comment]
Last steamkit update added cdnAuthToken back to download methods, so someone just needs to create a pull request that gets auth tokens and uses them.

Basically revert cdn auth token changes from this commit with some cleanup: https://github.com/SteamRE/DepotDownloader/commit/969a394fdd5e42c7ce56fac2b96280553bd2df1c

**Comment by xPaw** [comment]
Can you guys give this build a test: https://github.com/SteamRE/DepotDownloader/actions/runs/10561609465

It will attempt to get a cdn auth token when getting a HTTP 403 error.

**Comment by oureveryday** [comment]
> Can you guys give this build a test: https://github.com/SteamRE/DepotDownloader/actions/runs/10561609465
> 
> It will attempt to get a cdn auth token when getting a HTTP 403 error.

Yes it worked in Chinese CDNs.
