### ISSUE TITLE
Valve seems to have broken some depots

### ISSUE THREAD

**Issue by Aida-Enna** [SteamRE/DepotDownloader#428]
### What did you expect to happen?

The depot to download/give me information

### Instead of that, what actually happened?

```
Connecting to Steam3... Done!
Logging 'REDACTED' into Steam3... Done!
Got 2 licenses for account!
Got AppInfo for 1056640
Using app branch: 'Public'.
Warning: Depot 1056641 does not have branch named "Public". Trying public branch.
Depot 1056641 () missing public subsection or manifest section.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Disconnected from Steam
```

This happens on ~~seemingly every depot~~ some depots? now because of a change valve implemented 2 hours ago:~https://steamdb.info/changelist/18821630/

### Which operating system are you running on?

Tested on Windows and Linux

### Version

Official and a fork

**Comment by Aida-Enna** [comment]
I tested some more and it seems like it's not affecting every game, just specific ones. Someone complained about getting this issue on MHW but it's reproducable on PSO2: New Genesis.

For example, PUB:G downloads fine:
```DepotDownloader.exe -app 578080 -depot 578081 -username REDACTED -password REDACTED
Connecting to Steam3... Done!
Logging 'REDACTED' into Steam3... Done!
Got 3 licenses for account!
Got AppInfo for 578080
Using app branch: 'Public'.
Got depot key for 578081 result: OK
Processing depot 578081 -
Downloading depot manifest...Got manifest request code for 578081 7931454927563477701 result: 11295314931379368277
 Done!
Manifest 7931454927563477701 (5/16/2023 8:14:57 AM)
Downloading depot 578081 -
```

However, PSO2: New Genesis does not:

```DepotDownloader.exe -app 1056640 -depot 1056641 -username REDACTED -password REDACTED
Connecting to Steam3... Done!
Logging 'REDACTED' into Steam3... Done!
Got 3 licenses for account!
Got AppInfo for 1056640
Using app branch: 'Public'.
Warning: Depot 1056641 does not have branch named "Public". Trying public branch.
Depot 1056641 () missing public subsection or manifest section.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Disconnected from Steam```

**Comment by krafs** [comment]
I am experiencing the same issue with downloading the public branch of Rimworld. Has worked perfectly the last year, but now a couple of days ago my downloads started failing with the same error: "missing public subsection or manifest section."

It works fine if I explicitly provide a manifest id (instead of only app id and depot id) with the `-manifest` argument, but that won't give me the latest manifest if there's been a new released.

**Comment by rotioN29** [comment]
> You can give latest build a try: https://github.com/SteamRE/DepotDownloader/actions/runs/5153489983

Me and my friend tried this with Pufferpanel and it fixed the problems.
