### ISSUE TITLE
Output or Save Steam User ID

### ISSUE THREAD

**Issue by qjimbo** [SteamRE/DepotDownloader#431]
### What problem is this feature trying to solve?

Firstly thank you for making this tool!

I have implemented the DepotDownloader in my project at https://github.com/qjimbo/NMSLegacyVersionInstaller and it works great, however I have one issue, locating the user's steam ID in order for the installer to configure the game to read savegames from the correct location.

### How would you like it to be solved?

If DepotDownloader could store the user's steam ID somewhere, such as in the .DepotDownloader folder, or even output it to the commandline, it would be enormously helpful for my project!

### Have you considered any alternative solutions

Alternatively perhaps there is a way to get the steam ID already that I am not aware of?

**Comment by ThanosAtha** [comment]
well, i also need to make it OneClick-Installer for others (to a specific game depot), so can we make it somehow to prompt & ask for the Username & Password??? (it will be bat2exe converted, no edit by client)

**Comment by xPaw** [comment]
This request is not relevant to DD. You can get user's steamid by using the steamworks apis/sdk against the running Steam client.
