### ISSUE TITLE
Always Recieving "InvalidPassword"

### ISSUE THREAD

**Issue by spacebytee** [SteamRE/DepotDownloader#442]
### What did you expect to happen?

It would login to my account successfully.

### Instead of that, what actually happened?

Always recieve "InvalidPassword'

### Which operating system are you running on?

Windows

### Version

2.5.0

### Relevant log output

```shell
DepotDownloader -app 105600 -depot 105601 -manifest 5761620975617404996 -username xxxxxx -password "xxxxxxxxx"
Connecting to Steam3... Done!
Logging 'username xxxxxx' into Steam3...
Failed to authenticate with Steam: Authentication failed with result InvalidPassword.
Disconnected from Steam
Unable to get steam3 credentials.
Error: InitializeSteam failed
```

### Additional Information

I am using command prompt. My password has been escaped correctly, and I am 100% sure my credentials are correct. No matter what I do, it returns this error. I have disabled Steam Guard. I have also tried removing the password field to enter it manually, and I receive the same error.

Username and password have been censored for obvious reasons.

**Comment by pjy612** [comment]
not use "" ?

**Comment by fyoory** [comment]
I wanted to post I got the same error, nothing to 'escape' in my password but it is an account using steams 2FA.  So I wonder if its related to that.   Quotes or no quotes....

**Comment by fyoory** [comment]
Update, if you drop the -password and enter it manually it asks for the auth code.   So not sure if that is a bug or a consequence of using 2FA.  I'll leave that to you.  Just here to report.

**Comment by xPaw** [comment]
Do you still get this on 2.6.0?
