### ISSUE TITLE
Steam depot downloader not working properly

### ISSUE THREAD

**Issue by Xxangelica15xX** [SteamRE/DepotDownloader#445]
### What did you expect to happen?

For ark older version to download

### Instead of that, what actually happened?

Connection timeout downloading chunk 05a10c8a109c58267a538834a1115cd123c68c87
Connection timeout downloading chunk 300434e95bbde9ccfa3017c76a5384d38b9e7988
Connection timeout downloading chunk 6b1cbb2e454cc0a0abe5f6c9b2ab636f4d04879d
Connection timeout downloading chunk 7ab23eae26f2a31ced167e73b7919689cfde4677
Connection timeout downloading chunk 068165ad09f8068e0778250af9e20246a9457064
Connection timeout downloading chunk a0e8a3c6c83b2831e14862d16eeb4aa1285e5923
Connection timeout downloading chunk 05a10c8a109c58267a538834a1115cd123c68c87
Connection timeout downloading chunk 300434e95bbde9ccfa3017c76a5384d38b9e7988
Connection timeout downloading chunk 6b1cbb2e454cc0a0abe5f6c9b2ab636f4d04879d
Connection timeout downloading chunk 7ab23eae26f2a31ced167e73b7919689cfde4677
Connection timeout downloading chunk a0e8a3c6c83b2831e14862d16eeb4aa1285e5923
Connection timeout downloading chunk 068165ad09f8068e0778250af9e20246a9457064
Failed to retrieve content server list: A task was canceled.
App 346110 was not completely downloaded.
The operation was canceled.
Disconnected from Steam

### Which operating system are you running on?

Windows

### Version

2.5.0

### Relevant log output

```shell
Connection timeout downloading chunk 05a10c8a109c58267a538834a1115cd123c68c87
Connection timeout downloading chunk 300434e95bbde9ccfa3017c76a5384d38b9e7988
Connection timeout downloading chunk 6b1cbb2e454cc0a0abe5f6c9b2ab636f4d04879d
Connection timeout downloading chunk 7ab23eae26f2a31ced167e73b7919689cfde4677
Connection timeout downloading chunk 068165ad09f8068e0778250af9e20246a9457064
Connection timeout downloading chunk a0e8a3c6c83b2831e14862d16eeb4aa1285e5923
Connection timeout downloading chunk 05a10c8a109c58267a538834a1115cd123c68c87
Connection timeout downloading chunk 300434e95bbde9ccfa3017c76a5384d38b9e7988
Connection timeout downloading chunk 6b1cbb2e454cc0a0abe5f6c9b2ab636f4d04879d
Connection timeout downloading chunk 7ab23eae26f2a31ced167e73b7919689cfde4677
Connection timeout downloading chunk a0e8a3c6c83b2831e14862d16eeb4aa1285e5923
Connection timeout downloading chunk 068165ad09f8068e0778250af9e20246a9457064
Failed to retrieve content server list: A task was canceled.
App 346110 was not completely downloaded.
The operation was canceled.
Disconnected from Steam
```

**Comment by NicknineTheEagle** [comment]
If you're downloading a rare game or an old version, not all servers might have it. Try using -cellid parameter to select a more "central" cell like 1 or 4.
