### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by allan888** [SteamRE/DepotDownloader#465]
### What did you expect to happen?

成功下载

### Instead of that, what actually happened?

提示401然后与steam断连。

### Which operating system are you running on?

Windows

### Version

2.4.4

### Relevant log output

```shell
Encountered 401 for depot manifest 774172 385668526093753917. Aborting.

Unable to download manifest 385668526093753917 for depot 774172
App 774171 was not completely downloaded.
The operation was canceled.
Disconnected from Steam
```

**Comment by allan888** [comment]
The version I use was 2.5.0

**Comment by cyjyyd** [comment]
same for me. have no idea why it happening
