### ISSUE TITLE
[Feature Request] Force Region

### ISSUE THREAD

**Issue by marcussacana** [SteamRE/DepotDownloader#47]
I want download a region locked game, but looks like the DepotDownloader singin in the steam as a US user, then I can't download the depot.

**Comment by azuisleet** [comment]
If the default cell isn't in the location you want, you can override it with -cellid. I don't know what the current mappings are though

**Comment by VoiDeD** [comment]
You can get a list of cells from the cellmap.vdf file - SteamDB has is tracked here: https://github.com/SteamDatabase/SteamTracking/blob/master/ClientExtracted/steam/cached/CellMap.vdf

Not 100% sure if this is still being utilized by the client itself, but it should still be accurate.

**Comment by marcussacana** [comment]
thx, srry for disturb, just this cellid isn't a name much user-friendly to understand...
