### ISSUE TITLE
Skip OS check if depotid is specified directly

### ISSUE THREAD

**Issue by xPaw** [SteamRE/DepotDownloader#48]
> depotdownloader -app 250820 -depot 250832
> Depot 250832 not listed for app 250820 or not available on this platform

I feel like this check is useless when depotid is specified directly, which requires specifying OS/all-platforms unnecessarily.

**Comment by azuisleet** [comment]
This is resolved in e7b89df7432b971b13620e5ed5b428d1b08782d1
