### ISSUE TITLE
Modify Depot downloader to store depot access keys etc

### ISSUE THREAD

**Issue by nutterthanos** [SteamRE/DepotDownloader#491]
### What problem is this feature trying to solve?

What I find with it that if I download more than a certain amount of manifests at a time I get rate limited due to constant logins.

### How would you like it to be solved?

Storing depot access keys or whatever they are called can prevent DepotDownloader having to login for it every download with an offline manifest and the depot access key/decryption key since manifests that have not been downloaded yet nor the depot access key/decryption key will always need to be logged in.

### Have you considered any alternative solutions

Including downloading more than one manifest in the same login as well as above instead of one manifest download per login

**Comment by xPaw** [comment]
`-remember-password` saves the access token, but every time you re-run the exe it has to reconnect to Steam, there's no way around that.

You can specify multiple `-depot` params to download at once.

**Comment by nutterthanos** [comment]
> `-remember-password` saves the access token, but every time you re-run the exe it has to reconnect to Steam, there's no way around that.

The account access token isn't the point and also why is there no way around reconnecting?

> You can specify multiple `-depot` params to download at once.

Nor is this gonna help
