### ISSUE TITLE
 what is 401 for ?

### ISSUE THREAD

**Issue by trillto** [SteamRE/DepotDownloader#498]
### What did you expect to happen?

to  download r6 completely 
![Screenshot 2024-05-01 103800](https://github.com/SteamRE/DepotDownloader/assets/168588558/9ca577d2-a264-4f7f-88f9-ab31272980d0)

### Instead of that, what actually happened?

![Screenshot 2024-05-01 103800](https://github.com/SteamRE/DepotDownloader/assets/168588558/77a30365-d227-40a9-8f3e-6ac800cff67b)

### Which operating system are you running on?

Windows

### Version

downloaded 2.5

### Additional Information

i opened the help on discord R6S: operation throwback  2.0

**Comment by trillto** [comment]
> ### What did you expect to happen?
> to download r6 completely ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327212915-9ca577d2-a264-4f7f-88f9-ab31272980d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM1NzIsIm5iZiI6MTcxNDcyMzI3MiwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEyOTE1LTljYTU3N2QyLWEyNjQtNGY3Zi04OGY5LWFiMzEyNzI5ODBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODAxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzQ1N2Y0NGJlMjFmMjA3NThkZDg2ODhiNzAxM2VkYTJlNDQ4ZjdlN2E3MjJlZmRjZTY1NzY5ZDNlNzgxNjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F2LQY2S8XzOzb18dHzhVntoAhEOdVQTRygP_QnWTXbs)
> 
> ### Instead of that, what actually happened?
> ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327213037-77a30365-d227-40a9-8f3e-6ac800cff67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM1NzIsIm5iZiI6MTcxNDcyMzI3MiwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEzMDM3LTc3YTMwMzY1LWQyMjctNDBhOS04ZjNlLTZhYzgwMGNmZjY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODAxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2MzNWYzYjFiMWQ4MzBiNDZhM2Q0NjAwMjdkYTVmN2FhZWM4NTFiZDcyMDBjMTEzYzg1ZDVmNjhjMjlkZmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pqYIjg-GnfgykbOO1lfJN42vkgEpk4lapNe963gU3wI)
> 
> ### Which operating system are you running on?
> Windows
> 
> ### Version
> downloaded 2.5
> 
> ### Relevant log output
> _No response_
> 
> ### Additional Information
> i opened the help on discord R6S: operation throwback 2.0

**Comment by trillto** [comment]
> ### What did you expect to happen?
> to download r6 completely ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327212915-9ca577d2-a264-4f7f-88f9-ab31272980d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM3MTIsIm5iZiI6MTcxNDcyMzQxMiwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEyOTE1LTljYTU3N2QyLWEyNjQtNGY3Zi04OGY5LWFiMzEyNzI5ODBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODAzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGQxNTc3YzM3MjAwYzUzOTA4MzlkNGM5M2YyMWUxNzJjMjc0NTlmZjgyMzY2YTJkY2IwZjdjZWEzNDQxOGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7VHSgbKSa_ix2wcjkzvnniDDlFSRO6z90jOUgYT-O-8)
> 
> ### Instead of that, what actually happened?
> ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327213037-77a30365-d227-40a9-8f3e-6ac800cff67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM3MTIsIm5iZiI6MTcxNDcyMzQxMiwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEzMDM3LTc3YTMwMzY1LWQyMjctNDBhOS04ZjNlLTZhYzgwMGNmZjY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODAzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWVmZjEyYWNlMjcyOGRjYTkwNWI5OTc3ODE2M2RjNzVjZTlmMTFmMmQwMmQzNDBmM2NhNmVmMzVhNzY1MWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s-UxaBLWpVG-a6sqNmAx7I8O6WIQ2PKtKHARWR6GyZI)
> 
> ### Which operating system are you running on?
> Windows
> 
> ### Version
> downloaded 2.5
> 
> ### Relevant log output
> _No response_
> 
> ### Additional Information
> i opened the help on discord R6S: operation throwback 2.0



> ### What did you expect to happen?
> to download r6 completely ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327212915-9ca577d2-a264-4f7f-88f9-ab31272980d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM4NjEsIm5iZiI6MTcxNDcyMzU2MSwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEyOTE1LTljYTU3N2QyLWEyNjQtNGY3Zi04OGY5LWFiMzEyNzI5ODBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzUxZmUwZjQyOTk0MTQ1YTQ2NDE0ODRmOGU2NzM4NDI3MTc4NjVlY2Q4MmFiNzcxMmVlMmQ5NDI5YTlhZTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tcXK-JrcvtK9_9VP3_ne8RlxawGxrRs5hT8vJhhxvPE)
> 
> ### Instead of that, what actually happened?
> ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327213037-77a30365-d227-40a9-8f3e-6ac800cff67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM4NjEsIm5iZiI6MTcxNDcyMzU2MSwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEzMDM3LTc3YTMwMzY1LWQyMjctNDBhOS04ZjNlLTZhYzgwMGNmZjY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTQzYmJkNzAxMGM1OTgxOTUzMDJhMWYzNTI2ZDA2MTNjN2E1ZmU3NGNjNDAyNDM2Y2QxYjU1YTVkYTkzZTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v82ajPqeHnDtZLk1Xr4bZF4aIT9OcfNZOK8ffTrSxeQ)
> 
> ### Which operating system are you running on?
> Windows
> 
> ### Version
> downloaded 2.5
> 
> ### Relevant log output
> _No response_
> 
> ### Additional Information
> i opened the help on discord R6S: operation throwback 2.0



> ### What did you expect to happen?
> to download r6 completely ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327212915-9ca577d2-a264-4f7f-88f9-ab31272980d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM4NjEsIm5iZiI6MTcxNDcyMzU2MSwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEyOTE1LTljYTU3N2QyLWEyNjQtNGY3Zi04OGY5LWFiMzEyNzI5ODBkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzUxZmUwZjQyOTk0MTQ1YTQ2NDE0ODRmOGU2NzM4NDI3MTc4NjVlY2Q4MmFiNzcxMmVlMmQ5NDI5YTlhZTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tcXK-JrcvtK9_9VP3_ne8RlxawGxrRs5hT8vJhhxvPE)
> 
> ### Instead of that, what actually happened?
> ![Screenshot 2024-05-01 103800](https://private-user-images.githubusercontent.com/168588558/327213037-77a30365-d227-40a9-8f3e-6ac800cff67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjM4NjEsIm5iZiI6MTcxNDcyMzU2MSwicGF0aCI6Ii8xNjg1ODg1NTgvMzI3MjEzMDM3LTc3YTMwMzY1LWQyMjctNDBhOS04ZjNlLTZhYzgwMGNmZjY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwODA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTQzYmJkNzAxMGM1OTgxOTUzMDJhMWYzNTI2ZDA2MTNjN2E1ZmU3NGNjNDAyNDM2Y2QxYjU1YTVkYTkzZTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v82ajPqeHnDtZLk1Xr4bZF4aIT9OcfNZOK8ffTrSxeQ)
> 
> ### Which operating system are you running on?
> Windows
> 
> ### Version
> downloaded 2.5
> 
> ### Relevant log output
> _No response_
> 
> ### Additional Information
> i opened the help on discord R6S: operation throwback 2.0

**Comment by nutterthanos** [comment]
i've never seen http 401 error on downloading chunks before

**Comment by Eucliddd** [comment]
same herer

**Comment by SlejmUr** [comment]
401 error means the chunk file isn't found in the server, suggestion for it is to wait like an hour or something (and try again).
Also please do NOT open any issue here regarding the R6:S Throwback Related issues.

**Comment by RANDOMaBcD** [comment]
通过抓包发现，这应该是你的cdn问题，大陆内的cdn需要一个t参数和一个k参数，这应该是用于验证，
例如`http://dl.steam.clngaa.com/depot/1948981/manifest/3254038805619712034/5/9322460286420585911?t=1719430635&k=86b012a1030d43fe943de0f3575f2bb4`如果没有参数则会401报错

**Comment by qinlinzi** [comment]
大陆要怎么样加上这个验证参数呢
