### ISSUE TITLE
DepotDownloader - Wrong Compressed Size

### ISSUE THREAD

**Issue by nutterthanos** [SteamRE/DepotDownloader#499]
### What did you expect to happen?

It shows the correct size in bytes in comparison to what the appinfo would show:
Content Manifest for Depot 1551361

Manifest ID / date     : 3142817682348922585 / 11/05/2024 4:17:39 AM
Total number of files  : 20782
Total number of chunks : 168057
Total bytes on disk    : 155377970375
Total bytes compressed : 144624978320

### Instead of that, what actually happened?

it shows an different download/compressed size compared to appinfo:
Content Manifest for Depot 1551361

Manifest ID / date     : 3142817682348922585 / 11/05/2024 4:17:39 AM
Total number of files  : 20782
Total number of chunks : 168057
Total bytes on disk    : 155377970375
Total bytes compressed : 147453118224

### Which operating system are you running on?

Windows

### Version

2.6.0

### Additional Information

note this is with all depot's not just this one and also the different number in Total bytes compressed which i got from appinfo
the correct number i got from current manifest but says in current appinfo is 144624978320 not 147453118224 which is what i got from using the -manifest-only command and then reading the manifest_{depotid}_{manifest_id}.txt file and looking at the top

**Comment by xPaw** [comment]
I don't see what the bug is, or how we would even fix it. All DD does is loop over the files and sum up the sizes.

https://github.com/SteamRE/DepotDownloader/blob/65c07130a1f3beac9b489f5a52ee4a58ff1f3c40/DepotDownloader/ContentDownloader.cs#L1305
