### ISSUE TITLE
Failing to download Dota 2 workshop tools

### ISSUE THREAD

**Issue by ash47** [SteamRE/DepotDownloader#5]
I am using the latest release (2.1.1), I just asked it to download the depot that contains the workshop tools:

-app 570 -depot 313250

It downloads most of the stuff, but I noticed several errors during the install, aka, it failed to find a server with a given chunk, and is kept saying "aborting", it finished downloading and I was left with all the files, only, most were corrupted, so it was useless.

I'm happy to get the exact error(s) if that will help.

Thanks.

**Comment by psychonic** [comment]
This should be fixed now with bdfd56b4825b4

**Comment by ash47** [comment]
Neat
