### ISSUE TITLE
无法下载workshop项目

### ISSUE THREAD

**Issue by senioi** [SteamRE/DepotDownloader#52]
root@test-ub:~/depotdownloader# dotnet DepotDownloader.dll -pubfile 1710420172 -username ueser -password 123456
Error: -app not specified!

**Comment by azuisleet** [comment]
The 2.3.0 release does not include the pubfile command, the 2.4.0 release is still pending.

You will need to clone the repo and build it manually:
`git clone https://github.com/SteamRE/DepotDownloader.git`
`dotnet build DepotDownloader /p:Configuration=Release`
`dotnet DepotDownloader/bin/Release/netcoreapp2.0/DepotDownloader.dll -pubfile 1710420172`
