### ISSUE TITLE
Launching app fail?

### ISSUE THREAD

**Issue by Yunoextract1** [SteamRE/DepotDownloader#522]
### What did you expect to happen?

The app was supposed to launch and take me into the typing area like CMD

### Instead of that, what actually happened?

but it crashed instead right at launch. Do I need to open Steam first or open the app in another way? I'm not very good at coding, sorry :(

### Which operating system are you running on?

Windows

### Version

2.6.0

**Comment by voided** [comment]
> The app was supposed to launch and take me into the typing area like CMD

It isn't supposed to. See: https://github.com/SteamRE/DepotDownloader/discussions/288
