### ISSUE TITLE
Process stalls at "Downloading depot" or Downloading manifiest"

### ISSUE THREAD

**Issue by lukespragg** [SteamRE/DepotDownloader#54]
This has only just started happening within the last week maybe the last few days. Attempted on multiple systems/networks. Even the basics fail: `dotnet DepotDownloader.dll -app 258550`

![image](https://user-images.githubusercontent.com/671337/60187281-50d17300-97fb-11e9-8c64-da9eca361b65.png)

![image](https://user-images.githubusercontent.com/671337/60187433-93934b00-97fb-11e9-9218-07c9c6aa1824.png)

**Comment by azuisleet** [comment]
Confirmed. It's failing to bootstrap because of missing servers from CMsgClientServerList.

**Comment by a1batross** [comment]
I just wanted to post it here. Tried to update to latest beta SteamKit also and this still happens.

**Comment by lukespragg** [comment]
> I just wanted to post it here. Tried to update to latest beta SteamKit also and this still happens.

Yeah, that's the first thing I tried; should have mentioned! Thanks.

**Comment by Gh0stBlade** [comment]
.......

**Comment by azuisleet** [comment]
It looks like there's no easy way to construct the CDNClient.Server class, so additional work will be needed to fix this

**Comment by azuisleet** [comment]
Alright, a new ContentServerDirectoryService: https://github.com/SteamRE/SteamKit/pull/699
has been added to SteamKit, to be consumed in DepotDownloader: https://github.com/SteamRE/DepotDownloader/commit/c6975323d2915a451119260ded45032a47e4fa47

**Comment by lukespragg** [comment]
Working great, thanks! Release is up on NuGet by the way, compiled locally to test too.

**Comment by rfht** [comment]
Hi, thanks for the quick fix! Any chance this can be tagged as a hotfix release, ideally with zip attached? (depotdownloader-2.3.0-hotfix2 ...)

**Comment by azuisleet** [comment]
I have pushed out 2.3.1:
https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.1
