### ISSUE TITLE
Is it possible to obtain the .manifest file while using the -manifest-only command?

### ISSUE THREAD

**Issue by hxy310** [SteamRE/DepotDownloader#551]
### What problem is this feature trying to solve?

Obtain the .manifest file at the same time

### How would you like it to be solved?

Is it possible to obtain the .manifest file while using the -manifest-only command?

### Have you considered any alternative solutions

no

**Comment by NicknineTheEagle** [comment]
Fixed in https://github.com/SteamRE/DepotDownloader/pull/476. DepotDownloader now uses Steam compatible .manifest files.
