### ISSUE TITLE
Make batch file work when called from any working directory.

### ISSUE THREAD

**Issue by gibbed** [SteamRE/DepotDownloader#56]
I couldn't figure out where you're pulling `depotdownloader.bat` from for releases, so instead of forking and sending a PR, have an issue instead.

`No executable found matching command "dotnet-DepotDownloader.dll". See https://aka.ms/missing-command for more information.`

To fix this nonsense, change the line in `depotdownloader.bat` from `dotnet DepotDownloader.dll %*` to `dotnet %~dp0DepotDownloader.dll %*`.

**Comment by yaakov-h** [comment]
I believe those are created by the .NET SDK, not us.

**Comment by azuisleet** [comment]
Yeah, there are two wrapper scripts. I've updated `depotdownloader.bat` and replaced the release archive `depotdownloader-2.3.1.zip`
