### ISSUE TITLE
files not downloading properly or at all / depotdownloader UI not opening

### ISSUE THREAD

**Issue by senseibryce** [SteamRE/DepotDownloader#568]
### What did you expect to happen?

i click updates game files and the game files download in the folder i have setup

### Instead of that, what actually happened?

i clicked updates game files and nothing happened then it keeps giving me a "update may have failed, exit code: -2147450730"

### Which operating system are you running on?

Windows

### Version

2.7.3.0

### Command

i just clicked the "Update Game Files" with validate checked

### Relevant log output

```shell
Updating 1 servers
Updating server 1 of 1
Updating: "ASA Server 1" in C:\ark_asa_island
Update may have failed, exit code: -2147450730
Finished updating servers
Some servers may have failed to update. Please check the above log.
```

### Additional Information

its a repeating process no matter what i try
i ran the app as admin
i checked the firewall and let DepotDownloader through it

**Comment by xPaw** [comment]
This is not DD log or latest version.
