### ISSUE TITLE
Ark updater

### ISSUE THREAD

**Issue by badizsik** [SteamRE/DepotDownloader#578]
### What did you expect to happen?

Update ark servers or install files

### Instead of that, what actually happened?

Nothing happened and get error code -2147450730
![Capture](https://github.com/user-attachments/assets/f5f21fd8-08a1-415d-909e-369e0740aec2)

### Which operating system are you running on?

Windows

### Version

v2.7.3+0fb803b5f6485d081112387298754263025c6d58

### Command

Update

**Comment by yaakov-h** [comment]
There is no information here relevant to DepotDownloader. Please seek help from whatever "ASACT" is first.
