### ISSUE TITLE
Can't download depots:"NotFound (Not Found)'

### ISSUE THREAD

**Issue by senioi** [SteamRE/DepotDownloader#59]
Thank you for making this amazing tool.
This is a good dedicated server update solution.

i using for Don't Starve Together dedicated server 

command:

> dotnet DepotDownloader.dll -pubfile 1839858501 -username test -password test

Error:

> Downloading depot manifest...Got CDN auth token for cache3-hkg1.steamcontent.com result: OK (expires 2019/9/14 12:40:54)

> Initialized connection to content server cache3-hkg1.steamcontent.com:443 (SteamCache) with depot id 322330

> Encountered error downloading manifest for depot 322330 784111807996283035: Response status code does not indicate success: NotFound (Not Found).

> Got CDN auth token for cache1-hkg1.steamcontent.com result: OK (expires 2019/9/14 12:40:54)
> Initialized connection to content server cache1-hkg1.steamcontent.com:443 (SteamCache) with depot id 322330

> Encountered error downloading manifest for depot 322330 784111807996283035: Response status code does not indicate success: NotFound (Not Found).

**Comment by azuisleet** [comment]
I'm afraid I don't have this app, so I'm unable to do any diagnostics. It may be that some UGC content is not available through all CDN servers, and that we might need to target specific servers instead.

**Comment by senioi** [comment]
> I'm afraid I don't have this app, so I'm unable to do any diagnostics. It may be that some UGC content is not available through all CDN servers, and that we might need to target specific servers instead.

Hi,azuisleet, thanks for your reply.

Don't Starve Together any mod is can't download. 
e.g:https://steamcommunity.com/sharedfiles/filedetails/?id=1840284484

**Comment by a1batross** [comment]
@azuisleet if you're wondering and you want to fix it, I can share this game with you or probably just donate. :)

Write me on email: a1ba dot omarov at gmail dot com.

**Comment by azuisleet** [comment]
This might be https://github.com/SteamRE/SteamKit/issues/92 as suggested above

**Comment by rossengeorgiev** [comment]
This workshop item has a `file_url` from which the file can be downloaded directly. It doesn't go through steampipe.

```json
{
  "result": 1,
  "publishedfileid": "1840284484",
  "creator": "76561197973769935",
  "creator_appid": 245850,
  "consumer_appid": 322330,
  "consumer_shortcutid": 0,
  "filename": "mod_publish_data_file.zip",
  "file_size": "1371446",
  "preview_file_size": "526142",
  "file_url": "https://steamusercontent-a.akamaihd.net/ugc/770604271214145581/BDFDF57C646662088FD8562769E189C1F82A511B/",
  "preview_url": "https://steamuserimages-a.akamaihd.net/ugc/775104608727668226/AE7E3ACF19CF11774C697D3F9ADAF15DAB3CA8EA/",
  "url": "",
  "hcontent_file": "770604271214145581",
  "hcontent_preview": "775104608727668226",
```
