### ISSUE TITLE
How to Update files?

### ISSUE THREAD

**Issue by senioi** [SteamRE/DepotDownloader#60]
i using for some game dedicated server
When there is a mod update, use -pubfile, 
it will not delete old files, nor will it update existing files.

**Comment by azuisleet** [comment]
I don't believe any deletions are performed by DepotDownloader. If it did, I expect that it would have to be based on the presence of a previous manifest. 

As for failed updates, I would need an example of a depot that is not being updated correctly.

**Comment by senioi** [comment]
If you have "Portal Knights"
Test is easy.
just 
Start game ->  Play -> choose a character ->  Creative -> Create! -> click Edit -> add some map -> setting -> Public -> Copy url ->  use depotdownload  -> check file.
update a mod:
Start game ->  Play -> choose a character ->  Creative -> Create! -> click Edit ->  delete some map -> use depotdownload  -> check file.

**Comment by azuisleet** [comment]
This is likely out of scope for now. We do however manage deletions for depots now when we have depot manifests.
