### ISSUE TITLE
Corrupted Download

### ISSUE THREAD

**Issue by marcussacana** [SteamRE/DepotDownloader#66]
I used the DepotDownloader to download the FFXV outdated (there are only one build that can run with wine after all), but looks like the program downloaded some files corrupted.
I'm using the -validate to retry but I keep seeing random error like this:

![image](https://user-images.githubusercontent.com/10576957/68092165-0fb33480-fe67-11e9-993f-12bc29abbf90.png)

This is the second -validate but I keep geting error in random files, looks like I need repeat the validation many times to get everything right...?

If possible, add a option too to only validate the files and display what is corrupted, this will be usefull to me.

**Comment by azuisleet** [comment]
The WebException class hasn't been changed to the new SteamKitWebRequestException, so it isn't actually unexpected. The program will continue to re-download failed chunks, so the download only fails if the program aborts.

**Comment by marcussacana** [comment]
I think before create the issue 'maybe he retry after the error', but when I launch the game he give error to decompress certain files...
And i take that screenshot but isn't only that error that I see, but since I don't saved the log in the first download I don't know more what he said....

**Comment by azuisleet** [comment]
DepotDownloader does not run any installscripts. Running the validate command should not do anything special, as we only write chunks to disk that have the correct checksum.

**Comment by azuisleet** [comment]
Can you provide an example command lines that produces invalid files that are then repaired by a -validate run?

**Comment by marcussacana** [comment]
why not?

**Comment by azuisleet** [comment]
After reviewing the code, I cannot find anything that would reasonably cause corruption of the files.

If you can provide command lines showing corrupted download data, that a subsequent call with -validate fixes, I can investigate further.

If not, perhaps you have a faulty hard drive?

**Comment by marcussacana** [comment]
> If not, perhaps you have a faulty hard drive?

Don't scary me!, well... I used
`sh depotdownloader -username ***** -password ****** -app 637650 -depot 637651 -manifest 4711083296382803885 -validate`

**Comment by marcussacana** [comment]
If you are sure isn't fault of the DepotDownload you don't need investigate, if you are too confident about it, I can think in another possibility to the error, then don't care.

You can close the issue if you think is a false positive feedback.

**Comment by azuisleet** [comment]
I did a full download of the game using that command line and got:
```
Depot 637651 - Downloaded 82882843824 bytes (89383152981 bytes uncompressed)
Total downloaded: 82882777856 bytes (89384201557 bytes uncompressed) from 1 depots
```

Then I ran with -validate to check all the files I just downloaded and got:
```
Depot 637651 - Downloaded 0 bytes (0 bytes uncompressed)
Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots
```

I am unable to reproduce any file corruption. Any timeouts from when downloading chunks are retried, so that's not an issue either. If you have any more specific details, feel free to re-open this issue, but otherwise there's nothing to reproduce here.

**Comment by marcussacana** [comment]
Just to end any doubt, I found the problem, well, basically the outdated FFXV tried load my workshop subscriptions, and looks like the package format changed in the newest versions then the FFXV failed to start in the linux and the native windows since the other machine used the my same steam account.

Then a note, if someone create a issue of error in a outdated game execution like me, you can warn to disable DLCs and workshop content in the next time haha, sorry for the false positive and thanks for this amazing tool.

**Comment by azuisleet** [comment]
Excellent news, I'm glad you found a solution. We found a couple of items to improve in the process, so there's no wasted effort investigating things.

2e30364d8fbf02adf5d7dc09f6a21f0fa0311d49 - Double checking the cached manifest
0b598b43a71ac27da516d87eecd4541c8ca0ca68 - Ensuring the correct return code if a download fails
