### ISSUE TITLE
How to specify a language?

### ISSUE THREAD

**Issue by fossforus** [SteamRE/DepotDownloader#68]
I'm trying to fetch the english version of Morrowind for use with OpenMW, however I keep getting the german version and I'm uncertain how to fetch the english version specifically.
My command is: `depotdownloader -app 22320 -os windows -username 'User' -password 'Pass' -dir dir -validate`

**Comment by psychonic** [comment]
If you just specify an app, the current behavior is to download all of the depots that you have access to, and merge them together. Depending on the way the app handles content, depot ownership, and the order of the download, that could be causing the German content to overwrite the English content.

The only real workaround without code changes is to manually specify the depots you want (excluding the German one and possibly other languages), saving them to the same folder.

**Comment by fossforus** [comment]
Thanks. I'm currently trying to figure out how to get access to DepotID information; does it require signing up for the Steamworks Partnership and signing their NDA, because I'd rather not if I can avoid it.

**Comment by psychonic** [comment]
https://steamdb.info/app/22320/depots/

Looks like all of the English and shared content are together in a single depot. You should be able to just add the -depot parameter to your existing command line.

`depotdownloader -app 22320 -depot 22321 -os windows -username 'User' -password 'Pass' -dir dir -validate`

**Comment by fossforus** [comment]
Thank you very much. I managed to come across the same website shortly before you left your reply, I'll definitely keep it logged in case I need it again.
