### ISSUE TITLE
Feature request: Alternate path for config file

### ISSUE THREAD

**Issue by nosoop** [SteamRE/DepotDownloader#69]
I've written [the following manifest](https://gist.github.com/nosoop/b5a8ce5f8f83d3566b6531ad63a5e0df) to install `depotdownloader` into `%PATH%` via [scoop](https://scoop.sh/), so being able to read the configuration from a fixed, non-working directory would be useful.

The directory can either be the folder containing the DLL file or a manually-specified one on the command line.  It can also be one of the special folders as well, which would probably be better for cross-platform support.

Can't seem to compile a working build (it reports an unhandled exception that cannot be printed because `Exception.ToString()` failed &mdash; not sure if it's because I'm using the 2.1 runtime or because I'm building with `dotnet` instead of VS).  Would be willing to cobble together some C# and PR it myself if I could.

**Comment by Deathreus** [comment]
Sidenote: Nice

**Comment by azuisleet** [comment]
The DepotDownloader.config configuration file includes some target-specific data like the last manifest ID. I don't think it really needs to be portable... although a system-wide configuration file for sentry data, login keys, and content server data may be useful.

DpeotDownloader already writes to CWD when no path is specified. Should we simply include the config as a dot file in the CWD or target directory?

**Comment by azuisleet** [comment]
It sounds like the first option is more reasonable: We should split login data off into a persistent directory  (perhaps just LocalStorage for now?), and move manifest data into the target directory as a dotfile

**Comment by nosoop** [comment]
Didn't realize `DepotDownloader.config` covered all of that information; originally thought it was just for login data.

The auth / manifest data split sounds fine with me.

**Comment by azuisleet** [comment]
Take a look at the new release, 2.3.2:
https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.2

This should standardize the location for the configuration so there's nothing being written to the current working directory.

**Comment by nosoop** [comment]
Looks like it's throwing an error within [this function](https://github.com/SteamRE/DepotDownloader/blob/master/DepotDownloader/AccountSettingsStore.cs#L71-L89).

[Stack trace attached.](https://github.com/SteamRE/DepotDownloader/files/4169401/ddl.log)  I'd guess it's because of read access.

**Comment by azuisleet** [comment]
Oops, you're right, I missed that.

I have updated the zip file. Can you fetch it again?

**Comment by nosoop** [comment]
Yep; latest release works as expected in my basic tests.  Thanks again!
