### ISSUE TITLE
Download stuck (wrong server?)

### ISSUE THREAD

**Issue by KawaiiWafu** [SteamRE/DepotDownloader#71]
So, after Valve has decided to disable download_depot function for older manifests, I decided to try this tool, unfortunately, it always gets stuck between 1% and 2% and doesn't continue downloading. I does however, use a netword, the speed jumps to ~15 Mbps, ~7 Mbps, then to 0 Mbps and this has been going on for 7 hours, stuck on one file.

It's not my internet being bad, downloading using download_depot in Steam console went at over 300 Mbps without drops. Is there any way to fix this? How do I know what cellid I should use?

**Comment by KawaiiWafu** [comment]
Apparently, it downloads from servers in Hong Kong. How do I get a cellid for a server that's usable for me?

**Comment by azuisleet** [comment]
What Cell ID is being reported on the command line?

**Comment by KawaiiWafu** [comment]
I think it was 45. Is there any list I can follow?

**Comment by azuisleet** [comment]
You can see the list of servers for 45 here:

https://api.steampowered.com/IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell=45

I'm not super familiar with all the rules and restrctions around content servers, as some of that logic lives in steamclient.

**Comment by shakeyourbunny** [comment]
Similar problem, have to restart the download several times. 

Perhaps it would be neat to add a timeout for non receiving data?

**Comment by azuisleet** [comment]
Can you provide a log with the -debug command line option? 

Intermittent CDN failures are handled and retried. The download should continue until interrupted by the user, or we run out of CDN endpoints to try.

I would need to understand if this is something where no progress can be made on any CDN, as you should be seeing timeout errors since all calls have timeouts associated with them:

https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/CDNClient.cs#L485

It would also be helpful to know what cell ID is being reported after logging in.

**Comment by KawaiiWafu** [comment]
![Startup of depotdownloader](https://user-images.githubusercontent.com/11209667/79643173-06621e00-81a2-11ea-9d5c-6dae9bf83582.png)
`[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientClanState (822) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientClanState (822) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientClanState (822) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientClanState (822) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientClanState (822) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientClanState (822) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientSessionToken (850) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientClanState (822) (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CDNClient] Failed to complete web request to https://cache6-vie1.steamcontent.com:443/depot/792301/chunk/09edeab426abb5f0fa38053a171e2042694ad918: The operation was canceled.
Encountered unexpected error downloading chunk 09edeab426abb5f0fa38053a171e2042694ad918: The operation was canceled.
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)
[CMClient] Sent -> EMsg: ClientHeartBeat (Proto: True)`

This is the log with -debug option. Downloading through steam with a cheat engine workaround downloads pretty fast without an issues, but that might not work forever. There must be some error in chosing the server to download from.

**Comment by azuisleet** [comment]
Nothing here indicates a fatal error. You're certain no progress is being made?

**Comment by azuisleet** [comment]
Please try https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.4 as it contains a fix for CDN server lookup by cell id.

**Comment by KawaiiWafu** [comment]
[log.txt](https://github.com/SteamRE/DepotDownloader/files/4497670/log.txt)
Tried it, but same issue. The download is just stuck. It does use network, but much less than Steam with the same command used to.

**Comment by azuisleet** [comment]
You're saying the last line was the errors for chunk 01b7c78c15b5ba1b50a1ddead8acd94bd2102b81 and no further network or disk I/O is happening?

**Comment by KawaiiWafu** [comment]
Yes, the network did spike a bit several times to a couple of megabits (again, with Steam it used to use hundreds of megabits), then drops down and nothing is being written to the disk.

**Comment by azuisleet** [comment]
DepotDownloader doesn't pipeline the downloads the way most downloaders do, so all chunks are fetch/write in order. That's something I would like to improve.

As for dropping to zero and no writes, I'm not certain, since we should be seeing the timeouts. This could be an I/O stall on the disk (like anti-virus software?) or the 10 second timeout using the CancellationTokenSource is not working. We would see timeouts in the log as "Encountered error downloading chunk"

**Comment by KawaiiWafu** [comment]
Hmm... it definitely shouldn't be blocked by anything else. Running it as an administrator, not using any sort of anti-virus / protection software. Tried a different manifest of the game, this time I got the downloading chunk errors.
` 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\NextIcon.png
Encountered error downloading chunk 98aa4c7c4f2b1740fa673f993814fa282a342b46: InternalServerError
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_05x_Pressed.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_1x_Normal.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\BackIcon.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_Screen_Rotation_Hovered.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_1x_Pressed.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_Screen_Rotation_Pressed.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_Screen_Rotation_Normal.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\TrashCan_Small.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_05x_Normal.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\TrashCan.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\cursor_cardinal_cross.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PlusSymbol_12x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\ellipsis_12x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_05x_Hovered.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\eyedropper_16px.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\Cross_12x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_error_16x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\denied_16x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_info_16x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_redo_16px.png
Got CDN auth token for cache40-fra1.steamcontent.com result: OK (expires 25.04.2020 21:22:53)
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_help_16x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_undo_16px.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_tab_toolbar_16px.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\PIEWindow\WindowButton_1x_Hovered.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\cursor_grab.png
Encountered error downloading chunk b0509176f849cef96073455596e65a72d25cac2c: InternalServerError
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_tab_WidgetReflector_40x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_tab_WidgetReflector_16x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\notificationlist_fail.png
 00,28% depots\792301\4335651\Engine\Content\Slate\MessageLog\Log_Error.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\toolbar_expand_16x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\MessageLog\Log_Warning.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\Border.PNG
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\notificationlist_success.png
 00,28% depots\792301\4335651\Engine\Content\Slate\MessageLog\Log_Note.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\Menu_Background.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\HyperlinkUnderline.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\HyperlinkDotted.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\Notification_Border_Flash.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\DashedBorder.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\Button.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\ToolTip_Background.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\Menu_Background_Inverted_Border_Bold.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\ToolTip_BrightBackground.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\BrushWireframe.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_generic_toolbar.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\FlatColorSquare.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\Hyperlink.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\DefaultPawn_16px.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_Downloads_16x.png
Got CDN auth token for cache61-fra1.steamcontent.com result: OK (expires 25.04.2020 21:22:54)
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\Lit.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Old\White.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Icons\icon_warning_16x.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\Wireframe.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\TestRotation.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\UE4Icon.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\NewLevelBlank.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Tutorials\TutorialShadow.png
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\GammaReference.png
 00,28% depots\792301\4335651\Engine\Shaders\StandaloneRenderer\D3D\GammaCorrectionCommon.hlsl
 00,28% depots\792301\4335651\Engine\Shaders\StandaloneRenderer\OpenGL\SlateElementPixelShader.glsl
 00,28% depots\792301\4335651\Engine\Content\Slate\Testing\Unlit.png
 00,28% depots\792301\4335651\Engine\Shaders\StandaloneRenderer\D3D\SlateElementPixelShader.hlsl
 00,28% depots\792301\4335651\Engine\Shaders\StandaloneRenderer\OpenGL\SlateVertexShader.glsl
 00,28% depots\792301\4335651\Engine\Programs\CrashReportClient\Config\DefaultEngine.ini
 00,28% depots\792301\4335651\Engine\Content\Slate\Tutorials\TutorialBorder.png
 00,28% depots\792301\4335651\Engine\Shaders\StandaloneRenderer\OpenGL\SplashFragmentShader.glsl
 00,29% depots\792301\4335651\TheBeastInside.exe
 00,29% depots\792301\4335651\Engine\Shaders\StandaloneRenderer\OpenGL\SplashVertexShader.glsl
 00,29% depots\792301\4335651\Manifest_NonUFSFiles_Win64.txt
 00,29% depots\792301\4335651\Engine\Shaders\StandaloneRenderer\D3D\SlateDefaultVertexShader.hlsl
 00,29% depots\792301\4335651\Engine\Content\Slate\Old\ToolBar_Background.png
Encountered error downloading chunk 63b5d3dca2bcc133924c210dd0b9e527f4716f53: InternalServerError
Got CDN auth token for cache54-fra1.steamcontent.com result: OK (expires 25.04.2020 21:22:57)
Encountered error downloading chunk 63b5d3dca2bcc133924c210dd0b9e527f4716f53: NotFound
Got CDN auth token for cache31-fra1.steamcontent.com result: OK (expires 25.04.2020 21:22:58)
Encountered error downloading chunk 63b5d3dca2bcc133924c210dd0b9e527f4716f53: NotFound
 00,57% depots\792301\4335651\TheBeastInside\Content\Movies\DV_LoadingScreen.mp4
Got CDN auth token for cache46-fra1.steamcontent.com result: OK (expires 25.04.2020 21:22:58)
Encountered error downloading chunk 63b5d3dca2bcc133924c210dd0b9e527f4716f53: NotFound
Got CDN auth token for cache23-fra1.steamcontent.com result: OK (expires 25.04.2020 21:22:59)
Encountered error downloading chunk 63b5d3dca2bcc133924c210dd0b9e527f4716f53: NotFound
Got CDN auth token for cache6-vie1.steamcontent.com result: OK (expires 25.04.2020 21:22:59)
 00,85% depots\792301\4335651\TheBeastInside\Content\Movies\Mov_C07_Telescope_v03.mp4
Encountered error downloading chunk 1d5e7b0c5ee4bf2caf138de7947b3842f0b02bf0: InternalServerError
Got CDN auth token for cache14-fra1.steamcontent.com result: OK (expires 25.04.2020 21:23:03)
 00,98% depots\792301\4335651\TheBeastInside\Content\Movies\DV_Outro_NicolasBrick_01.wav
 01,09% depots\792301\4335651\TheBeastInside\Content\Movies\UE_Logo.mp4
 01,20% depots\792301\4335651\TheBeastInside\Binaries\Win64\TheBeastInside-Win64-Shipping.exe
 01,21% depots\792301\4335651\TheBeastInside\Content\Movies\UE_Logo_1.wav
 01,28% depots\792301\4335651\Engine\Extras\Redist\en-us\UE4PrereqSetup_x64.exe
 01,33% depots\792301\4335651\TheBeastInside\Content\Movies\DV_Outro_NicolasHunt_01.wav
 01,44% depots\792301\4335651\TheBeastInside\Content\Movies\DV_Outro_NicolasBrick_01.mp4
 01,49% depots\792301\4335651\TheBeastInside\Content\Splash\Splash.bmp
 01,60% depots\792301\4335651\TheBeastInside\Content\Movies\DV_Outro_NicolasHunt_01.mp4
 01,62% depots\792301\4335651\TheBeastInside\Content\Movies\DV_Outro_Flashbacks_01.mp4
Encountered error downloading chunk 09f26a4faae010ea22e138fa0f5988895b1c43dd: InternalServerError
Encountered error downloading chunk 0ac5970bcece9dc7035b5ad1f891f00b0ad96a2a: InternalServerError`

**Comment by azuisleet** [comment]
The errors are not fatal, as we are still making progress by attempting another server. If it was a fatal error downloading, the process would end

**Comment by KawaiiWafu** [comment]
Yeah, they're not fatal. But it gets stuck there and won't move.

**Comment by azuisleet** [comment]
The important piece is if there is network and disk I/O. The output to the console is after a file is downloaded, so it's possible it's making progress on a large file, but you don't see the output until after all chunks are fetched.

**Comment by KawaiiWafu** [comment]
Well, yes, there indeed is disk and network I/O. But it's so negligible that it's essentially not different from not downloading. Downloading it through Steam (with the Cheat Engine workaround) took just a while to finish, in that time, the percentage in depot downloader doesn't even move.

I'd much rather use the Depot Downloader, because having to do some Cheat Engine workarounds is just messy - and might stop working with next Steam update.

**Comment by azuisleet** [comment]
Could you give this build a shot:

https://www.dropbox.com/s/9c6uiwv684brvnc/DepotDownloader-with-outstanding-limit.zip?dl=0

https://gist.github.com/azuisleet/28b4fb3fe07695024a623e0b78797ae4

I am wondering if the timeout is failing to run, which would normally resolve slow connections

**Comment by KawaiiWafu** [comment]
[log.txt](https://github.com/SteamRE/DepotDownloader/files/4498041/log.txt)
It loads the network a bit more, but still doesn't seem to move after about 20 minutes.

**Comment by azuisleet** [comment]
Any difference with:

https://www.dropbox.com/s/shfdres97ibgavr/DepotDownloader-with-cdn-token-limit.zip?dl=0

**Comment by KawaiiWafu** [comment]
[log.txt](https://github.com/SteamRE/DepotDownloader/files/4498082/log.txt)
Pretty much the same results.

**Comment by azuisleet** [comment]
I don't have any more ideas currently. I'll keep the issue open, but we'll probably have to work on some more diagnostics.

**Comment by KawaiiWafu** [comment]
Sure, always happy to assist.

**Comment by azuisleet** [comment]
Here's the last thing I think worth checking, reducing the connection timeout to something short like 2 seconds. If the stalls are slow connections, you should see a lot of "The operation was canceled". I want to confirm if this is something we are even able to recover from if we detected slow connections:

https://www.dropbox.com/s/so7a9zkp8tlr50w/depotdownloader-short-timeout.zip?dl=0

https://gist.github.com/azuisleet/28b4fb3fe07695024a623e0b78797ae4

**Comment by KawaiiWafu** [comment]
The console seems to be full of "Encountered error downloading manifest for depot 792301 1959931036373210771: The operation was canceled" and doesn't start downloading at all.

**Comment by azuisleet** [comment]
Until I or someone else adds additional diagnostics, I cannot do anything further for slow downloads.
