### ISSUE TITLE
Connection to Steam failed

### ISSUE THREAD

**Issue by fsjNk** [SteamRE/DepotDownloader#76]
Hi, I get this error username and password is 110% not wrong I already checked it multiple times but its definitely not wrong. Any fixes ?

![Depotdownlaoder bug](https://user-images.githubusercontent.com/62440135/77187548-f38df800-6ad4-11ea-9090-f3b25bdb09ba.png)

**Comment by azuisleet** [comment]
Can you reach https://api.steampowered.com/ISteamDirectory/GetCMList/v1?cellid=0?

Are you behind any firewalls?

**Comment by azuisleet** [comment]
Please download https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.3 and retry with the -debug command line option to get further diagnostic information.

**Comment by fsjNk** [comment]
> Please download https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.3 and retry with the -debug command line option to get further diagnostic information.

yes i can reach the link.

i did it with the -debug command and the output is:
![Depotdownlaoder -debug](https://user-images.githubusercontent.com/62440135/77833809-6ab03580-7140-11ea-8511-f7e262e8a033.png)

and after this i tried to turn off my firewall and it worked
