### ISSUE TITLE
Downloading depots for EFLC (and possibly other "half owned" games as well)

### ISSUE THREAD

**Issue by ClaudeLib** [SteamRE/DepotDownloader#77]
After updating Grand Theft Auto IV to Complete Edition, Rockstar Games have "retired" the standalone "Episodes from Liberty City" bundle. This means that everyone who has ever bought/activated the game no longer have it in their library and cannot download and play it anymore. Downloading the game's depots via DepotDownloader doesn't work either, it returns "App 12220 (Grand Theft Auto: Episodes from Liberty City) is not available from this account."
However, it actually is still possible to download its depot via Steam Console, and after downgrading the client, it's possible to download the older manifests as well. This means that the procedure slightly differs between DD and Steam. Can something be done to make DD able to download such games?

**Comment by psychonic** [comment]
You can see [here](https://steamdb.info/app/12220/subs/), that the app is no longer available from any packages, and thus no longer owned by anyone. You cannot request a depot key for an app/depot you don't have ownership of. It's possible that Steam still has the depot keys cached (in config.vdf), and ignores ownership when using the console command if it has that cached.

I suppose we could add an argument to pass in a depot key to use.

**Comment by psychonic** [comment]
I did a quick prototyping of this, and it works well enough, but I had to replace the requesting of the CDN token with "". I recall there being a recentish change where that an actual token is not needed in most cases, but I don't remember the specifics of that.

**Comment by dotgodly** [comment]
Is there a way I can grab my depot keys before they are removed?

**Comment by dotgodly** [comment]
Is there code of this somewhere? I recently dug out my old EFLC keys and passing depot keys would be awesome for me to use.

**Comment by DaRkL3AD3R** [comment]
Even if you got the files, I'm pretty sure Rockstar broke something on this version of EFLC completely as it crashes the second it gets to the main menu. I have full backups of both the original GTA IV v1.0.4.0 and EFLC and GTA IV works fine from this standalone backup but EFLC is totally broken and won't get past the legal screens.

**Comment by azuisleet** [comment]
While interesting, I'm not sure there's a compelling reason to support this (downloading with only a depot key). It's definitely a step in the direction of piracy that I'm not interested in taking.

**Comment by NicknineTheEagle** [comment]
You do not actually need a locally provided depot key to download half-owned depots like EFLC. I did some testing and it appears that Steam servers would return the depot key if two conditions are met:
1) the app's ReleaseState is "released" (or you own a package with ReleaseStateOverride)
2) you own the depot in question
You do not need to actually own the parent app.
That being said, this scenario where you own a depot but not its parent app is exceedingly rare so I'm not sure if it's own covering this edge case.
