### ISSUE TITLE
The new depotkey-based download method violates applicable law.

### ISSUE THREAD

**Issue by Christsnatcher** [SteamRE/DepotDownloader#78]
Hello,

this is not a bug report, but rather a warning to the developers of this tool. The newly introduced depotkey-based, de facto anonymous download method gives everyone the opportunity to download content from Valve's servers which they actually doesn't have a legit subscription for, all they need is the resp. depotkey string which they could e.g. get from a friend. This fulfills the definition of "theft", violates the SSA and will DEFINITIVELY have legal consequences for the tool developers if Valve should become aware of it. So, in your own interest, take into consideration to delete all depotkey-related commits as soon as possible. Thank you.

**Comment by asherkin** [comment]
There is no code for downloading using depotkeys in this repository.
