### ISSUE TITLE
Steam disconnects after successful authentication in a loop

### ISSUE THREAD

**Issue by Gbps** [SteamRE/DepotDownloader#79]
Using multiple parallel instances of DD at once sometimes results in each one entering a connect/disconnect loop and making no progress:
```Connecting to Steam3... Done!
Logging '<user>' into Steam3... Done!
Using Steam3 suggested CellID: 63
Got 139 licenses for account!
Got session token!
Lost connection to Steam. Reconnecting
 Done!
Logging '<user>' into Steam3... Done!
Got 139 licenses for account!
Got session token!
Lost connection to Steam. Reconnecting
```

It doesn't seem to give any more detailed information about any difficulties it encounters, so it seems like it's encountering some kind of authentication rate limiting. The output folders are independent in each of the instances of DD, so I don't think there's any file races. The problem appears to resolve itself after about 10 minutes as long as I do not run multiple instances of DepotDownloader at the same time.

During one execution, I encountered this hang which it never recovered from:
```
Connecting to Steam3... Done!
Logging '<user>' into Steam3... Done!
Using Steam3 suggested CellID: 63
Got 139 licenses for account!
Got session token!
Accepted new login key for account <user>
Got session token!
```

Is this a backend issue?

**Comment by azuisleet** [comment]
It is indeed, you are most likely being booted off for concurrent sessions. DepotDownloader uses a fixed LoginID, and Steam only allows one session per LoginID:

https://github.com/SteamRE/DepotDownloader/blob/def0729fce3249339ff7a9e29ef6adeac2aaee1d/DepotDownloader/ContentDownloader.cs#L352

**Comment by Gbps** [comment]
Thanks for the quick reply. Must the LoginID remain fixed or is this something I can correct myself?

**Comment by azuisleet** [comment]
You can customize it yes, there just isn't a command line option to do so.

**Comment by Gbps** [comment]
Would this be a good candidate for a PR that I can produce for you?

**Comment by azuisleet** [comment]
If it makes sense, sure. I would add an option to specify a custom LoginID and update the README instructions.

**Comment by Gbps** [comment]
I'll experiment and get back to you. Thank you for the help.
