### ISSUE TITLE
Disconnected from Steam

### ISSUE THREAD

**Issue by Nico2525** [SteamRE/DepotDownloader#82]
![Anmerkung 2020-03-25 224456](https://user-images.githubusercontent.com/19267144/77591627-a359d000-6ef0-11ea-8e65-a0ecf5df4870.png)
I´m trying to download the release manifest from HL-Alyx but I always get this. I have tried downloading the current manifest and also tried another game I own but it won´t download. 
I have installed .Net Core 2.0.9 and 3.1 and I´m using Windows 10

PS [REDACTED]\DepotDownloader 2.3.2> dotnet DepotDownloader.dll -app 546560 -depot 546561 -manifest 2483063085863239688 -username [REDACTED] -password [REDACTED] -dir "F:\Half-Life Alyx 1.0"
Connecting to Steam3... Done!
Logging '[REDACTED]' into Steam3...Disconnected from Steam
This account is protected by Steam Guard.
Please enter your 2 factor auth code from your authenticator app: [REDACTED]
Retrying Steam3 connection... Done!
Logging '[REDACTED]' into Steam3... Done!
Using Steam3 suggested CellID: 89
Got 362 licenses for account!
Got session token!
Got AppInfo for 546560
Accepted new login key for account [REDACTED]
Disconnected from Steam

**Comment by azuisleet** [comment]
I'm uncertain how to diagnose this, as it appears to be a failure somewhere after RequestAppInfo but before it reaches `Using app branch`. Between those two lines, I don't see any code that would return without printing something:

https://github.com/SteamRE/DepotDownloader/blob/master/DepotDownloader/ContentDownloader.cs#L410

This may require adding a logging diagnostic option to print out the net messages.

**Comment by azuisleet** [comment]
Please download https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.3 and retry with the -debug command line option to get further diagnostic information.

**Comment by Nico2525** [comment]
I tried it with version 2.3.3 and it works now. I left my pc on so there was no magic restart. Once I complete the download I will try again with 2.3.2. Even though you didn´t change anything that could have fixed it. Maybe the Steam servers had a bad day yesterday?

Sometimes I get the message " Failed to complete web request to https://cache1-waw1.steamcontent.com:443/depot/546561/chunk/2189c7bfa005678ac74b4e45ce2bd67482de9429: The operation was canceled.
Encountered unexpected error downloading chunk 2189c7bfa005678ac74b4e45ce2bd67482de9429: The operation was canceled." But I would say thats just a normal timeout or similar.

However thank you for your help.

**Comment by azuisleet** [comment]
Those are indeed expected errors. If you are able to reproduce any connection issues, feel free to open a new issue.
