### ISSUE TITLE
Disconnected from Steam 2.3.2

### ISSUE THREAD

**Issue by Nico2525** [SteamRE/DepotDownloader#84]
Reference: https://github.com/SteamRE/DepotDownloader/issues/82
So I have tried with 2.3.2 again and it doesn´t work but is somehow fixed in 2.3.3 for me.
I downloaded the source for 2.3.2 and added the code for the debug.

As an error it gave me this : 

Got AppInfo for 546560
[CMClient] Sent -> EMsg: ClientPICSProductInfoRequest (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientPICSProductInfoResponse (8904) (Proto: True)
[CMClient] <- Recv'd EMsg: Multi (1) (Proto: True)
[CMClient] <- Recv'd EMsg: ClientPICSProductInfoResponse (8904) (Proto: True)
[SteamClient] Unhandled 'ArgumentException' exception from 'SteamApps' handler: 'An item with the same key has already been added. Key: 414170'
Disconnected from Steam

I´m unsure if this is still an issue as it seems to be fixed in 2.3.3 but maybe it is of some use to you.

**Comment by xPaw** [comment]
This was fixed by 8dd7c4c1b58a3436799bec1617035d330aa2901c
