### ISSUE TITLE
Registry is not supported on this platform

### ISSUE THREAD

**Issue by BowDown097** [SteamRE/DepotDownloader#87]
No matter what manifest, depot, or app I choose, or what parameters I put in, I always get this exception upon running the program. It seems to be a problem with this program specifically, as I've actually played with registry stuff when coding in C# myself on this device. I'm running Windows 8.1, 64-bit.
![image](https://user-images.githubusercontent.com/42720004/79677586-e170a980-81a7-11ea-9f33-18e576d250e3.png)

**Comment by azuisleet** [comment]
Are you using the Pre-release version?

**Comment by azuisleet** [comment]
The packaging for 2.3.4 was wrong, please download the latest release, 2.3.3

**Comment by BowDown097** [comment]
Ah, alright, yes I was :) thanks

**Comment by azuisleet** [comment]
The packaging for 2.3.4 has been corrected.
