### ISSUE TITLE
Unable to get steam3 credentials

### ISSUE THREAD

**Issue by gitezu** [SteamRE/DepotDownloader#9]
Using version 2.1.1 and windows xp.
Yesterday, this command works great:
-app 243730 -depot 243732 -username 1234 -password 1234 -dir G:\sdk
But today i tried: 
-app 243730 -depot 243732 -username 1234 -password 1234 -dir G:\sdkbeta -beta upcoming
and also the previous command again and does not work at all.

Connecting to Steam3...Timeout connecting to Steam3.
Unable to get steam3 credentials.

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at DepotDownloader.ContentDownloader.AccountHasAccess(UInt32 depotId)
   at DepotDownloader.ContentDownloader.DownloadApp(UInt32 appId, UInt32 depotId
, String branch)
   at DepotDownloader.Program.Main(String[] args)

Thanks.

**Comment by LennyPenny** [comment]
Got the same problem

**Comment by LennyPenny** [comment]
Fixed in https://github.com/SteamRE/DepotDownloader/commit/b599768bd8108d64419914a6d65484cc7520f6d1
