### ISSUE TITLE
Encountered unexpected While Download

### ISSUE THREAD

**Issue by DemonRem** [SteamRE/DepotDownloader#91]
Encountered unexpected error downloading chunk 0cb43c8e40e4c6148fac63209cbe68c6e14de312: The operation was canceled.

**Comment by azuisleet** [comment]
This is an expected error. The error message indicates you are using an old version of the tool, so please upgrade to a newer version. If there is a blocking issue, please open a new issue.

**Comment by Pennek** [comment]
I got the same error while using version 2.4.7

[Image](https://pennek.s-ul.eu/z15dxNUb.png)

**Comment by bnthomason** [comment]
Same error with latest version

**Comment by Evidark** [comment]
+

**Comment by Evidark** [comment]
Same.

**Comment by Evidark** [comment]
+

**Comment by Evidark** [comment]
Same.
