### ISSUE TITLE
Can't get the dll to run with dotnet

### ISSUE THREAD

**Issue by thaurane** [SteamRE/DepotDownloader#92]
I am using release 2.3.4

With version 3.1 sdk and installing it properly (since it does it for me) I get the error:  "It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download"

When I downloaded the sdk 2.0 version all I got was a few files so I put them in the folder with your utility. I then navigated to it with command prompt and ran the command in the readme to try to download a depot. I get the error: "Did you mean to run dotnet SDK commands? Please install dotnet SDK from: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409" 

Can you provide a step by step walkthrough on how to get this utility to run properly? The README documentation is not enough. I have never used the .net framework commands before and have no idea what I am doing.

**Comment by azuisleet** [comment]
You need a .NET Core Runtime that is 2.0 or newer:
https://dotnet.microsoft.com/download

**Comment by thaurane** [comment]
Thank you for the quick reply. I got it to kinda work so now I have another problem. When I try to get the depot, it connects to steam correctly but as anonymous. Since the app is now available from anonymous I try to use my steam credentials. Here is an example of the commands I am trying to use:

dotnet D:\depotdownloader-2.3.4\DepotDownloader.dll -app 12345 [-depot 123456 [-manifest 123456789] | [-username myusername [-password mypasword]]

and

dotnet D:\depotdownloader-2.3.4\DepotDownloader.dll -app 12345 [-depot 123456 [-manifest 123456789] [-username myusername [-password mypasword]]

With the first example it says "[-username' is not recognized as an internal or external command". With the second example it still tries to connect as anonymous.

**Comment by azuisleet** [comment]
The brackets simply indicate optional parameters. Your full list of parameters is:

`dotnet depotdownloader.dll -app 12345 -depot 123456 -manifest 123456789 -username myusername -password mypassword`

**Comment by thaurane** [comment]
It is now downloading! Thank you for the support! I'll create another ticket if I run into further issues with your utility.
