### ISSUE TITLE
Does using DepotDownloader Reveal Your Steam Id and Password?

### ISSUE THREAD

**Issue by brandflake11** [SteamRE/DepotDownloader#97]
Hello all,
I know this is open source, but I am not skilled enough to go through the entirety of the code. I want to use this program, but I am unsure about using it. Does this reveal your steam login credentials to anyone when you use it? I just want to make sure not to give my steam account to someone else. 

Thank you very much for all of your help!

**Comment by azuisleet** [comment]
The only way to know is to audit and build the code yourself. That may not be reasonable for everyone, but here's what the program is intended to do, assuming you have an official release:

- The program asks Steam what the list of CM servers is
- The program connects and negotiates the encrypted channel with Steam (CM)
- The program performs a login (and any assisted 2fa) using the same commands that the Steam Client uses.
- The program does not store passwords, but Steam Guard tokens and Login Keys are persisted as necessary (or requested)

**Comment by brandflake11** [comment]
@azuisleet Thank you for the reply with this. Knowing this uses the same login commands that the steam client uses makes me feel safe with this! Also, I tried the software after making the issue, and with Steam Guard working with Depotdownloader, I feel pretty confident in using Depotdownloader. Thanks!
