### ISSUE TITLE
Manifest expired

### ISSUE THREAD

**Issue by ljs2000** [SteamRE/DepotDownloader#98]
...
Downloading depot manifest...Got CDN auth token for ctr-00201-na-us-east.steam-content-dnld-1.us-e2-cdn.cqloud.com result: Fail (expires 1/1/1970 12:00:00 AM)
Disconnected from Steam

**Comment by azuisleet** [comment]
What Cell ID is being reported after logging in? What is the app, depot, and manifest you are trying to download?

**Comment by ljs2000** [comment]
I'm not sure what a cell id is... But i'm trying to download an older version of terraria and the manifest is here on steamdb: https://steamdb.info/depot/105601/manifests/

**Comment by ljs2000** [comment]
Oh and the app is 105600 and the depot is 105601

**Comment by azuisleet** [comment]
Unfortunately I don't know how the cqloud CDN is meant to work. It could be that a CDN token is not required, but it's not clear why it would return an error.

This probably needs to be investigated by watching Steam Client with NetHook, or tracing the Steam Client logic.

**Comment by azuisleet** [comment]
Can you post the result from https://api.steampowered.com/IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=63

**Comment by ljs2000** [comment]
Sure but what is cell id 63?

**Comment by ljs2000** [comment]
{"response":{"servers":[{"type":"OpenCache","source_id":167,"cell_id":9999,"load":0,"weighted_load":0,"num_entries_in_client_list":1,"host":"ctr-00201-na-us-east.steam-content-dnld-1.us-e2-cdn.cqloud.com","vhost":"ctr-00201-na-us-east.steam-content-dnld-1.us-e2-cdn.cqloud.com","use_as_proxy":true,"proxy_request_path_template":"/%host%%path%","https_support":"mandatory","preferred_server":true},{"type":"SteamCache","source_id":172,"cell_id":63,"load":71,"weighted_load":64.7458343505859375,"num_entries_in_client_list":1,"host":"cache24-iad1.steamcontent.com","vhost":"cache24-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":33,"cell_id":63,"load":75,"weighted_load":66.0131149291992188,"num_entries_in_client_list":1,"host":"cache3-iad1.steamcontent.com","vhost":"cache3-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":17,"cell_id":50,"load":84,"weighted_load":68.0583419799804688,"num_entries_in_client_list":1,"host":"cache3-atl1.steamcontent.com","vhost":"cache3-atl1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":227,"cell_id":63,"load":77,"weighted_load":70.06121826171875,"num_entries_in_client_list":1,"host":"cache14-iad1.steamcontent.com","vhost":"cache14-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":226,"cell_id":63,"load":77,"weighted_load":70.3093719482421875,"num_entries_in_client_list":1,"host":"cache13-iad1.steamcontent.com","vhost":"cache13-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":169,"cell_id":63,"load":76,"weighted_load":72.1143112182617188,"num_entries_in_client_list":1,"host":"cache21-iad1.steamcontent.com","vhost":"cache21-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":165,"cell_id":63,"load":78,"weighted_load":77.4709091186523438,"num_entries_in_client_list":1,"host":"cache17-iad1.steamcontent.com","vhost":"cache17-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":174,"cell_id":63,"load":93,"weighted_load":77.7851104736328125,"num_entries_in_client_list":1,"host":"cache26-iad1.steamcontent.com","vhost":"cache26-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":166,"cell_id":63,"load":80,"weighted_load":78.9024276733398438,"num_entries_in_client_list":1,"host":"cache18-iad1.steamcontent.com","vhost":"cache18-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":168,"cell_id":63,"load":77,"weighted_load":78.9883270263671875,"num_entries_in_client_list":1,"host":"cache20-iad1.steamcontent.com","vhost":"cache20-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":139,"cell_id":63,"load":76,"weighted_load":83.71697998046875,"num_entries_in_client_list":1,"host":"cache16-iad1.steamcontent.com","vhost":"cache16-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":34,"cell_id":63,"load":84,"weighted_load":83.808807373046875,"num_entries_in_client_list":1,"host":"cache4-iad1.steamcontent.com","vhost":"cache4-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":167,"cell_id":63,"load":78,"weighted_load":84.9811859130859375,"num_entries_in_client_list":1,"host":"cache19-iad1.steamcontent.com","vhost":"cache19-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":224,"cell_id":63,"load":78,"weighted_load":88.6386032104492188,"num_entries_in_client_list":1,"host":"cache11-iad1.steamcontent.com","vhost":"cache11-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":137,"cell_id":63,"load":79,"weighted_load":88.7137908935546875,"num_entries_in_client_list":1,"host":"cache15-iad1.steamcontent.com","vhost":"cache15-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":32,"cell_id":63,"load":74,"weighted_load":90.5182876586914063,"num_entries_in_client_list":1,"host":"cache2-iad1.steamcontent.com","vhost":"cache2-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":14,"cell_id":50,"load":90,"weighted_load":93.4331207275390625,"num_entries_in_client_list":1,"host":"cache9-atl1.steamcontent.com","vhost":"cache9-atl1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":170,"cell_id":63,"load":86,"weighted_load":93.9669418334960938,"num_entries_in_client_list":1,"host":"cache22-iad1.steamcontent.com","vhost":"cache22-iad1.steamcontent.com","https_support":"optional","preferred_server":false},{"type":"SteamCache","source_id":120,"cell_id":1,"load":86,"weighted_load":99.62310791015625,"num_entries_in_client_list":1,"host":"cache8-ord1.steamcontent.com","vhost":"cache8-ord1.steamcontent.com","https_support":"optional","preferred_server":false}]}}

**Comment by azuisleet** [comment]
Alright. OpenCache support is going to take some time, so in the mean time, I have filtered the CDN server list to just the server types we currently support. Take a look at:

https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.5

**Comment by ljs2000** [comment]
> Alright. OpenCache support is going to take some time, so in the mean time, I have filtered the CDN server list to just the server types we currently support. Take a look at:
> 
> https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.5

Thanks so much for your help and quick response. I appreciate it

**Comment by ljs2000** [comment]
*NOTICE* I FIXED THE PROBLEM
I didn't have steam kit installed, I was just using the dll. I downloaded the release zip file instead of compiling it with VS17 and it worked. Don't know if you still need to add opencach support or whatever but hope this helps clear some things up
